#! /bin/sh

# ident "@(#)postremove	1.6	96/05/03 SMI"
# SUNWpcelx postremove script

PATH="/bin:/usr/bin:/usr/sbin:${PATH}"
export PATH

REMDRV=/usr/sbin/rem_drv

trap "rm -f /tmp/$$.*;exit" 0 1 2 3 13 15

${REMDRV} -b ${BASEDIR} pcelx
rm -f ${BASEDIR}/dev/pcelx*

touch ${BASEDIR}/reconfigure

exit 0
