/*
 * Copyright (c) 1993, by Sun Microsystems, Inc.
 */

#pragma ident	"@(#)pcic.h	1.1	93/10/29 SMI"

#define CHIP_PCIC			1
#define CHIP_PHIC			2
#define CHIP_ICCNT			3

#define PCIC_INDEX_REG			0x3E0
#define PCIC_DATA_REG			0x3E1
#define PCIC_ID_AND_REV			0x00
#define PCIC_IF_STATUS			0x01
#define PCIC_POWER_CONTROL		0x02
#define PCIC_INT_AND_GEN_CONTROL	0x03
#define PCIC_CARD_STATUS_CHANGE		0x04
#define PCIC_CARD_STATUS_INT_CONTROL	0x05
#define PCIC_ADDRESS_WINDOW_ENABLE	0x06
#define PCIC_IO_CONTROL			0x07
#define PCIC_IO_ADDR_0_START_LB		0x08
#define PCIC_IO_ADDR_0_START_HB		0x09
#define PCIC_IO_ADDR_0_STOP_LB		0x0A
#define PCIC_IO_ADDR_0_STOP_HB		0x0B
#define PCIC_IO_ADDR_1_START_LB		0x0C
#define PCIC_IO_ADDR_1_START_HB		0x0D
#define PCIC_IO_ADDR_1_STOP_LB		0x0E
#define PCIC_IO_ADDR_1_STOP_HB		0x0F
#define PCIC_SM_ADDR_0_START_LB		0x10
#define PCIC_SM_ADDR_0_START_HB		0x11
#define PCIC_SM_ADDR_0_STOP_LB		0x12
#define PCIC_SM_ADDR_0_STOP_HB		0x13
#define PCIC_CM_OFFSET_ADDR_0_LB	0x14
#define PCIC_CM_OFFSET_ADDR_0_HB	0x15
#define PCIC_SM_ADDR_1_START_LB		0x18
#define PCIC_SM_ADDR_1_START_HB		0x19
#define PCIC_SM_ADDR_1_STOP_LB		0x1A
#define PCIC_SM_ADDR_1_STOP_HB		0x1B
#define PCIC_CM_OFFSET_ADDR_1_LB	0x1C
#define PCIC_CM_OFFSET_ADDR_1_HB	0x1D
#define PCIC_SM_ADDR_2_START_LB		0x20
#define PCIC_SM_ADDR_2_START_HB		0x21
#define PCIC_SM_ADDR_2_STOP_LB		0x22
#define PCIC_SM_ADDR_2_STOP_HB		0x23
#define PCIC_CM_OFFSET_ADDR_2_LB	0x24
#define PCIC_CM_OFFSET_ADDR_2_HB	0x25
#define PCIC_SM_ADDR_3_START_LB		0x28
#define PCIC_SM_ADDR_3_START_HB		0x29
#define PCIC_SM_ADDR_3_STOP_LB		0x2A
#define PCIC_SM_ADDR_3_STOP_HB		0x2B
#define PCIC_CM_OFFSET_ADDR_3_LB	0x2C
#define PCIC_CM_OFFSET_ADDR_3_HB	0x2D
#define PCIC_SM_ADDR_4_START_LB		0x30
#define PCIC_SM_ADDR_4_START_HB		0x31
#define PCIC_SM_ADDR_4_STOP_LB		0x32
#define PCIC_SM_ADDR_4_STOP_HB		0x33
#define PCIC_CM_OFFSET_ADDR_4_LB	0x34
#define PCIC_CM_OFFSET_ADDR_4_HB	0x35

/* register bit definitions */

#define PCIC_MW_REG_ACTIVE		0x40	/* attribute/common memory */
#define PCIC_MW_WRITE_PROTECT        	0x80	/* mem window wp */
#define PCIC_MW_WAIT_STATE_BITS		0xC0
#define PCIC_IOW_ENABLE_WINDOW_0	0x40
#define PCIC_IOW_ENABLE_WINDOW_1	0x80
#define PCIC_ENABLE_12V			0x9A
#define PCIC_ENABLE_5V			0x95
#define PCIC_CLEAR_CARD_CHANGE		0x08
#define PCIC_CARD_DETECTED		0x0C
#define PCIC_CARD_READY			0x20
