#
# Copyright (c) 1996 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.21	96/02/27 SMI"

include		$(SRC)/cmd/sgs/libld/Makefile.com

.KEEP_STATE:

all:		$(DYNLIB) $(LIBLINKS)

install:	all $(ROOTDYNLIB)

lint:		$(LINTLIB)

include		$(SRC)/cmd/sgs/libld/Makefile.targ
