#
# Copyright (c) 1996, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident @(#)Makefile   1.2     96/05/28
#

.KEEP_STATE:

all install clean clobber lint: FRC
	@cd init.d; pwd; $(MAKE) $(MFLAGS) $@

FRC:

