#
#ident	"@(#)Makefile	1.1	95/05/05 SMI"
#
# Copyright (c) 1993-1995 by Sun Microsystems, Inc.
# All rights reserved.
#
# cmd/eeprom/ppc/prep/Makefile
#
# Platform specific Makefile for the eeprom command.
#
# PLATFORM is the target for the binary installation.
#
# PLATLINKS is a list of platforms which are to be linked to this binary
#	at the file level.
#
SRCDIR		= ../..
PLATFORM	= prep
PLATLINKS	=

include $(SRCDIR)/Makefile.com

.KEEP_STATE:

all:	$(PROG)

include $(SRCDIR)/Makefile.targ
