#
# uts/i86/Makefile.rules
#
# Copyright (c) 1996 by Sun Microsystems, Inc.
# All Rights Reserved
#
#pragma ident	"@(#)Makefile.rules	1.26	96/06/18 SMI"
#
#	This Makefile defines all file modules and build rules for the
# directory uts/i86 and it's children. These are the source files which
# are specific to the i86 processor.
#

#
#	This was implemented by pattern matching rules of the form:
#
# $(OBJS_DIR)/%.o:	 $(UTSBASE)/common/os/%.c
#	$(COMPILE.c) -o $@ $<
#
# $(LINTS_DIR)/%.ln:	$(UTSBASE)/common/os/%.c
#	@($(LHEAD) $(LINT.c) $< $(LTAIL))
#
#	For each directory containing source. This proved to slow under
#	Nse because it caused a significant additional number of stats
#	and stats are real slow under TFS. If TFS performance should
#	improve, one might consider returning to the former implementation.
#	In the former implementation, this file (Makefile.rules) was not
#	needed and the pattern matching rules were in Makefile.files.
#

#
#	C object build rules
#
#	The following are alphabetized by source file path. Please maintain
# this ordering.
#

#
#	Lint `object' build rules.
#
#	The following are alphabetized by source file path. Please maintain
#       this ordering.
#
