#
#      "@(#)Makefile 1.2 94/10/13"
#
# Makefile for 50install/files
#

include ../../Makefile.cmd

# FILES are those things that are just used as is
FILES= OWconfig msm.conf

.KEEP_STATE:

all: ${FILES}

install: all $(ROOTAI86FILES)

msgs msgs_test strip clean:

include ../../Makefile.targ
