#
# uts/i86pc/Makefile.rules
#
# Copyright (c) 1996 Sun Microsystems, Inc.
# All Rights Reserved.
#pragma ident	"@(#)Makefile.rules	1.83	96/08/19 SMI"
#


#	This Makefile defines the build rules for the directory uts/i86pc
#	and its children. These are the source files which are i86pc
#	"implementation architecture" dependent.
#

#
#	This was implemented by pattern matching rules of the form:
#
# $(OBJS_DIR)/%.o:	 $(UTSBASE)/i86pc/os/%.c
#	$(COMPILE.c) -o $@ $<
#
# $(LINTS_DIR)/%.ln:	$(UTSBASE)/i86pc/os/%.c
#	@($(LHEAD) $(LINT.c) $< $(LTAIL))
#
#	For each directory containing source. This proved to slow under
#	Nse because it caused a significant additional number of stats
#	and stats are real slow under TFS. If TFS performance should
#	improve, one might consider returning to the former implementation.
#	In the former implementation, this file (Makefile.rules) was not
#	needed and the pattern matching rules were in Makefile.files.
#

#
#	C object build rules
#
#	The following are alphabetized by source file path. Please maintain
# this ordering.
#
# Check ordering with:
# sed -n '/^\$(OBJS_DIR)/s/.*:	*//p' Makefile.rules | sort -c
# sed -n '/^\$(LINTS_DIR)/s/.*:	*//p' Makefile.rules | sort -c
#
$(OBJS_DIR)/avintr.o:		$(UTSBASE)/common/io/avintr.c
	$(COMPILE.c) -o $@ $(UTSBASE)/common/io/avintr.c

$(OBJS_DIR)/hardclk.o:		$(UTSBASE)/common/io/hardclk.c
	$(COMPILE.c) -o $@ $(UTSBASE)/common/io/hardclk.c

$(OBJS_DIR)/bootdev.o:		$(UTSBASE)/i86/os/bootdev.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86/os/bootdev.c

$(OBJS_DIR)/confunix.o:		$(UTSBASE)/i86pc/conf/confunix.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/conf/confunix.c

$(OBJS_DIR)/autoconf.o:		$(UTSBASE)/i86pc/io/autoconf.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/io/autoconf.c

$(OBJS_DIR)/eisa.o:		$(UTSBASE)/i86pc/io/eisa.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/io/eisa.c

$(OBJS_DIR)/hrtimers.o:		$(UTSBASE)/i86pc/io/hrtimers.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/io/hrtimers.c

$(OBJS_DIR)/isa.o:		$(UTSBASE)/i86pc/io/isa.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/io/isa.c

$(OBJS_DIR)/mc.o:		$(UTSBASE)/i86pc/io/mc.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/io/mc.c

$(OBJS_DIR)/pci.o:		$(UTSBASE)/i86pc/io/pci/pci.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/io/pci/pci.c

$(OBJS_DIR)/pci_autoconfig.o:	$(UTSBASE)/i86pc/io/pci/pci_autoconfig.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/io/pci/pci_autoconfig.c

$(OBJS_DIR)/pci_mech1.o:		$(UTSBASE)/i86pc/io/pci/pci_mech1.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/io/pci/pci_mech1.c

$(OBJS_DIR)/pci_mech2.o:		$(UTSBASE)/i86pc/io/pci/pci_mech2.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/io/pci/pci_mech2.c

$(OBJS_DIR)/pci_neptune.o:		$(UTSBASE)/i86pc/io/pci/pci_neptune.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/io/pci/pci_neptune.c

$(OBJS_DIR)/pci_orion.o:		$(UTSBASE)/i86pc/io/pci/pci_orion.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/io/pci/pci_orion.c

$(OBJS_DIR)/uppc.o:		$(UTSBASE)/i86pc/io/psm/uppc.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/io/psm/uppc.c

$(OBJS_DIR)/uppc_ml.o:		$(UTSBASE)/i86pc/io/psm/uppc_ml.s
	$(COMPILE.s) -o $@ $(UTSBASE)/i86pc/io/psm/uppc_ml.s

$(OBJS_DIR)/rootnex.o:		$(UTSBASE)/i86pc/io/rootnex.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/io/rootnex.c

$(OBJS_DIR)/tcic.o:		$(UTSBASE)/i86pc/io/tcic.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/io/tcic.c

$(OBJS_DIR)/vdi.o:		$(UTSBASE)/i86pc/io/vdi.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/io/vdi.c

$(OBJS_DIR)/locore.o:		$(UTSBASE)/i86pc/ml/locore.s
	$(COMPILE.s) -o $@ $(UTSBASE)/i86pc/ml/locore.s

$(OBJS_DIR)/mpcore.o:		$(UTSBASE)/i86pc/ml/mpcore.s
	$(COMPILE.s) -o $@ $(UTSBASE)/i86pc/ml/mpcore.s

$(OBJS_DIR)/notes.o:		$(UTSBASE)/i86pc/ml/notes.s
	$(COMPILE.s) -o $@ $(UTSBASE)/i86pc/ml/notes.s

$(OBJS_DIR)/v86locore.o:	$(UTSBASE)/i86pc/ml/v86locore.s
	$(COMPILE.s) -o $@ $(UTSBASE)/i86pc/ml/v86locore.s

$(OBJS_DIR)/bp_map.o:		$(UTSBASE)/i86pc/os/bp_map.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/os/bp_map.c

$(OBJS_DIR)/ddi_impl.o:		$(UTSBASE)/i86pc/os/ddi_impl.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/os/ddi_impl.c

$(OBJS_DIR)/dvma.o:		$(UTSBASE)/i86pc/os/dvma.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/os/dvma.c

$(OBJS_DIR)/mach_sysconfig.o:		$(UTSBASE)/i86pc/os/mach_sysconfig.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/os/mach_sysconfig.c

$(OBJS_DIR)/machdep.o:		$(UTSBASE)/i86pc/os/machdep.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/os/machdep.c

$(OBJS_DIR)/mlsetup.o:		$(UTSBASE)/i86pc/os/mlsetup.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/os/mlsetup.c

$(OBJS_DIR)/mp_call.o:		$(UTSBASE)/i86pc/os/mp_call.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/os/mp_call.c

$(OBJS_DIR)/mp_implfuncs.o:	$(UTSBASE)/i86pc/os/mp_implfuncs.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/os/mp_implfuncs.c

$(OBJS_DIR)/mp_machdep.o:	$(UTSBASE)/i86pc/os/mp_machdep.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/os/mp_machdep.c

$(OBJS_DIR)/mp_startup.o:	$(UTSBASE)/i86pc/os/mp_startup.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/os/mp_startup.c

$(OBJS_DIR)/ppage.o:		$(UTSBASE)/i86pc/os/ppage.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/os/ppage.c

$(OBJS_DIR)/startup.o:		$(UTSBASE)/i86pc/os/startup.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/os/startup.c

$(OBJS_DIR)/trap.o:		$(UTSBASE)/i86pc/os/trap.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/os/trap.c

$(OBJS_DIR)/x_call.o:		$(UTSBASE)/i86pc/os/x_call.c
	$(COMPILE.c) -o $@ $(UTSBASE)/i86pc/os/x_call.c

#
#	Lint `object' build rules
#
#	The following are alphabetized by source file path. Please maintain
# this ordering.
#
$(LINTS_DIR)/avintr.ln:		$(UTSBASE)/common/io/avintr.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/common/io/avintr.c $(LTAIL))

$(LINTS_DIR)/hardclk.ln:	$(UTSBASE)/common/io/hardclk.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/common/io/hardclk.c $(LTAIL))

$(LINTS_DIR)/bootdev.ln:	$(UTSBASE)/i86/os/bootdev.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86/os/bootdev.c $(LTAIL))

$(LINTS_DIR)/confunix.ln:	$(UTSBASE)/i86pc/conf/confunix.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/conf/confunix.c $(LTAIL))

$(LINTS_DIR)/autoconf.ln:	$(UTSBASE)/i86pc/io/autoconf.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/io/autoconf.c $(LTAIL))

$(LINTS_DIR)/eisa.ln:		$(UTSBASE)/i86pc/io/eisa.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/io/eisa.c $(LTAIL))

$(LINTS_DIR)/hrtimers.ln:	$(UTSBASE)/i86pc/io/hrtimers.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/io/hrtimers.c $(LTAIL))

$(LINTS_DIR)/isa.ln:		$(UTSBASE)/i86pc/io/isa.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/io/isa.c $(LTAIL))

$(LINTS_DIR)/mc.ln:		$(UTSBASE)/i86pc/io/mc.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/io/mc.c $(LTAIL))

$(LINTS_DIR)/pci.ln:		$(UTSBASE)/i86pc/io/pci/pci.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/io/pci/pci.c $(LTAIL))

$(LINTS_DIR)/pci_autoconfig.ln:	$(UTSBASE)/i86pc/io/pci/pci_autoconfig.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/io/pci/pci_autoconfig.c $(LTAIL))

$(LINTS_DIR)/pci_mech1.ln:		$(UTSBASE)/i86pc/io/pci/pci_mech1.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/io/pci/pci_mech1.c $(LTAIL))

$(LINTS_DIR)/pci_mech2.ln:		$(UTSBASE)/i86pc/io/pci/pci_mech2.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/io/pci/pci_mech2.c $(LTAIL))

$(LINTS_DIR)/pci_neptune.ln:		$(UTSBASE)/i86pc/io/pci/pci_neptune.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/io/pci/pci_neptune.c $(LTAIL))

$(LINTS_DIR)/pci_orion.ln:		$(UTSBASE)/i86pc/io/pci/pci_orion.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/io/pci/pci_orion.c $(LTAIL))

$(LINTS_DIR)/uppc.ln:		$(UTSBASE)/i86pc/io/psm/uppc.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/io/psm/uppc.c $(LTAIL))

$(LINTS_DIR)/uppc_ml.ln:	$(UTSBASE)/i86pc/io/psm/uppc_ml.s
	@($(LHEAD) $(LINT.s) $(UTSBASE)/i86pc/io/psm/uppc_ml.s $(LTAIL))

$(LINTS_DIR)/rootnex.ln:	$(UTSBASE)/i86pc/io/rootnex.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/io/rootnex.c $(LTAIL))

$(LINTS_DIR)/tcic.ln:		$(UTSBASE)/i86pc/io/tcic.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/io/tcic.c $(LTAIL))

$(LINTS_DIR)/vdi.ln:		$(UTSBASE)/i86pc/io/vdi.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/io/vdi.c $(LTAIL))

$(LINTS_DIR)/locore.ln:		$(UTSBASE)/i86pc/ml/locore.s
	@($(LHEAD) $(LINT.s) $(UTSBASE)/i86pc/ml/locore.s $(LTAIL))

$(LINTS_DIR)/mpcore.ln:		$(UTSBASE)/i86pc/ml/mpcore.s
	@($(LHEAD) $(LINT.s) $(UTSBASE)/i86pc/ml/mpcore.s $(LTAIL))

$(LINTS_DIR)/notes.ln:		$(UTSBASE)/i86pc/ml/notes.s
	@($(LHEAD) $(LINT.s) $(UTSBASE)/i86pc/ml/notes.s $(LTAIL))

$(LINTS_DIR)/v86locore.ln:	$(UTSBASE)/i86pc/ml/v86locore.s
	@($(LHEAD) $(LINT.s) $(UTSBASE)/i86pc/ml/v86locore.s $(LTAIL))

$(LINTS_DIR)/bp_map.ln:		$(UTSBASE)/i86pc/os/bp_map.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/os/bp_map.c $(LTAIL))

$(LINTS_DIR)/ddi_impl.ln:	$(UTSBASE)/i86pc/os/ddi_impl.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/os/ddi_impl.c $(LTAIL))

$(LINTS_DIR)/dvma.ln:		$(UTSBASE)/i86pc/os/dvma.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/os/dvma.c $(LTAIL))

$(LINTS_DIR)/mach_sysconfig.ln:	$(UTSBASE)/i86pc/os/mach_sysconfig.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/os/mach_sysconfig.c $(LTAIL))

$(LINTS_DIR)/machdep.ln:	$(UTSBASE)/i86pc/os/machdep.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/os/machdep.c $(LTAIL))

$(LINTS_DIR)/mlsetup.ln:	$(UTSBASE)/i86pc/os/mlsetup.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/os/mlsetup.c $(LTAIL))

$(LINTS_DIR)/mp_call.ln:	$(UTSBASE)/i86pc/os/mp_call.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/os/mp_call.c $(LTAIL))

$(LINTS_DIR)/mp_implfuncs.ln:	$(UTSBASE)/i86pc/os/mp_implfuncs.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/os/mp_implfuncs.c $(LTAIL))

$(LINTS_DIR)/mp_machdep.ln:	$(UTSBASE)/i86pc/os/mp_machdep.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/os/mp_machdep.c $(LTAIL))

$(LINTS_DIR)/mp_startup.ln:	$(UTSBASE)/i86pc/os/mp_startup.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/os/mp_startup.c $(LTAIL))

$(LINTS_DIR)/ppage.ln:		$(UTSBASE)/i86pc/os/ppage.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/os/ppage.c $(LTAIL))

$(LINTS_DIR)/startup.ln:	$(UTSBASE)/i86pc/os/startup.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/os/startup.c $(LTAIL))

$(LINTS_DIR)/trap.ln:		$(UTSBASE)/i86pc/os/trap.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/os/trap.c $(LTAIL))

$(LINTS_DIR)/x_call.ln:		$(UTSBASE)/i86pc/os/x_call.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/i86pc/os/x_call.c $(LTAIL))
