/*
 * Copyright (c) 1991 Sun Microsystems, Inc.  All Rights Reserved. Sun
 * considers its source code as an unpublished, proprietary trade secret, and
 * it is available only under strict license provisions.  This copyright
 * notice is placed here only to protect Sun in the event the source is
 * deemed a published work.  Dissassembly, decompilation, or other means of
 * reducing the object code to human readable form is prohibited by the
 * license agreement under which this code is provided to the user or company
 * in possession of this copy.
 *
 * RESTRICTED RIGHTS LEGEND: Use, duplication, or disclosure by the Government
 * is subject to restrictions as set forth in subparagraph (c)(1)(ii) of the
 * Rights in Technical Data and Computer Software clause at DFARS 52.227-7013
 * and in similar clauses in the FAR and NASA FAR Supplement.
 */

#ifndef lint
#ident	"@(#)Base_stubs.c 1.12 93/04/08"
#endif

/*
 * Base_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `Base.G'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include <group.h>
#include "swmtool.h"
#include "defs.h"
#include "ui.h"


/*
 * Menu handler for `FileMenu (Save)'.
 */
Menu_item
Base_FileMenu_item0_callback(Menu_item item, Menu_generate op)
{
	Base_BaseWin_objects * ip = (Base_BaseWin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
#ifdef XV_DEBUG
		fputs("swmtool: Base_FileMenu_item0_callback: MENU_NOTIFY\n", stderr);
#endif /* XV_DEBUG */
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			ConfigFile(CONFIG_SAVE);
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `FileMenu (Save As...)'.
 */
Menu_item
Base_FileMenu_item1_callback(Menu_item item, Menu_generate op)
{
	Base_BaseWin_objects * ip = (Base_BaseWin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
#ifdef XV_DEBUG
		fputs("swmtool: Base_FileMenu_item1_callback: MENU_NOTIFY\n", stderr);
#endif /* XV_DEBUG */
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			ConfigFile(CONFIG_SAVEAS);
		}
		
		xv_set(File_FileWin->FileWin, XV_SHOW, TRUE, NULL);
		
		xv_set(File_FileWin->FileWin, XV_LABEL, dgettext("SUNW_INSTALL_SWM", "Software Manager:  Save As"), NULL);
		
		xv_set(File_FileWin->FileDoit, PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Save"), NULL);
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `ViewMenu (Prev Level)'.
 */
Menu_item
Base_ViewMenu_item0_callback(Menu_item item, Menu_generate op)
{
	Base_BaseWin_objects * ip = (Base_BaseWin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
#ifdef XV_DEBUG
		fputs("swmtool: Base_ViewMenu_item0_callback: MENU_NOTIFY\n", stderr);
#endif /* XV_DEBUG */
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			Module *prev = GetPreviousLevel();
			
			if (prev != (Module *)0)
				SetCurrentLevel((char *)0, prev);
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `ViewMenu (Command Window...)'.
 */
Menu_item
Base_ViewMenu_item1_callback(Menu_item item, Menu_generate op)
{
	Base_BaseWin_objects * ip = (Base_BaseWin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
#ifdef XV_DEBUG
		fputs("swmtool: Base_ViewMenu_item1_callback: MENU_NOTIFY\n", stderr);
#endif /* XV_DEBUG */
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		xv_set(Cmd_CmdWin->CmdWin, FRAME_CMD_PUSHPIN_IN, TRUE, NULL);
		xv_set(Cmd_CmdWin->CmdWin, XV_SHOW, TRUE, NULL);
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `ViewMenu (Space Meter...)'.
 */
Menu_item
Base_ViewMenu_item2_callback(Menu_item item, Menu_generate op)
{
	Base_BaseWin_objects * ip = (Base_BaseWin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
#ifdef XV_DEBUG
		fputs("swmtool: Base_ViewMenu_item2_callback: MENU_NOTIFY\n", stderr);
#endif /* XV_DEBUG */
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		xv_set(Meter_MeterWin->MeterWin, FRAME_CMD_PUSHPIN_IN, TRUE, NULL);
		xv_set(Meter_MeterWin->MeterWin, XV_SHOW, TRUE, NULL);
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `EditMenu (Native Environment)'.
 */
Menu_item
Base_EditMenu_item0_callback(Menu_item item, Menu_generate op)
{
	Base_BaseWin_objects * ip = (Base_BaseWin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
#ifdef XV_DEBUG
		fputs("swmtool: Base_EditMenu_item0_callback: MENU_NOTIFY\n", stderr);
#endif /* XV_DEBUG */
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			if (get_view() != VIEW_NATIVE) {
				set_installed_media((Module *)0);
				BrowseModules(MODE_UNSPEC, VIEW_NATIVE);
			}
		}
		
		xv_set(Client_ClientWin->ClientOs, PANEL_INACTIVE, TRUE, NULL);
		
		xv_set(Client_ClientWin->ClientArch, PANEL_INACTIVE, TRUE, NULL);
		
		xv_set(Client_ClientWin->ClientApply, PANEL_INACTIVE, TRUE, NULL);
		
		xv_set(Client_ClientWin->ClientReset, PANEL_INACTIVE, TRUE, NULL);
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `EditMenu (Add Client Support...)'.
 */
Menu_item
Base_EditMenu_item1_callback(Menu_item item, Menu_generate op)
{
	Base_BaseWin_objects * ip = (Base_BaseWin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
#ifdef XV_DEBUG
		fputs("swmtool: Base_EditMenu_item1_callback: MENU_NOTIFY\n", stderr);
#endif /* XV_DEBUG */
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			InitClientInfo((Xv_opaque)Client_ClientWin, MODE_INSTALL);
		}
		
		xv_set(Client_ClientWin->ClientWin, XV_LABEL, dgettext("SUNW_INSTALL_SWM", "Software Manager:  Add Client Support"), NULL);
		
		xv_set(Client_ClientWin->ClientWin, FRAME_CMD_PUSHPIN_IN, TRUE, NULL);
		xv_set(Client_ClientWin->ClientWin, XV_SHOW, TRUE, NULL);
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `EditMenu (Select All)'.
 */
Menu_item
Base_EditMenu_item3_callback(Menu_item item, Menu_generate op)
{
	Base_BaseWin_objects * ip = (Base_BaseWin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
#ifdef XV_DEBUG
		fputs("swmtool: Base_EditMenu_item3_callback: MENU_NOTIFY\n", stderr);
#endif /* XV_DEBUG */
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			SelectAllModules(1);
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `EditMenu (Deselect All)'.
 */
Menu_item
Base_EditMenu_item4_callback(Menu_item item, Menu_generate op)
{
	Base_BaseWin_objects * ip = (Base_BaseWin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
#ifdef XV_DEBUG
		fputs("swmtool: Base_EditMenu_item4_callback: MENU_NOTIFY\n", stderr);
#endif /* XV_DEBUG */
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			SelectAllModules(0);
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `BaseMenu (Package Properties...)'.
 */
Menu_item
Base_BaseMenu_item0_callback(Menu_item item, Menu_generate op)
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
#ifdef XV_DEBUG
		fputs("swmtool: Base_BaseMenu_item0_callback: MENU_NOTIFY\n", stderr);
#endif /* XV_DEBUG */
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			GetPackageInfo(GetCurrentModule());
		}
		
		xv_set(Pkg_PkgWin->PkgWin, FRAME_CMD_PUSHPIN_IN, TRUE, NULL);
		xv_set(Pkg_PkgWin->PkgWin, XV_SHOW, TRUE, NULL);
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `BaseMenu (Select Localizations...)'.
 */
Menu_item
Base_BaseMenu_item1_callback(Menu_item item, Menu_generate op)
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
#ifdef XV_DEBUG
		fputs("swmtool: Base_BaseMenu_item1_callback: MENU_NOTIFY\n", stderr);
#endif /* XV_DEBUG */
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			GetProductInfo(GetCurrentModule(), 1);
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `BaseMenu (Set Base Directory...)'.
 */
Menu_item
Base_BaseMenu_item4_callback(Menu_item item, Menu_generate op)
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
#ifdef XV_DEBUG
		fputs("swmtool: Base_BaseMenu_item4_callback: MENU_NOTIFY\n", stderr);
#endif /* XV_DEBUG */
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			GetPackageInfo(GetCurrentModule());
		}
		
		xv_set(Pkg_PkgWin->PkgWin, FRAME_CMD_PUSHPIN_IN, TRUE, NULL);
		xv_set(Pkg_PkgWin->PkgWin, XV_SHOW, TRUE, NULL);
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `BaseMenu (Expand)'.
 */
Menu_item
Base_BaseMenu_item5_callback(Menu_item item, Menu_generate op)
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
#ifdef XV_DEBUG
		fputs("swmtool: Base_BaseMenu_item5_callback: MENU_NOTIFY\n", stderr);
#endif /* XV_DEBUG */
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			Module *mod = GetCurrentModule();
			
			if (mod != (Module *)0)
				SetCurrentLevel((char *)0, mod);
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Event callback function for `BaseWin'.
 */
Notify_value
Base_BaseWin_event_callback(Xv_window win, Event *event, Notify_arg arg, Notify_event_type type)
{
	Base_BaseWin_objects *ip = (Base_BaseWin_objects *) xv_get(win, XV_KEY_DATA, INSTANCE);
	
#ifdef XV_DEBUG
	fprintf(stderr, "swmtool: Base_BaseWin_event_callback: event %d\n", event_id(event));
#endif /* XV_DEBUG */
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	if (event_action(event) == WIN_RESIZE)
	{
		BaseResize((Xv_opaque)ip);
	}
	
	/* gxv_end_connections */

	return notify_next_event_func(win, (Notify_event) event, arg, type);
}

/*
 * Notify callback function for `BaseMode'.
 */
void
Base_BaseWin_BaseMode_notify_callback(Panel_item item, int	 value, Event *event)
{
	Base_BaseWin_objects *ip = (Base_BaseWin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
#ifdef XV_DEBUG
	fprintf(stderr, "swmtool: Base_BaseWin_BaseMode_notify_callback: value: %u\n", value);
#endif /* XV_DEBUG */
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		if (get_mode() == MODE_REMOVE && value == 0)
			BrowseModules(MODE_INSTALL, VIEW_UNSPEC);
		else if (get_mode() == MODE_INSTALL && value == 1)
			BrowseModules(MODE_REMOVE, VIEW_UNSPEC);
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `BaseProps'.
 */
void
Base_BaseWin_BaseProps_notify_callback(Panel_item item, Event *event)
{
	Base_BaseWin_objects *ip = (Base_BaseWin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
#ifdef XV_DEBUG
	fputs("swmtool: Base_BaseWin_BaseProps_notify_callback\n", stderr);
#endif /* XV_DEBUG */
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		ShowProperties(PROPS_LAST, (caddr_t)0);
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `BaseDoit'.
 */
void
Base_BaseWin_BaseDoit_notify_callback(Panel_item item, Event *event)
{
	Base_BaseWin_objects *ip = (Base_BaseWin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
#ifdef XV_DEBUG
	fputs("swmtool: Base_BaseWin_BaseDoit_notify_callback\n", stderr);
#endif /* XV_DEBUG */
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		Apply((Xv_opaque)ip);
	}
	
	/* gxv_end_connections */

}

/*
 * Event callback function for `Levels'.
 */
Notify_value
Base_BaseWin_Levels_event_callback(Xv_window win, Event *event, Notify_arg arg, Notify_event_type type)
{
	Base_BaseWin_objects *ip = (Base_BaseWin_objects *) xv_get(xv_get(win, CANVAS_PAINT_CANVAS_WINDOW), XV_KEY_DATA, INSTANCE);
	
#ifdef XV_DEBUG
	fprintf(stderr, "swmtool: Base_BaseWin_Levels_event_callback: event %d\n", event_id(event));
#endif /* XV_DEBUG */
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		SelectLevel(win, event, arg, type);
	}
	
	/* gxv_end_connections */

	return notify_next_event_func(win, (Notify_event) event, arg, type);
}

/*
 * Repaint callback function for `Levels'.
 */
void
Base_BaseWin_Levels_repaint_callback(Canvas canvas, Xv_window paint_window, Display *display, Window xid, Xv_xrectlist *rects)
{
#ifdef XV_DEBUG
	fputs("swmtool: Base_BaseWin_Levels_repaint_callback\n", stderr);
#endif /* XV_DEBUG */
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		RepaintLevels(canvas, paint_window, display, xid, rects);
	}
	
	/* gxv_end_connections */

}

/*
 * Event callback function for `Mods'.
 */
Notify_value
Base_BaseWin_Mods_event_callback(Xv_window win, Event *event, Notify_arg arg, Notify_event_type type)
{
	Base_BaseWin_objects *ip = (Base_BaseWin_objects *) xv_get(xv_get(win, CANVAS_PAINT_CANVAS_WINDOW), XV_KEY_DATA, INSTANCE);
	
#ifdef XV_DEBUG
	fprintf(stderr, "swmtool: Base_BaseWin_Mods_event_callback: event %d\n", event_id(event));
#endif /* XV_DEBUG */
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		SelectModules(win, event, arg, type);
	}
	
	/* gxv_end_connections */

	return notify_next_event_func(win, (Notify_event) event, arg, type);
}

/*
 * Repaint callback function for `Mods'.
 */
void
Base_BaseWin_Mods_repaint_callback(Canvas canvas, Xv_window paint_window, Display *display, Window xid, Xv_xrectlist *rects)
{
#ifdef XV_DEBUG
	fputs("swmtool: Base_BaseWin_Mods_repaint_callback\n", stderr);
#endif /* XV_DEBUG */
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		RepaintModules(canvas, paint_window, display, xid, rects);
	}
	
	/* gxv_end_connections */

}

