/*
 * Copyright (c) 1991 Sun Microsystems, Inc.  All Rights Reserved. Sun
 * considers its source code as an unpublished, proprietary trade secret, and
 * it is available only under strict license provisions.  This copyright
 * notice is placed here only to protect Sun in the event the source is
 * deemed a published work.  Dissassembly, decompilation, or other means of
 * reducing the object code to human readable form is prohibited by the
 * license agreement under which this code is provided to the user or company
 * in possession of this copy.
 *
 * RESTRICTED RIGHTS LEGEND: Use, duplication, or disclosure by the Government
 * is subject to restrictions as set forth in subparagraph (c)(1)(ii) of the
 * Rights in Technical Data and Computer Software clause at DFARS 52.227-7013
 * and in similar clauses in the FAR and NASA FAR Supplement.
 */

#ifndef lint
#ident	"@(#)File_stubs.c 1.2 92/12/14"
#endif

/*
 * File_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `File.G'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include <group.h>
#include "swmtool.h"
#include "defs.h"
#include "ui.h"


/*
 * Notify callback function for `FileName'.
 */
Panel_setting
File_FileWin_FileName_notify_callback(Panel_item item, Event *event)
{
	File_FileWin_objects *ip = (File_FileWin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
#ifdef XV_DEBUG
	fprintf(stderr, "swmtool: File_FileWin_FileName_notify_callback: value: %s\n", value);
#endif /* XV_DEBUG */
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		ConfigFile(CONFIG_SAVE);
	}
	
	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `FileDoit'.
 */
void
File_FileWin_FileDoit_notify_callback(Panel_item item, Event *event)
{
	File_FileWin_objects *ip = (File_FileWin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
#ifdef XV_DEBUG
	fputs("swmtool: File_FileWin_FileDoit_notify_callback\n", stderr);
#endif /* XV_DEBUG */
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		ConfigFile((CF_mode)xv_get(item, PANEL_CLIENT_DATA));
	}
	
	/* gxv_end_connections */

}

