/*
 * Copyright (c) 1991 Sun Microsystems, Inc.  All Rights Reserved. Sun
 * considers its source code as an unpublished, proprietary trade secret, and
 * it is available only under strict license provisions.  This copyright
 * notice is placed here only to protect Sun in the event the source is
 * deemed a published work.  Dissassembly, decompilation, or other means of
 * reducing the object code to human readable form is prohibited by the
 * license agreement under which this code is provided to the user or company
 * in possession of this copy.
 *
 * RESTRICTED RIGHTS LEGEND: Use, duplication, or disclosure by the Government
 * is subject to restrictions as set forth in subparagraph (c)(1)(ii) of the
 * Rights in Technical Data and Computer Software clause at DFARS 52.227-7013
 * and in similar clauses in the FAR and NASA FAR Supplement.
 */

#ifndef lint
#ident	"@(#)File_ui.h 1.1 92/10/08"
#endif

#ifndef	File_HEADER
#define	File_HEADER

/*
 * File_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `File.G'.
 * DO NOT EDIT BY HAND.
 */

#ifndef SVR4
EXTERN_FUNCTION( char *bindtextdomain, (const char *, const char *) );
EXTERN_FUNCTION( char *dgettext, (const char *, const char *) );
#else
#include <locale.h>
#endif

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	FileWin;
	Xv_opaque	FileCtrl;
	Xv_opaque	FileDir;
	Xv_opaque	FileName;
	Xv_opaque	FileGrp;
	Xv_opaque	FileDoit;
	Xv_opaque	FileButtons;
} File_FileWin_objects;

extern File_FileWin_objects	*File_FileWin_objects_initialize(File_FileWin_objects *, Xv_opaque);

extern Xv_opaque	File_FileWin_FileWin_create(File_FileWin_objects *, Xv_opaque);
extern Xv_opaque	File_FileWin_FileCtrl_create(File_FileWin_objects *, Xv_opaque);
extern Xv_opaque	File_FileWin_FileDir_create(File_FileWin_objects *, Xv_opaque);
extern Xv_opaque	File_FileWin_FileName_create(File_FileWin_objects *, Xv_opaque);
extern Xv_opaque	File_FileWin_FileGrp_create(File_FileWin_objects *, Xv_opaque);
extern Xv_opaque	File_FileWin_FileDoit_create(File_FileWin_objects *, Xv_opaque);
extern Xv_opaque	File_FileWin_FileButtons_create(File_FileWin_objects *, Xv_opaque);
#endif
