/*
 * Copyright (c) 1991 Sun Microsystems, Inc.  All Rights Reserved. Sun
 * considers its source code as an unpublished, proprietary trade secret, and
 * it is available only under strict license provisions.  This copyright
 * notice is placed here only to protect Sun in the event the source is
 * deemed a published work.  Dissassembly, decompilation, or other means of
 * reducing the object code to human readable form is prohibited by the
 * license agreement under which this code is provided to the user or company
 * in possession of this copy.
 *
 * RESTRICTED RIGHTS LEGEND: Use, duplication, or disclosure by the Government
 * is subject to restrictions as set forth in subparagraph (c)(1)(ii) of the
 * Rights in Technical Data and Computer Software clause at DFARS 52.227-7013
 * and in similar clauses in the FAR and NASA FAR Supplement.
 */

#ifndef lint
#ident	"@(#)Meter_stubs.c 1.3 92/12/14"
#endif

/*
 * Meter_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `Meter.G'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include <group.h>
#include "swmtool.h"


/*
 * Notify callback function for `MeterDismiss'.
 */
void
Meter_MeterWin_MeterDismiss_notify_callback(Panel_item item, Event *event)
{
	Meter_MeterWin_objects *ip = (Meter_MeterWin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
#ifdef XV_DEBUG
	fputs("swmtool: Meter_MeterWin_MeterDismiss_notify_callback\n", stderr);
#endif /* XV_DEBUG */
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	xv_set(Meter_MeterWin->MeterWin, FRAME_CMD_PUSHPIN_IN, FALSE, NULL);
	xv_set(Meter_MeterWin->MeterWin, XV_SHOW, FALSE, NULL);
	
	/* gxv_end_connections */

}

