/*
 * Copyright (c) 1991 Sun Microsystems, Inc.  All Rights Reserved. Sun
 * considers its source code as an unpublished, proprietary trade secret, and
 * it is available only under strict license provisions.  This copyright
 * notice is placed here only to protect Sun in the event the source is
 * deemed a published work.  Dissassembly, decompilation, or other means of
 * reducing the object code to human readable form is prohibited by the
 * license agreement under which this code is provided to the user or company
 * in possession of this copy.
 *
 * RESTRICTED RIGHTS LEGEND: Use, duplication, or disclosure by the Government
 * is subject to restrictions as set forth in subparagraph (c)(1)(ii) of the
 * Rights in Technical Data and Computer Software clause at DFARS 52.227-7013
 * and in similar clauses in the FAR and NASA FAR Supplement.
 */

#ifndef lint
#ident	"@(#)Pkg_ui.h 1.3 92/11/16"
#endif

#ifndef	Pkg_HEADER
#define	Pkg_HEADER

/*
 * Pkg_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `Pkg.G'.
 * DO NOT EDIT BY HAND.
 */

#ifndef SVR4
EXTERN_FUNCTION( char *bindtextdomain, (const char *, const char *) );
EXTERN_FUNCTION( char *dgettext, (const char *, const char *) );
#else
#include <locale.h>
#endif

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	ProdWin;
	Xv_opaque	ProdCtrl;
	Xv_opaque	ProdName;
	Xv_opaque	ProdLocList;
	Xv_opaque	ProdGrp;
	Xv_opaque	ProdApply;
	Xv_opaque	ProdReset;
	Xv_opaque	ProdButtons;
} Pkg_ProdWin_objects;

extern Pkg_ProdWin_objects	*Pkg_ProdWin_objects_initialize(Pkg_ProdWin_objects *, Xv_opaque);

extern Xv_opaque	Pkg_ProdWin_ProdWin_create(Pkg_ProdWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_ProdWin_ProdCtrl_create(Pkg_ProdWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_ProdWin_ProdName_create(Pkg_ProdWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_ProdWin_ProdLocList_create(Pkg_ProdWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_ProdWin_ProdGrp_create(Pkg_ProdWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_ProdWin_ProdApply_create(Pkg_ProdWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_ProdWin_ProdReset_create(Pkg_ProdWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_ProdWin_ProdButtons_create(Pkg_ProdWin_objects *, Xv_opaque);

typedef struct {
	Xv_opaque	PkgWin;
	Xv_opaque	PkgCtrl;
	Xv_opaque	PkgName;
	Xv_opaque	PkgProd;
	Xv_opaque	PkgAbbrev;
	Xv_opaque	PkgVend;
	Xv_opaque	PkgVers;
	Xv_opaque	PkgDesc;
	Xv_opaque	PkgArch;
	Xv_opaque	PkgStatus;
	Xv_opaque	PkgSize;
	Xv_opaque	PkgMbytes;
	Xv_opaque	PkgDummy;
	Xv_opaque	PkgRoot;
	Xv_opaque	PkgOpt;
	Xv_opaque	PkgExport;
	Xv_opaque	PkgUsr;
	Xv_opaque	PkgVar;
	Xv_opaque	PkgOpenwin;
	Xv_opaque	PkgFs;
	Xv_opaque	PkgBase;
	Xv_opaque	PkgGrp;
	Xv_opaque	PkgApply;
	Xv_opaque	PkgReset;
	Xv_opaque	PkgButtons;
} Pkg_PkgWin_objects;

extern Pkg_PkgWin_objects	*Pkg_PkgWin_objects_initialize(Pkg_PkgWin_objects *, Xv_opaque);

extern Xv_opaque	Pkg_PkgWin_PkgWin_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgCtrl_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgName_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgProd_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgAbbrev_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgVend_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgVers_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgDesc_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgArch_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgStatus_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgSize_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgMbytes_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgDummy_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgRoot_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgOpt_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgExport_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgUsr_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgVar_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgOpenwin_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgFs_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgBase_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgGrp_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgApply_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgReset_create(Pkg_PkgWin_objects *, Xv_opaque);
extern Xv_opaque	Pkg_PkgWin_PkgButtons_create(Pkg_PkgWin_objects *, Xv_opaque);
#endif
