/*
 * Copyright (c) 1991 Sun Microsystems, Inc.  All Rights Reserved. Sun
 * considers its source code as an unpublished, proprietary trade secret, and
 * it is available only under strict license provisions.  This copyright
 * notice is placed here only to protect Sun in the event the source is
 * deemed a published work.  Dissassembly, decompilation, or other means of
 * reducing the object code to human readable form is prohibited by the
 * license agreement under which this code is provided to the user or company
 * in possession of this copy.
 *
 * RESTRICTED RIGHTS LEGEND: Use, duplication, or disclosure by the Government
 * is subject to restrictions as set forth in subparagraph (c)(1)(ii) of the
 * Rights in Technical Data and Computer Software clause at DFARS 52.227-7013
 * and in similar clauses in the FAR and NASA FAR Supplement.
 */

#ifndef lint
#ident	"@(#)Pkg_ui.c 1.10 93/04/08"
#endif

/*
 * Pkg_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `Pkg.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include <group.h>
#include "Pkg_ui.h"

/*
 * Initialize an instance of object `ProdWin'.
 */
Pkg_ProdWin_objects *
Pkg_ProdWin_objects_initialize(Pkg_ProdWin_objects *ip, Xv_opaque owner)
{
	if (!ip && !(ip = (Pkg_ProdWin_objects *) calloc(1, sizeof (Pkg_ProdWin_objects))))
		return (Pkg_ProdWin_objects *) NULL;
	if (!ip->ProdWin)
		ip->ProdWin = Pkg_ProdWin_ProdWin_create(ip, owner);
	if (!ip->ProdCtrl)
		ip->ProdCtrl = Pkg_ProdWin_ProdCtrl_create(ip, ip->ProdWin);
	if (!ip->ProdName)
		ip->ProdName = Pkg_ProdWin_ProdName_create(ip, ip->ProdCtrl);
	if (!ip->ProdLocList)
		ip->ProdLocList = Pkg_ProdWin_ProdLocList_create(ip, ip->ProdCtrl);
	if (!ip->ProdGrp)
		ip->ProdGrp = Pkg_ProdWin_ProdGrp_create(ip, ip->ProdCtrl);
	if (!ip->ProdApply)
		ip->ProdApply = Pkg_ProdWin_ProdApply_create(ip, ip->ProdCtrl);
	if (!ip->ProdReset)
		ip->ProdReset = Pkg_ProdWin_ProdReset_create(ip, ip->ProdCtrl);
	if (!ip->ProdButtons)
		ip->ProdButtons = Pkg_ProdWin_ProdButtons_create(ip, ip->ProdCtrl);
	window_fit(ip->ProdCtrl);
	
	window_fit(ip->ProdWin);
	
	xv_set(ip->ProdCtrl,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		NULL);
	return ip;
}

/*
 * Create object `ProdWin' in the specified instance.
 */
Xv_opaque
Pkg_ProdWin_ProdWin_create(Pkg_ProdWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 392,
		XV_HEIGHT, 326,
		XV_LABEL, dgettext("SUNW_INSTALL_SWM", "Software Manager:  Product Localizations"),
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, FALSE,
		FRAME_CMD_PUSHPIN_IN, TRUE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `ProdCtrl' in the specified instance.
 */
Xv_opaque
Pkg_ProdWin_ProdCtrl_create(Pkg_ProdWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `ProdName' in the specified instance.
 */
Xv_opaque
Pkg_ProdWin_ProdName_create(Pkg_ProdWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 30,
		XV_Y, 30,
		PANEL_VALUE_DISPLAY_LENGTH, 40,
		PANEL_VALUE_STORED_LENGTH, 1024,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Product Name:"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_UNDERLINED, FALSE,
		PANEL_READ_ONLY, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `ProdLocList' in the specified instance.
 */
Xv_opaque
Pkg_ProdWin_ProdLocList_create(Pkg_ProdWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_LIST,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 33,
		XV_Y, 65,
		PANEL_LIST_WIDTH, 200,
		PANEL_LIST_DISPLAY_ROWS, 10,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Localizations:"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, TRUE,
		PANEL_CHOOSE_ONE, FALSE,
		PANEL_CHOOSE_NONE, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `ProdGrp' in the specified instance.
 */
Xv_opaque
Pkg_ProdWin_ProdGrp_create(Pkg_ProdWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 30,
		XV_Y, 30,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->ProdName,
			ip->ProdLocList,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_LABELS,
		GROUP_VERTICAL_SPACING, 20,
		GROUP_ANCHOR_OBJ, ip->ProdCtrl,
		GROUP_ANCHOR_POINT, GROUP_NORTHWEST,
		GROUP_REFERENCE_POINT, GROUP_NORTHWEST,
		GROUP_HORIZONTAL_OFFSET, 30,
		GROUP_VERTICAL_OFFSET, 30,
		NULL);
	return obj;
}

/*
 * Create object `ProdApply' in the specified instance.
 */
Xv_opaque
Pkg_ProdWin_ProdApply_create(Pkg_ProdWin_objects *ip, Xv_opaque owner)
{
	extern void		Pkg_ProdWin_ProdApply_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 133,
		XV_Y, 295,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Apply"),
		PANEL_NOTIFY_PROC, Pkg_ProdWin_ProdApply_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `ProdReset' in the specified instance.
 */
Xv_opaque
Pkg_ProdWin_ProdReset_create(Pkg_ProdWin_objects *ip, Xv_opaque owner)
{
	extern void		Pkg_ProdWin_ProdReset_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 201,
		XV_Y, 295,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Reset"),
		PANEL_NOTIFY_PROC, Pkg_ProdWin_ProdReset_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `ProdButtons' in the specified instance.
 */
Xv_opaque
Pkg_ProdWin_ProdButtons_create(Pkg_ProdWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 133,
		XV_Y, 295,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->ProdApply,
			ip->ProdReset,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 15,
		GROUP_ANCHOR_OBJ, ip->ProdGrp,
		GROUP_ANCHOR_POINT, GROUP_SOUTH,
		GROUP_REFERENCE_POINT, GROUP_NORTH,
		GROUP_HORIZONTAL_OFFSET, 0,
		GROUP_VERTICAL_OFFSET, 30,
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `PkgWin'.
 */
Pkg_PkgWin_objects *
Pkg_PkgWin_objects_initialize(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	if (!ip && !(ip = (Pkg_PkgWin_objects *) calloc(1, sizeof (Pkg_PkgWin_objects))))
		return (Pkg_PkgWin_objects *) NULL;
	if (!ip->PkgWin)
		ip->PkgWin = Pkg_PkgWin_PkgWin_create(ip, owner);
	if (!ip->PkgCtrl)
		ip->PkgCtrl = Pkg_PkgWin_PkgCtrl_create(ip, ip->PkgWin);
	if (!ip->PkgName)
		ip->PkgName = Pkg_PkgWin_PkgName_create(ip, ip->PkgCtrl);
	if (!ip->PkgProd)
		ip->PkgProd = Pkg_PkgWin_PkgProd_create(ip, ip->PkgCtrl);
	if (!ip->PkgAbbrev)
		ip->PkgAbbrev = Pkg_PkgWin_PkgAbbrev_create(ip, ip->PkgCtrl);
	if (!ip->PkgVend)
		ip->PkgVend = Pkg_PkgWin_PkgVend_create(ip, ip->PkgCtrl);
	if (!ip->PkgVers)
		ip->PkgVers = Pkg_PkgWin_PkgVers_create(ip, ip->PkgCtrl);
	if (!ip->PkgDesc)
		ip->PkgDesc = Pkg_PkgWin_PkgDesc_create(ip, ip->PkgCtrl);
	if (!ip->PkgArch)
		ip->PkgArch = Pkg_PkgWin_PkgArch_create(ip, ip->PkgCtrl);
	if (!ip->PkgStatus)
		ip->PkgStatus = Pkg_PkgWin_PkgStatus_create(ip, ip->PkgCtrl);
	if (!ip->PkgSize)
		ip->PkgSize = Pkg_PkgWin_PkgSize_create(ip, ip->PkgCtrl);
	if (!ip->PkgMbytes)
		ip->PkgMbytes = Pkg_PkgWin_PkgMbytes_create(ip, ip->PkgCtrl);
	if (!ip->PkgDummy)
		ip->PkgDummy = Pkg_PkgWin_PkgDummy_create(ip, ip->PkgCtrl);
	if (!ip->PkgRoot)
		ip->PkgRoot = Pkg_PkgWin_PkgRoot_create(ip, ip->PkgCtrl);
	if (!ip->PkgOpt)
		ip->PkgOpt = Pkg_PkgWin_PkgOpt_create(ip, ip->PkgCtrl);
	if (!ip->PkgExport)
		ip->PkgExport = Pkg_PkgWin_PkgExport_create(ip, ip->PkgCtrl);
	if (!ip->PkgUsr)
		ip->PkgUsr = Pkg_PkgWin_PkgUsr_create(ip, ip->PkgCtrl);
	if (!ip->PkgVar)
		ip->PkgVar = Pkg_PkgWin_PkgVar_create(ip, ip->PkgCtrl);
	if (!ip->PkgOpenwin)
		ip->PkgOpenwin = Pkg_PkgWin_PkgOpenwin_create(ip, ip->PkgCtrl);
	if (!ip->PkgFs)
		ip->PkgFs = Pkg_PkgWin_PkgFs_create(ip, ip->PkgCtrl);
	if (!ip->PkgBase)
		ip->PkgBase = Pkg_PkgWin_PkgBase_create(ip, ip->PkgCtrl);
	if (!ip->PkgGrp)
		ip->PkgGrp = Pkg_PkgWin_PkgGrp_create(ip, ip->PkgCtrl);
	if (!ip->PkgApply)
		ip->PkgApply = Pkg_PkgWin_PkgApply_create(ip, ip->PkgCtrl);
	if (!ip->PkgReset)
		ip->PkgReset = Pkg_PkgWin_PkgReset_create(ip, ip->PkgCtrl);
	if (!ip->PkgButtons)
		ip->PkgButtons = Pkg_PkgWin_PkgButtons_create(ip, ip->PkgCtrl);
	window_fit(ip->PkgCtrl);
	
	window_fit(ip->PkgWin);
	
	xv_set(ip->PkgCtrl,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		NULL);
	return ip;
}

/*
 * Create object `PkgWin' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgWin_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 565,
		XV_HEIGHT, 486,
		XV_LABEL, dgettext("SUNW_INSTALL_SWM", "Software Manager:  Package Information"),
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, FALSE,
		FRAME_CMD_PUSHPIN_IN, TRUE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `PkgCtrl' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgCtrl_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:PkgCtrl",
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `PkgName' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgName_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 96,
		XV_Y, 30,
		PANEL_VALUE_DISPLAY_LENGTH, 30,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Name:"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_UNDERLINED, FALSE,
		PANEL_READ_ONLY, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `PkgProd' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgProd_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 84,
		XV_Y, 60,
		PANEL_VALUE_DISPLAY_LENGTH, 30,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Product:"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_UNDERLINED, FALSE,
		PANEL_READ_ONLY, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `PkgAbbrev' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgAbbrev_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 46,
		XV_Y, 90,
		PANEL_VALUE_DISPLAY_LENGTH, 30,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Abbreviation:"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_UNDERLINED, FALSE,
		PANEL_READ_ONLY, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `PkgVend' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgVend_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 87,
		XV_Y, 120,
		PANEL_VALUE_DISPLAY_LENGTH, 30,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Vendor:"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_UNDERLINED, FALSE,
		PANEL_READ_ONLY, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `PkgVers' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgVers_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 82,
		XV_Y, 150,
		PANEL_VALUE_DISPLAY_LENGTH, 30,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Version:"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_UNDERLINED, FALSE,
		PANEL_READ_ONLY, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `PkgDesc' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgDesc_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MULTILINE_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 55,
		XV_Y, 180,
		PANEL_VALUE_DISPLAY_LENGTH, 40,
		PANEL_VALUE_STORED_LENGTH, 1024,
		PANEL_DISPLAY_ROWS, 5,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Description:"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `PkgArch' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgArch_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 30,
		XV_Y, 266,
		PANEL_VALUE_DISPLAY_LENGTH, 30,
		PANEL_VALUE_STORED_LENGTH, 1024,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Supported Arch:"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_UNDERLINED, FALSE,
		PANEL_READ_ONLY, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `PkgStatus' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgStatus_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 92,
		XV_Y, 296,
		PANEL_VALUE_DISPLAY_LENGTH, 40,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Status:"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_UNDERLINED, FALSE,
		PANEL_READ_ONLY, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `PkgSize' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgSize_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 35,
		XV_Y, 327,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Estimated Size:"),
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `PkgMbytes' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgMbytes_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 190,
		XV_Y, 327,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "(Mbytes)"),
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `PkgDummy' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgDummy_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 388,
		XV_Y, 327,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Dummy"),
		PANEL_LABEL_BOLD, TRUE,
		XV_SHOW, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `PkgRoot' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgRoot_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 131,
		XV_Y, 351,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "/"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_UNDERLINED, FALSE,
		PANEL_READ_ONLY, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `PkgOpt' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgOpt_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 221,
		XV_Y, 351,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "/opt"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_UNDERLINED, FALSE,
		PANEL_READ_ONLY, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `PkgExport' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgExport_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 391,
		XV_Y, 351,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "/export"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_UNDERLINED, FALSE,
		PANEL_READ_ONLY, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `PkgUsr' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgUsr_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 108,
		XV_Y, 376,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "/usr"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_UNDERLINED, FALSE,
		PANEL_READ_ONLY, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `PkgVar' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgVar_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 221,
		XV_Y, 376,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "/var"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_UNDERLINED, FALSE,
		PANEL_READ_ONLY, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `PkgOpenwin' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgOpenwin_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 345,
		XV_Y, 376,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "/usr/openwin"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_UNDERLINED, FALSE,
		PANEL_READ_ONLY, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `PkgFs' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgFs_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 35,
		XV_Y, 326,
		GROUP_TYPE, GROUP_ROWCOLUMN,
		GROUP_MEMBERS,
			ip->PkgSize,
			ip->PkgMbytes,
			ip->PkgDummy,
			ip->PkgRoot,
			ip->PkgOpt,
			ip->PkgExport,
			ip->PkgUsr,
			ip->PkgVar,
			ip->PkgOpenwin,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_COLUMNS, 3,
		GROUP_COLUMN_ALIGNMENT, GROUP_LABELS,
		GROUP_HORIZONTAL_SPACING, -20,
		GROUP_VERTICAL_SPACING, 10,
		NULL);
	return obj;
}

/*
 * Create object `PkgBase' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgBase_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 35,
		XV_Y, 406,
		PANEL_VALUE_DISPLAY_LENGTH, 32,
		PANEL_VALUE_STORED_LENGTH, 1024,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Base Directory:"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `PkgGrp' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgGrp_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 30,
		XV_Y, 30,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->PkgName,
			ip->PkgProd,
			ip->PkgAbbrev,
			ip->PkgVend,
			ip->PkgVers,
			ip->PkgDesc,
			ip->PkgArch,
			ip->PkgStatus,
			ip->PkgFs,
			ip->PkgBase,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_LABELS,
		GROUP_VERTICAL_SPACING, 15,
		GROUP_ANCHOR_OBJ, ip->PkgCtrl,
		GROUP_ANCHOR_POINT, GROUP_NORTHWEST,
		GROUP_REFERENCE_POINT, GROUP_NORTHWEST,
		GROUP_HORIZONTAL_OFFSET, 30,
		GROUP_VERTICAL_OFFSET, 30,
		NULL);
	return obj;
}

/*
 * Create object `PkgApply' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgApply_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	extern void		Pkg_PkgWin_PkgApply_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 220,
		XV_Y, 451,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Apply"),
		PANEL_NOTIFY_PROC, Pkg_PkgWin_PkgApply_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `PkgReset' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgReset_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	extern void		Pkg_PkgWin_PkgReset_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 288,
		XV_Y, 451,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Reset"),
		PANEL_NOTIFY_PROC, Pkg_PkgWin_PkgReset_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `PkgButtons' in the specified instance.
 */
Xv_opaque
Pkg_PkgWin_PkgButtons_create(Pkg_PkgWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 220,
		XV_Y, 451,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->PkgApply,
			ip->PkgReset,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 15,
		GROUP_ANCHOR_OBJ, ip->PkgGrp,
		GROUP_ANCHOR_POINT, GROUP_SOUTH,
		GROUP_REFERENCE_POINT, GROUP_NORTH,
		GROUP_HORIZONTAL_OFFSET, 0,
		GROUP_VERTICAL_OFFSET, 30,
		NULL);
	return obj;
}

