/*
 * Copyright (c) 1991 Sun Microsystems, Inc.  All Rights Reserved. Sun
 * considers its source code as an unpublished, proprietary trade secret, and
 * it is available only under strict license provisions.  This copyright
 * notice is placed here only to protect Sun in the event the source is
 * deemed a published work.  Dissassembly, decompilation, or other means of
 * reducing the object code to human readable form is prohibited by the
 * license agreement under which this code is provided to the user or company
 * in possession of this copy.
 *
 * RESTRICTED RIGHTS LEGEND: Use, duplication, or disclosure by the Government
 * is subject to restrictions as set forth in subparagraph (c)(1)(ii) of the
 * Rights in Technical Data and Computer Software clause at DFARS 52.227-7013
 * and in similar clauses in the FAR and NASA FAR Supplement.
 */

#ifndef lint
#ident	"@(#)Props_ui.h 1.3 92/11/16"
#endif

#ifndef	Props_HEADER
#define	Props_HEADER

/*
 * Props_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `Props.G'.
 * DO NOT EDIT BY HAND.
 */

#ifndef SVR4
EXTERN_FUNCTION( char *bindtextdomain, (const char *, const char *) );
EXTERN_FUNCTION( char *dgettext, (const char *, const char *) );
#else
#include <locale.h>
#endif

extern Attr_attribute	INSTANCE;

extern Xv_opaque	Props_MailMenu_create(caddr_t, Xv_opaque);
extern Xv_opaque	Props_HostAddMenu_create(caddr_t, Xv_opaque);
extern Xv_opaque	Props_HostEditMenu_create(caddr_t, Xv_opaque);

typedef struct {
	Xv_opaque	PropsWin;
	Xv_opaque	PropsCtrl;
	Xv_opaque	PropsSet;
	Xv_opaque	PropsSetGrp;
	Xv_opaque	DispCtrl;
	Xv_opaque	DispIconic;
	Xv_opaque	DispName;
	Xv_opaque	DispCols;
	Xv_opaque	DispGrp;
	Xv_opaque	DispApply;
	Xv_opaque	DispReset;
	Xv_opaque	DispButtons;
	Xv_opaque	LoadCtrl;
	Xv_opaque	LoadType;
	Xv_opaque	LoadEject;
	Xv_opaque	LoadDev;
	Xv_opaque	LoadDevGrp;
	Xv_opaque	LoadDir;
	Xv_opaque	LoadText;
	Xv_opaque	LoadParams;
	Xv_opaque	LoadApply;
	Xv_opaque	LoadReset;
	Xv_opaque	LoadButtons;
	Xv_opaque	LoadMedia;
	Xv_opaque	ConfigCtrl;
	Xv_opaque	ConfigMailList;
	Xv_opaque	ConfigMailAdd;
	Xv_opaque	ConfigMailDelete;
	Xv_opaque	ConfigMailChange;
	Xv_opaque	ConfigMailButtons;
	Xv_opaque	ConfigMailListGrp;
	Xv_opaque	ConfigRecip;
	Xv_opaque	ConfigMailGrp;
	Xv_opaque	ConfigConflict;
	Xv_opaque	ConfigInstance;
	Xv_opaque	ConfigPartial;
	Xv_opaque	ConfigSetuid;
	Xv_opaque	ConfigAction;
	Xv_opaque	ConfigIdepend;
	Xv_opaque	ConfigRdepend;
	Xv_opaque	ConfigRunlevel;
	Xv_opaque	ConfigSpace;
	Xv_opaque	ConfigVerbose;
	Xv_opaque	ConfigInteract;
	Xv_opaque	ConfigParams;
	Xv_opaque	ConfigGrp;
	Xv_opaque	ConfigApply;
	Xv_opaque	ConfigReset;
	Xv_opaque	ConfigButtons;
	Xv_opaque	CatCtrl;
	Xv_opaque	CatList;
	Xv_opaque	CatListGroup;
	Xv_opaque	CatApply;
	Xv_opaque	CatReset;
	Xv_opaque	CatButtonGroup;
	Xv_opaque	HostCtrl;
	Xv_opaque	HostEdit;
	Xv_opaque	HostList;
	Xv_opaque	HostToggle;
	Xv_opaque	HostListGrp;
	Xv_opaque	HostGrp;
	Xv_opaque	HostName;
	Xv_opaque	HostPwdClear;
	Xv_opaque	HostPwd;
	Xv_opaque	HostPwdGrp;
	Xv_opaque	HostParmGrp;
	Xv_opaque	HostApply;
	Xv_opaque	HostReset;
	Xv_opaque	HostLowButtons;
} Props_PropsWin_objects;

extern Props_PropsWin_objects	*Props_PropsWin_objects_initialize(Props_PropsWin_objects *, Xv_opaque);

extern Xv_opaque	Props_PropsWin_PropsWin_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_PropsCtrl_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_PropsSet_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_PropsSetGrp_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_DispCtrl_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_DispIconic_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_DispName_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_DispCols_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_DispGrp_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_DispApply_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_DispReset_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_DispButtons_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_LoadCtrl_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_LoadType_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_LoadEject_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_LoadDev_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_LoadDevGrp_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_LoadDir_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_LoadText_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_LoadParams_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_LoadApply_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_LoadReset_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_LoadButtons_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_LoadMedia_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigCtrl_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigMailList_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigMailAdd_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigMailDelete_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigMailChange_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigMailButtons_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigMailListGrp_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigRecip_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigMailGrp_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigConflict_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigInstance_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigPartial_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigSetuid_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigAction_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigIdepend_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigRdepend_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigRunlevel_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigSpace_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigVerbose_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigInteract_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigParams_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigGrp_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigApply_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigReset_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_ConfigButtons_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_CatCtrl_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_CatList_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_CatListGroup_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_CatApply_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_CatReset_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_CatButtonGroup_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_HostCtrl_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_HostEdit_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_HostList_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_HostToggle_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_HostListGrp_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_HostGrp_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_HostName_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_HostPwdClear_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_HostPwd_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_HostPwdGrp_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_HostParmGrp_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_HostApply_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_HostReset_create(Props_PropsWin_objects *, Xv_opaque);
extern Xv_opaque	Props_PropsWin_HostLowButtons_create(Props_PropsWin_objects *, Xv_opaque);
#endif
