/*
 * Copyright (c) 1991 Sun Microsystems, Inc.  All Rights Reserved. Sun
 * considers its source code as an unpublished, proprietary trade secret, and
 * it is available only under strict license provisions.  This copyright
 * notice is placed here only to protect Sun in the event the source is
 * deemed a published work.  Dissassembly, decompilation, or other means of
 * reducing the object code to human readable form is prohibited by the
 * license agreement under which this code is provided to the user or company
 * in possession of this copy.
 *
 * RESTRICTED RIGHTS LEGEND: Use, duplication, or disclosure by the Government
 * is subject to restrictions as set forth in subparagraph (c)(1)(ii) of the
 * Rights in Technical Data and Computer Software clause at DFARS 52.227-7013
 * and in similar clauses in the FAR and NASA FAR Supplement.
 */

#ifndef lint
#ident	"@(#)Props_ui.c 1.8 93/10/13"
#endif

/*
 * Props_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `Props.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include <group.h>
#include "Props_ui.h"

/*
 * Create object `MailMenu' in the specified instance.
 */
Xv_opaque
Props_MailMenu_create(caddr_t ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(XV_NULL, MENU_COMMAND_MENU,
		XV_KEY_DATA, INSTANCE, ip,
		MENU_TITLE_ITEM, dgettext("SUNW_INSTALL_SWM", "Scrolling list"),
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, dgettext("SUNW_INSTALL_SWM", "Locate Choice"),
			NULL,
		MENU_DEFAULT, 2,
		NULL);
	return obj;
}

/*
 * Create object `HostAddMenu' in the specified instance.
 */
Xv_opaque
Props_HostAddMenu_create(caddr_t ip, Xv_opaque owner)
{
	extern Menu_item	Props_HostAddMenu_item0_callback(Menu_item, Menu_generate);
	extern Menu_item	Props_HostAddMenu_item1_callback(Menu_item, Menu_generate);
	extern Menu_item	Props_HostAddMenu_item2_callback(Menu_item, Menu_generate);
	extern Menu_item	Props_HostAddMenu_item3_callback(Menu_item, Menu_generate);
	Xv_opaque	obj;
	
	obj = xv_create(XV_NULL, MENU_COMMAND_MENU,
		XV_KEY_DATA, INSTANCE, ip,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, dgettext("SUNW_INSTALL_SWM", "Before"),
			MENU_GEN_PROC, Props_HostAddMenu_item0_callback,
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, dgettext("SUNW_INSTALL_SWM", "After"),
			MENU_GEN_PROC, Props_HostAddMenu_item1_callback,
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, dgettext("SUNW_INSTALL_SWM", "Top"),
			MENU_GEN_PROC, Props_HostAddMenu_item2_callback,
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, dgettext("SUNW_INSTALL_SWM", "Bottom"),
			MENU_GEN_PROC, Props_HostAddMenu_item3_callback,
			NULL,
		MENU_DEFAULT, 4,
		NULL);
	return obj;
}

/*
 * Create object `HostEditMenu' in the specified instance.
 */
Xv_opaque
Props_HostEditMenu_create(caddr_t ip, Xv_opaque owner)
{
	extern Menu_item	Props_HostEditMenu_item1_callback(Menu_item, Menu_generate);
	extern Menu_item	Props_HostEditMenu_item2_callback(Menu_item, Menu_generate);
	Xv_opaque	obj;
	
	obj = xv_create(XV_NULL, MENU_COMMAND_MENU,
		XV_KEY_DATA, INSTANCE, ip,
		MENU_TITLE_ITEM, dgettext("SUNW_INSTALL_SWM", "Edit"),
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, dgettext("SUNW_INSTALL_SWM", "Add Entry"),
			MENU_PULLRIGHT, Props_HostAddMenu_create(ip, owner),
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, dgettext("SUNW_INSTALL_SWM", "Modify Entry"),
			MENU_GEN_PROC, Props_HostEditMenu_item1_callback,
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, dgettext("SUNW_INSTALL_SWM", "Remove Entry"),
			MENU_GEN_PROC, Props_HostEditMenu_item2_callback,
			NULL,
		MENU_DEFAULT, 2,
		MENU_GEN_PIN_WINDOW, owner, dgettext("SUNW_INSTALL_SWM", "Edit"),
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `PropsWin'.
 */
Props_PropsWin_objects *
Props_PropsWin_objects_initialize(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	if (!ip && !(ip = (Props_PropsWin_objects *) calloc(1, sizeof (Props_PropsWin_objects))))
		return (Props_PropsWin_objects *) NULL;
	if (!ip->PropsWin)
		ip->PropsWin = Props_PropsWin_PropsWin_create(ip, owner);
	if (!ip->PropsCtrl)
		ip->PropsCtrl = Props_PropsWin_PropsCtrl_create(ip, ip->PropsWin);
	if (!ip->PropsSet)
		ip->PropsSet = Props_PropsWin_PropsSet_create(ip, ip->PropsCtrl);
	if (!ip->PropsSetGrp)
		ip->PropsSetGrp = Props_PropsWin_PropsSetGrp_create(ip, ip->PropsCtrl);
	window_fit(ip->PropsCtrl);
	
	if (!ip->DispCtrl)
		ip->DispCtrl = Props_PropsWin_DispCtrl_create(ip, ip->PropsWin);
	if (!ip->DispIconic)
		ip->DispIconic = Props_PropsWin_DispIconic_create(ip, ip->DispCtrl);
	if (!ip->DispName)
		ip->DispName = Props_PropsWin_DispName_create(ip, ip->DispCtrl);
	if (!ip->DispCols)
		ip->DispCols = Props_PropsWin_DispCols_create(ip, ip->DispCtrl);
	if (!ip->DispGrp)
		ip->DispGrp = Props_PropsWin_DispGrp_create(ip, ip->DispCtrl);
	if (!ip->DispApply)
		ip->DispApply = Props_PropsWin_DispApply_create(ip, ip->DispCtrl);
	if (!ip->DispReset)
		ip->DispReset = Props_PropsWin_DispReset_create(ip, ip->DispCtrl);
	if (!ip->DispButtons)
		ip->DispButtons = Props_PropsWin_DispButtons_create(ip, ip->DispCtrl);
	window_fit(ip->DispCtrl);
	
	if (!ip->LoadCtrl)
		ip->LoadCtrl = Props_PropsWin_LoadCtrl_create(ip, ip->PropsWin);
	if (!ip->LoadType)
		ip->LoadType = Props_PropsWin_LoadType_create(ip, ip->LoadCtrl);
	if (!ip->LoadEject)
		ip->LoadEject = Props_PropsWin_LoadEject_create(ip, ip->LoadCtrl);
	if (!ip->LoadDev)
		ip->LoadDev = Props_PropsWin_LoadDev_create(ip, ip->LoadCtrl);
	if (!ip->LoadDevGrp)
		ip->LoadDevGrp = Props_PropsWin_LoadDevGrp_create(ip, ip->LoadCtrl);
	if (!ip->LoadDir)
		ip->LoadDir = Props_PropsWin_LoadDir_create(ip, ip->LoadCtrl);
	if (!ip->LoadText)
		ip->LoadText = Props_PropsWin_LoadText_create(ip, ip->LoadCtrl);
	if (!ip->LoadParams)
		ip->LoadParams = Props_PropsWin_LoadParams_create(ip, ip->LoadCtrl);
	if (!ip->LoadApply)
		ip->LoadApply = Props_PropsWin_LoadApply_create(ip, ip->LoadCtrl);
	if (!ip->LoadReset)
		ip->LoadReset = Props_PropsWin_LoadReset_create(ip, ip->LoadCtrl);
	if (!ip->LoadButtons)
		ip->LoadButtons = Props_PropsWin_LoadButtons_create(ip, ip->LoadCtrl);
	if (!ip->LoadMedia)
		ip->LoadMedia = Props_PropsWin_LoadMedia_create(ip, ip->LoadCtrl);
	window_fit(ip->LoadCtrl);
	
	if (!ip->ConfigCtrl)
		ip->ConfigCtrl = Props_PropsWin_ConfigCtrl_create(ip, ip->PropsWin);
	if (!ip->ConfigMailList)
		ip->ConfigMailList = Props_PropsWin_ConfigMailList_create(ip, ip->ConfigCtrl);
	if (!ip->ConfigMailAdd)
		ip->ConfigMailAdd = Props_PropsWin_ConfigMailAdd_create(ip, ip->ConfigCtrl);
	if (!ip->ConfigMailDelete)
		ip->ConfigMailDelete = Props_PropsWin_ConfigMailDelete_create(ip, ip->ConfigCtrl);
	if (!ip->ConfigMailChange)
		ip->ConfigMailChange = Props_PropsWin_ConfigMailChange_create(ip, ip->ConfigCtrl);
	if (!ip->ConfigMailButtons)
		ip->ConfigMailButtons = Props_PropsWin_ConfigMailButtons_create(ip, ip->ConfigCtrl);
	if (!ip->ConfigMailListGrp)
		ip->ConfigMailListGrp = Props_PropsWin_ConfigMailListGrp_create(ip, ip->ConfigCtrl);
	if (!ip->ConfigRecip)
		ip->ConfigRecip = Props_PropsWin_ConfigRecip_create(ip, ip->ConfigCtrl);
	if (!ip->ConfigMailGrp)
		ip->ConfigMailGrp = Props_PropsWin_ConfigMailGrp_create(ip, ip->ConfigCtrl);
	if (!ip->ConfigConflict)
		ip->ConfigConflict = Props_PropsWin_ConfigConflict_create(ip, ip->ConfigCtrl);
	if (!ip->ConfigInstance)
		ip->ConfigInstance = Props_PropsWin_ConfigInstance_create(ip, ip->ConfigCtrl);
	if (!ip->ConfigPartial)
		ip->ConfigPartial = Props_PropsWin_ConfigPartial_create(ip, ip->ConfigCtrl);
	if (!ip->ConfigSetuid)
		ip->ConfigSetuid = Props_PropsWin_ConfigSetuid_create(ip, ip->ConfigCtrl);
	if (!ip->ConfigAction)
		ip->ConfigAction = Props_PropsWin_ConfigAction_create(ip, ip->ConfigCtrl);
	if (!ip->ConfigIdepend)
		ip->ConfigIdepend = Props_PropsWin_ConfigIdepend_create(ip, ip->ConfigCtrl);
	if (!ip->ConfigRdepend)
		ip->ConfigRdepend = Props_PropsWin_ConfigRdepend_create(ip, ip->ConfigCtrl);
	if (!ip->ConfigRunlevel)
		ip->ConfigRunlevel = Props_PropsWin_ConfigRunlevel_create(ip, ip->ConfigCtrl);
	if (!ip->ConfigSpace)
		ip->ConfigSpace = Props_PropsWin_ConfigSpace_create(ip, ip->ConfigCtrl);
	if (!ip->ConfigVerbose)
		ip->ConfigVerbose = Props_PropsWin_ConfigVerbose_create(ip, ip->ConfigCtrl);
	if (!ip->ConfigInteract)
		ip->ConfigInteract = Props_PropsWin_ConfigInteract_create(ip, ip->ConfigCtrl);
	if (!ip->ConfigParams)
		ip->ConfigParams = Props_PropsWin_ConfigParams_create(ip, ip->ConfigCtrl);
	if (!ip->ConfigGrp)
		ip->ConfigGrp = Props_PropsWin_ConfigGrp_create(ip, ip->ConfigCtrl);
	if (!ip->ConfigApply)
		ip->ConfigApply = Props_PropsWin_ConfigApply_create(ip, ip->ConfigCtrl);
	if (!ip->ConfigReset)
		ip->ConfigReset = Props_PropsWin_ConfigReset_create(ip, ip->ConfigCtrl);
	if (!ip->ConfigButtons)
		ip->ConfigButtons = Props_PropsWin_ConfigButtons_create(ip, ip->ConfigCtrl);
	window_fit(ip->ConfigCtrl);
	
	if (!ip->CatCtrl)
		ip->CatCtrl = Props_PropsWin_CatCtrl_create(ip, ip->PropsWin);
	if (!ip->CatList)
		ip->CatList = Props_PropsWin_CatList_create(ip, ip->CatCtrl);
	if (!ip->CatListGroup)
		ip->CatListGroup = Props_PropsWin_CatListGroup_create(ip, ip->CatCtrl);
	if (!ip->CatApply)
		ip->CatApply = Props_PropsWin_CatApply_create(ip, ip->CatCtrl);
	if (!ip->CatReset)
		ip->CatReset = Props_PropsWin_CatReset_create(ip, ip->CatCtrl);
	if (!ip->CatButtonGroup)
		ip->CatButtonGroup = Props_PropsWin_CatButtonGroup_create(ip, ip->CatCtrl);
	window_fit(ip->CatCtrl);
	
	if (!ip->HostCtrl)
		ip->HostCtrl = Props_PropsWin_HostCtrl_create(ip, ip->PropsWin);
	if (!ip->HostEdit)
		ip->HostEdit = Props_PropsWin_HostEdit_create(ip, ip->HostCtrl);
	if (!ip->HostList)
		ip->HostList = Props_PropsWin_HostList_create(ip, ip->HostCtrl);
	if (!ip->HostToggle)
		ip->HostToggle = Props_PropsWin_HostToggle_create(ip, ip->HostCtrl);
	if (!ip->HostListGrp)
		ip->HostListGrp = Props_PropsWin_HostListGrp_create(ip, ip->HostCtrl);
	if (!ip->HostGrp)
		ip->HostGrp = Props_PropsWin_HostGrp_create(ip, ip->HostCtrl);
	if (!ip->HostName)
		ip->HostName = Props_PropsWin_HostName_create(ip, ip->HostCtrl);
	if (!ip->HostPwdClear)
		ip->HostPwdClear = Props_PropsWin_HostPwdClear_create(ip, ip->HostCtrl);
	if (!ip->HostPwd)
		ip->HostPwd = Props_PropsWin_HostPwd_create(ip, ip->HostCtrl);
	if (!ip->HostPwdGrp)
		ip->HostPwdGrp = Props_PropsWin_HostPwdGrp_create(ip, ip->HostCtrl);
	if (!ip->HostParmGrp)
		ip->HostParmGrp = Props_PropsWin_HostParmGrp_create(ip, ip->HostCtrl);
	if (!ip->HostApply)
		ip->HostApply = Props_PropsWin_HostApply_create(ip, ip->HostCtrl);
	if (!ip->HostReset)
		ip->HostReset = Props_PropsWin_HostReset_create(ip, ip->HostCtrl);
	if (!ip->HostLowButtons)
		ip->HostLowButtons = Props_PropsWin_HostLowButtons_create(ip, ip->HostCtrl);
	window_fit(ip->HostCtrl);
	
	window_fit(ip->PropsWin);
	
	xv_set(ip->PropsCtrl, XV_WIDTH, WIN_EXTEND_TO_EDGE, NULL);
	xv_set(ip->DispCtrl,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		NULL);
	xv_set(ip->LoadCtrl,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		NULL);
	xv_set(ip->ConfigCtrl,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		NULL);
	xv_set(ip->CatCtrl,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		NULL);
	xv_set(ip->HostCtrl,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		NULL);
	return ip;
}

/*
 * Create object `PropsWin' in the specified instance.
 */
Xv_opaque
Props_PropsWin_PropsWin_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 453,
		XV_HEIGHT, 546,
		XV_LABEL, dgettext("SUNW_INSTALL_SWM", "Software Manager:  Properties"),
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		FRAME_CMD_PUSHPIN_IN, TRUE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `PropsCtrl' in the specified instance.
 */
Xv_opaque
Props_PropsWin_PropsCtrl_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:PropsCtrl",
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, 46,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `PropsSet' in the specified instance.
 */
Xv_opaque
Props_PropsWin_PropsSet_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	extern void		Props_PropsWin_PropsSet_notify_callback(Panel_item, int, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:PropsSet",
		XV_X, 30,
		XV_Y, 10,
		PANEL_CHOICE_NCOLS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Category:"),
		PANEL_NOTIFY_PROC, Props_PropsWin_PropsSet_notify_callback,
		PANEL_CHOICE_STRINGS,
			dgettext("SUNW_INSTALL_SWM", "Source Media"),
			dgettext("SUNW_INSTALL_SWM", "Package Administration"),
			dgettext("SUNW_INSTALL_SWM", "Current Product Category"),
			dgettext("SUNW_INSTALL_SWM", "Browser Display"),
			dgettext("SUNW_INSTALL_SWM", "Remote Hosts"),
			NULL,
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `PropsSetGrp' in the specified instance.
 */
Xv_opaque
Props_PropsWin_PropsSetGrp_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 30,
		XV_Y, 10,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->PropsSet,
			NULL,
		GROUP_ANCHOR_OBJ, ip->PropsCtrl,
		GROUP_ANCHOR_POINT, GROUP_NORTHWEST,
		GROUP_REFERENCE_POINT, GROUP_NORTHWEST,
		GROUP_HORIZONTAL_OFFSET, 30,
		GROUP_VERTICAL_OFFSET, 10,
		NULL);
	return obj;
}

/*
 * Create object `DispCtrl' in the specified instance.
 */
Xv_opaque
Props_PropsWin_DispCtrl_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:DispCtrl",
		XV_X, 0,
		XV_Y, (int)xv_get(ip->PropsCtrl, XV_Y) +
		      (int)xv_get(ip->PropsCtrl, XV_HEIGHT),
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		XV_SHOW, FALSE,
		WIN_BORDER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `DispIconic' in the specified instance.
 */
Xv_opaque
Props_PropsWin_DispIconic_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:DispIconic",
		XV_X, 64,
		XV_Y, 20,
		PANEL_CHOICE_NCOLS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Display Format:"),
		PANEL_CHOICE_STRINGS,
			dgettext("SUNW_INSTALL_SWM", "Automatic"),
			dgettext("SUNW_INSTALL_SWM", "Iconic"),
			dgettext("SUNW_INSTALL_SWM", "Textual"),
			NULL,
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `DispName' in the specified instance.
 */
Xv_opaque
Props_PropsWin_DispName_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:DispName",
		XV_X, 78,
		XV_Y, 48,
		PANEL_CHOICE_NCOLS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Name Length:"),
		PANEL_CHOICE_STRINGS,
			dgettext("SUNW_INSTALL_SWM", "Long"),
			dgettext("SUNW_INSTALL_SWM", "Short"),
			NULL,
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `DispCols' in the specified instance.
 */
Xv_opaque
Props_PropsWin_DispCols_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:DispCols",
		XV_X, 30,
		XV_Y, 76,
		PANEL_CHOICE_NCOLS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Number of Columns:"),
		PANEL_CHOICE_STRINGS,
			dgettext("SUNW_INSTALL_SWM", "1"),
			dgettext("SUNW_INSTALL_SWM", "2"),
			dgettext("SUNW_INSTALL_SWM", "3"),
			NULL,
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `DispGrp' in the specified instance.
 */
Xv_opaque
Props_PropsWin_DispGrp_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 30,
		XV_Y, 20,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->DispIconic,
			ip->DispName,
			ip->DispCols,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_LABELS,
		GROUP_VERTICAL_SPACING, 5,
		GROUP_ANCHOR_OBJ, ip->DispCtrl,
		GROUP_ANCHOR_POINT, GROUP_NORTHWEST,
		GROUP_REFERENCE_POINT, GROUP_NORTHWEST,
		GROUP_HORIZONTAL_OFFSET, 30,
		GROUP_VERTICAL_OFFSET, 20,
		NULL);
	return obj;
}

/*
 * Create object `DispApply' in the specified instance.
 */
Xv_opaque
Props_PropsWin_DispApply_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	extern void		Props_PropsWin_DispApply_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:DispApply",
		XV_X, 96,
		XV_Y, 129,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Apply"),
		PANEL_NOTIFY_PROC, Props_PropsWin_DispApply_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `DispReset' in the specified instance.
 */
Xv_opaque
Props_PropsWin_DispReset_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	extern void		Props_PropsWin_DispReset_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:DispReset",
		XV_X, 159,
		XV_Y, 129,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Reset"),
		PANEL_NOTIFY_PROC, Props_PropsWin_DispReset_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `DispButtons' in the specified instance.
 */
Xv_opaque
Props_PropsWin_DispButtons_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 96,
		XV_Y, 129,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->DispApply,
			ip->DispReset,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 10,
		GROUP_ANCHOR_OBJ, ip->DispGrp,
		GROUP_ANCHOR_POINT, GROUP_SOUTH,
		GROUP_REFERENCE_POINT, GROUP_NORTH,
		GROUP_HORIZONTAL_OFFSET, 0,
		GROUP_VERTICAL_OFFSET, 30,
		NULL);
	return obj;
}

/*
 * Create object `LoadCtrl' in the specified instance.
 */
Xv_opaque
Props_PropsWin_LoadCtrl_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:LoadCtrl",
		XV_X, 0,
		XV_Y, (int)xv_get(ip->PropsCtrl, XV_Y) +
		      (int)xv_get(ip->PropsCtrl, XV_HEIGHT),
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `LoadType' in the specified instance.
 */
Xv_opaque
Props_PropsWin_LoadType_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	extern void		Props_PropsWin_LoadType_notify_callback(Panel_item, int, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:LoadType",
		XV_X, 86,
		XV_Y, 30,
		PANEL_CHOICE_NCOLS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Media Type:"),
		PANEL_NOTIFY_PROC, Props_PropsWin_LoadType_notify_callback,
		PANEL_CHOICE_STRINGS,
			dgettext("SUNW_INSTALL_SWM", "Local CD-ROM"),
			dgettext("SUNW_INSTALL_SWM", "Mounted Directory"),
			NULL,
		PANEL_DEFAULT_VALUE, 0,
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `LoadEject' in the specified instance.
 */
Xv_opaque
Props_PropsWin_LoadEject_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	extern void		Props_PropsWin_LoadEject_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:LoadEject",
		XV_X, 346,
		XV_Y, 83,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Eject"),
		PANEL_NOTIFY_PROC, Props_PropsWin_LoadEject_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `LoadDev' in the specified instance.
 */
Xv_opaque
Props_PropsWin_LoadDev_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:LoadDev",
		XV_X, 76,
		XV_Y, 85,
		PANEL_VALUE_DISPLAY_LENGTH, 20,
		PANEL_VALUE_STORED_LENGTH, 1024,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Device Name:"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
#ifdef i386
		PANEL_VALUE, dgettext("SUNW_INSTALL_SWM", "/dev/dsk/c0t6d0p0"),
#else
		PANEL_VALUE, dgettext("SUNW_INSTALL_SWM", "/dev/dsk/c0t6d0s0"),
#endif
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `LoadDevGrp' in the specified instance.
 */
Xv_opaque
Props_PropsWin_LoadDevGrp_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 76,
		XV_Y, 83,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->LoadDev,
			ip->LoadEject,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 10,
		NULL);
	return obj;
}

/*
 * Create object `LoadDir' in the specified instance.
 */
Xv_opaque
Props_PropsWin_LoadDir_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	extern Panel_setting	Props_PropsWin_LoadDir_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:LoadDir",
		XV_X, 59,
		XV_Y, 117,
		PANEL_VALUE_DISPLAY_LENGTH, 20,
		PANEL_VALUE_STORED_LENGTH, 1024,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Directory Name:"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE, dgettext("SUNW_INSTALL_SWM", "/cdrom"),
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, Props_PropsWin_LoadDir_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `LoadText' in the specified instance.
 */
Xv_opaque
Props_PropsWin_LoadText_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 59,
		XV_Y, 83,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->LoadDevGrp,
			ip->LoadDir,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_LABELS,
		GROUP_VERTICAL_SPACING, 15,
		NULL);
	return obj;
}

/*
 * Create object `LoadParams' in the specified instance.
 */
Xv_opaque
Props_PropsWin_LoadParams_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 59,
		XV_Y, 30,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->LoadType,
			ip->LoadText,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_LABELS,
		GROUP_VERTICAL_SPACING, 20,
		NULL);
	return obj;
}

/*
 * Create object `LoadApply' in the specified instance.
 */
Xv_opaque
Props_PropsWin_LoadApply_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	extern void		Props_PropsWin_LoadApply_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:LoadApply",
		XV_X, 165,
		XV_Y, 367,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Apply"),
		PANEL_NOTIFY_PROC, Props_PropsWin_LoadApply_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `LoadReset' in the specified instance.
 */
Xv_opaque
Props_PropsWin_LoadReset_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	extern void		Props_PropsWin_LoadReset_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 200,
		XV_Y, 367,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Reset"),
		PANEL_NOTIFY_PROC, Props_PropsWin_LoadReset_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `LoadButtons' in the specified instance.
 */
Xv_opaque
Props_PropsWin_LoadButtons_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 165,
		XV_Y, 367,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->LoadApply,
			ip->LoadReset,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 15,
		NULL);
	return obj;
}

/*
 * Create object `LoadMedia' in the specified instance.
 */
Xv_opaque
Props_PropsWin_LoadMedia_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 59,
		XV_Y, 30,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->LoadParams,
			ip->LoadButtons,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_VERTICAL_CENTERS,
		GROUP_VERTICAL_SPACING, 30,
		GROUP_ANCHOR_OBJ, ip->LoadCtrl,
		GROUP_ANCHOR_POINT, GROUP_NORTHWEST,
		GROUP_REFERENCE_POINT, GROUP_NORTHWEST,
		GROUP_HORIZONTAL_OFFSET, 30,
		GROUP_VERTICAL_OFFSET, 30,
		NULL);
	return obj;
}

/*
 * Create object `ConfigCtrl' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigCtrl_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:ConfigCtrl",
		XV_X, 0,
		XV_Y, (int)xv_get(ip->PropsCtrl, XV_Y) +
		      (int)xv_get(ip->PropsCtrl, XV_HEIGHT),
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		XV_SHOW, FALSE,
		WIN_BORDER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `ConfigMailList' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigMailList_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	extern int		Props_PropsWin_ConfigMailList_notify_callback(Panel_item, char *, Xv_opaque, Panel_list_op, Event *, int);
	extern Xv_opaque	Props_MailMenu_create(caddr_t, Xv_opaque);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_LIST,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:ConfigMailList",
		XV_X, 31,
		XV_Y, 20,
		PANEL_LIST_WIDTH, 250,
		PANEL_LIST_DISPLAY_ROWS, 3,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Mail Recipients:"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, TRUE,
		PANEL_CHOOSE_ONE, TRUE,
		PANEL_CHOOSE_NONE, TRUE,
		PANEL_ITEM_MENU, Props_MailMenu_create((caddr_t) ip, ip->PropsWin),
		PANEL_NOTIFY_PROC, Props_PropsWin_ConfigMailList_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `ConfigMailAdd' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigMailAdd_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	extern void		Props_PropsWin_ConfigMailAdd_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:ConfigMailAdd",
		XV_X, 133,
		XV_Y, 104,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Add"),
		PANEL_NOTIFY_PROC, Props_PropsWin_ConfigMailAdd_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `ConfigMailDelete' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigMailDelete_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	extern void		Props_PropsWin_ConfigMailDelete_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:ConfigMailDelete",
		XV_X, 185,
		XV_Y, 104,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Delete"),
		PANEL_NOTIFY_PROC, Props_PropsWin_ConfigMailDelete_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `ConfigMailChange' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigMailChange_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	extern void		Props_PropsWin_ConfigMailChange_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:ConfigMailChange",
		XV_X, 252,
		XV_Y, 104,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Change"),
		PANEL_NOTIFY_PROC, Props_PropsWin_ConfigMailChange_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `ConfigMailButtons' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigMailButtons_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 133,
		XV_Y, 104,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->ConfigMailAdd,
			ip->ConfigMailDelete,
			ip->ConfigMailChange,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 10,
		NULL);
	return obj;
}

/*
 * Create object `ConfigMailListGrp' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigMailListGrp_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 31,
		XV_Y, 20,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->ConfigMailList,
			ip->ConfigMailButtons,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_VERTICAL_CENTERS,
		GROUP_VERTICAL_SPACING, 10,
		NULL);
	return obj;
}

/*
 * Create object `ConfigRecip' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigRecip_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:ConfigRecip",
		XV_X, 30,
		XV_Y, 133,
		PANEL_VALUE_DISPLAY_LENGTH, 30,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Recipient Name:"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `ConfigMailGrp' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigMailGrp_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 30,
		XV_Y, 20,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->ConfigMailListGrp,
			ip->ConfigRecip,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_LABELS,
		GROUP_VERTICAL_SPACING, 10,
		NULL);
	return obj;
}

/*
 * Create object `ConfigConflict' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigConflict_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:ConfigConflict",
		XV_X, 185,
		XV_Y, 163,
		PANEL_CHOICE_NCOLS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Existing Files:"),
		PANEL_CHOICE_STRINGS,
			dgettext("SUNW_INSTALL_SWM", "Ask"),
			dgettext("SUNW_INSTALL_SWM", "Overwrite"),
			dgettext("SUNW_INSTALL_SWM", "Skip"),
			dgettext("SUNW_INSTALL_SWM", "Abort"),
			NULL,
		PANEL_DEFAULT_VALUE, 0,
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `ConfigInstance' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigInstance_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:ConfigInstance",
		XV_X, 155,
		XV_Y, 191,
		PANEL_CHOICE_NCOLS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Existing Packages:"),
		PANEL_CHOICE_STRINGS,
			dgettext("SUNW_INSTALL_SWM", "Ask"),
			dgettext("SUNW_INSTALL_SWM", "Overwrite"),
			dgettext("SUNW_INSTALL_SWM", "Install Unique"),
			dgettext("SUNW_INSTALL_SWM", "Abort"),
			NULL,
		PANEL_DEFAULT_VALUE, 0,
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `ConfigPartial' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigPartial_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:ConfigPartial",
		XV_X, 89,
		XV_Y, 219,
		PANEL_CHOICE_NCOLS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Existing Partial Installation:"),
		PANEL_CHOICE_STRINGS,
			dgettext("SUNW_INSTALL_SWM", "Ask"),
			dgettext("SUNW_INSTALL_SWM", "Ignore"),
			dgettext("SUNW_INSTALL_SWM", "Abort"),
			NULL,
		PANEL_DEFAULT_VALUE, 0,
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `ConfigSetuid' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigSetuid_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:ConfigSetuid",
		XV_X, 99,
		XV_Y, 247,
		PANEL_CHOICE_NCOLS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Install Setuid/Setgid Files:"),
		PANEL_CHOICE_STRINGS,
			dgettext("SUNW_INSTALL_SWM", "Ask"),
			dgettext("SUNW_INSTALL_SWM", "Yes"),
			dgettext("SUNW_INSTALL_SWM", "No"),
			dgettext("SUNW_INSTALL_SWM", "Abort"),
			NULL,
		PANEL_DEFAULT_VALUE, 0,
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `ConfigAction' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigAction_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:ConfigAction",
		XV_X, 102,
		XV_Y, 275,
		PANEL_CHOICE_NCOLS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Run Setuid/Setgid Scripts:"),
		PANEL_CHOICE_STRINGS,
			dgettext("SUNW_INSTALL_SWM", "Ask"),
			dgettext("SUNW_INSTALL_SWM", "Yes"),
			dgettext("SUNW_INSTALL_SWM", "Abort"),
			NULL,
		PANEL_DEFAULT_VALUE, 0,
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `ConfigIdepend' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigIdepend_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:ConfigIdepend",
		XV_X, 40,
		XV_Y, 303,
		PANEL_CHOICE_NCOLS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Installation Dependencies Not Met:"),
		PANEL_CHOICE_STRINGS,
			dgettext("SUNW_INSTALL_SWM", "Ask"),
			dgettext("SUNW_INSTALL_SWM", "Ignore"),
			dgettext("SUNW_INSTALL_SWM", "Abort"),
			NULL,
		PANEL_DEFAULT_VALUE, 0,
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `ConfigRdepend' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigRdepend_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:ConfigRdepend",
		XV_X, 61,
		XV_Y, 331,
		PANEL_CHOICE_NCOLS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Removal Dependencies Not Met:"),
		PANEL_CHOICE_STRINGS,
			dgettext("SUNW_INSTALL_SWM", "Ask"),
			dgettext("SUNW_INSTALL_SWM", "Ignore"),
			dgettext("SUNW_INSTALL_SWM", "Abort"),
			NULL,
		PANEL_DEFAULT_VALUE, 0,
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `ConfigRunlevel' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigRunlevel_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:ConfigRunlevel",
		XV_X, 144,
		XV_Y, 359,
		PANEL_CHOICE_NCOLS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Incorrect Run Level:"),
		PANEL_CHOICE_STRINGS,
			dgettext("SUNW_INSTALL_SWM", "Ask"),
			dgettext("SUNW_INSTALL_SWM", "Ignore"),
			dgettext("SUNW_INSTALL_SWM", "Abort"),
			NULL,
		PANEL_DEFAULT_VALUE, 0,
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `ConfigSpace' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigSpace_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:ConfigSpace",
		XV_X, 151,
		XV_Y, 387,
		PANEL_CHOICE_NCOLS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Insufficient Space:"),
		PANEL_CHOICE_STRINGS,
			dgettext("SUNW_INSTALL_SWM", "Ask"),
			dgettext("SUNW_INSTALL_SWM", "Ignore"),
			dgettext("SUNW_INSTALL_SWM", "Abort"),
			NULL,
		PANEL_DEFAULT_VALUE, 0,
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `ConfigVerbose' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigVerbose_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:ConfigVerbose",
		XV_X, 162,
		XV_Y, 415,
		PANEL_CHOICE_NCOLS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Show Copyrights:"),
		PANEL_CHOICE_STRINGS,
			dgettext("SUNW_INSTALL_SWM", "Yes"),
			dgettext("SUNW_INSTALL_SWM", "No"),
			NULL,
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `ConfigInteract' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigInteract_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:ConfigInteract",
		XV_X, 80,
		XV_Y, 443,
		PANEL_CHOICE_NCOLS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Install/Remove Interactively:"),
		PANEL_CHOICE_STRINGS,
			dgettext("SUNW_INSTALL_SWM", "Yes"),
			dgettext("SUNW_INSTALL_SWM", "No"),
			NULL,
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `ConfigParams' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigParams_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 40,
		XV_Y, 163,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->ConfigConflict,
			ip->ConfigInstance,
			ip->ConfigPartial,
			ip->ConfigSetuid,
			ip->ConfigAction,
			ip->ConfigIdepend,
			ip->ConfigRdepend,
			ip->ConfigRunlevel,
			ip->ConfigSpace,
			ip->ConfigVerbose,
			ip->ConfigInteract,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_LABELS,
		GROUP_VERTICAL_SPACING, 5,
		NULL);
	return obj;
}

/*
 * Create object `ConfigGrp' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigGrp_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 30,
		XV_Y, 20,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->ConfigMailGrp,
			ip->ConfigParams,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_VERTICAL_CENTERS,
		GROUP_VERTICAL_SPACING, 15,
		GROUP_ANCHOR_OBJ, ip->ConfigCtrl,
		GROUP_ANCHOR_POINT, GROUP_NORTHWEST,
		GROUP_REFERENCE_POINT, GROUP_NORTHWEST,
		GROUP_HORIZONTAL_OFFSET, 30,
		GROUP_VERTICAL_OFFSET, 20,
		NULL);
	return obj;
}

/*
 * Create object `ConfigApply' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigApply_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	extern void		Props_PropsWin_ConfigApply_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:ConfigApply",
		XV_X, 167,
		XV_Y, 496,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Apply"),
		PANEL_NOTIFY_PROC, Props_PropsWin_ConfigApply_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `ConfigReset' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigReset_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	extern void		Props_PropsWin_ConfigReset_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:ConfigReset",
		XV_X, 200,
		XV_Y, 496,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Reset"),
		PANEL_NOTIFY_PROC, Props_PropsWin_ConfigReset_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `ConfigButtons' in the specified instance.
 */
Xv_opaque
Props_PropsWin_ConfigButtons_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 167,
		XV_Y, 496,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->ConfigApply,
			ip->ConfigReset,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 10,
		GROUP_ANCHOR_OBJ, ip->ConfigGrp,
		GROUP_ANCHOR_POINT, GROUP_SOUTH,
		GROUP_REFERENCE_POINT, GROUP_NORTH,
		GROUP_HORIZONTAL_OFFSET, 0,
		GROUP_VERTICAL_OFFSET, 30,
		NULL);
	return obj;
}

/*
 * Create object `CatCtrl' in the specified instance.
 */
Xv_opaque
Props_PropsWin_CatCtrl_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:CatCtrl",
		XV_X, 0,
		XV_Y, (int)xv_get(ip->PropsCtrl, XV_Y) +
		      (int)xv_get(ip->PropsCtrl, XV_HEIGHT),
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		XV_SHOW, FALSE,
		WIN_BORDER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `CatList' in the specified instance.
 */
Xv_opaque
Props_PropsWin_CatList_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_LIST,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:CatList",
		XV_X, 30,
		XV_Y, 20,
		PANEL_LIST_WIDTH, 200,
		PANEL_LIST_DISPLAY_ROWS, 10,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Categories:"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, TRUE,
		PANEL_CHOOSE_ONE, TRUE,
		PANEL_CHOOSE_NONE, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `CatListGroup' in the specified instance.
 */
Xv_opaque
Props_PropsWin_CatListGroup_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 30,
		XV_Y, 20,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->CatList,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_VERTICAL_CENTERS,
		GROUP_VERTICAL_SPACING, 10,
		GROUP_ANCHOR_OBJ, ip->CatCtrl,
		GROUP_ANCHOR_POINT, GROUP_NORTHWEST,
		GROUP_REFERENCE_POINT, GROUP_NORTHWEST,
		GROUP_HORIZONTAL_OFFSET, 30,
		GROUP_VERTICAL_OFFSET, 20,
		NULL);
	return obj;
}

/*
 * Create object `CatApply' in the specified instance.
 */
Xv_opaque
Props_PropsWin_CatApply_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	extern void		Props_PropsWin_CatApply_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:CatApply",
		XV_X, 124,
		XV_Y, 250,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Apply"),
		PANEL_NOTIFY_PROC, Props_PropsWin_CatApply_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `CatReset' in the specified instance.
 */
Xv_opaque
Props_PropsWin_CatReset_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	extern void		Props_PropsWin_CatReset_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:CatReset",
		XV_X, 187,
		XV_Y, 250,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Reset"),
		PANEL_NOTIFY_PROC, Props_PropsWin_CatReset_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `CatButtonGroup' in the specified instance.
 */
Xv_opaque
Props_PropsWin_CatButtonGroup_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 100,
		XV_Y, 250,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->CatApply,
			ip->CatReset,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 10,
		GROUP_ANCHOR_OBJ, ip->CatListGroup,
		GROUP_ANCHOR_POINT, GROUP_SOUTH,
		GROUP_REFERENCE_POINT, GROUP_NORTH,
		GROUP_HORIZONTAL_OFFSET, 0,
		GROUP_VERTICAL_OFFSET, 30,
		NULL);
	return obj;
}

/*
 * Create object `HostCtrl' in the specified instance.
 */
Xv_opaque
Props_PropsWin_HostCtrl_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:HostCtrl",
		XV_X, 0,
		XV_Y, (int)xv_get(ip->PropsCtrl, XV_Y) +
		      (int)xv_get(ip->PropsCtrl, XV_HEIGHT),
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		XV_SHOW, FALSE,
		WIN_BORDER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `HostEdit' in the specified instance.
 */
Xv_opaque
Props_PropsWin_HostEdit_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	extern Xv_opaque	Props_HostEditMenu_create(caddr_t, Xv_opaque);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:HostEdit",
		XV_X, 102,
		XV_Y, 20,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Edit"),
		PANEL_ITEM_MENU, Props_HostEditMenu_create((caddr_t) ip, ip->PropsWin),
		NULL);
	return obj;
}

/*
 * Create object `HostList' in the specified instance.
 */
Xv_opaque
Props_PropsWin_HostList_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	extern int		Props_PropsWin_HostList_notify_callback(Panel_item, char *, Xv_opaque, Panel_list_op, Event *, int);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_LIST,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:HostList",
		XV_X, 30,
		XV_Y, 49,
		PANEL_LIST_WIDTH, 400,
		PANEL_LIST_DISPLAY_ROWS, 6,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Target Hosts:"),
		PANEL_LAYOUT, PANEL_VERTICAL,
		PANEL_READ_ONLY, TRUE,
		PANEL_CHOOSE_ONE, TRUE,
		PANEL_CHOOSE_NONE, FALSE,
		PANEL_NOTIFY_PROC, Props_PropsWin_HostList_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `HostToggle' in the specified instance.
 */
Xv_opaque
Props_PropsWin_HostToggle_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	extern void		Props_PropsWin_HostToggle_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:HostToggle",
		XV_X, 131,
		XV_Y, 222,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Toggle Selection"),
		PANEL_NOTIFY_PROC, Props_PropsWin_HostToggle_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `HostListGrp' in the specified instance.
 */
Xv_opaque
Props_PropsWin_HostListGrp_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 30,
		XV_Y, 49,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->HostList,
			ip->HostToggle,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_VERTICAL_CENTERS,
		GROUP_VERTICAL_SPACING, 10,
		NULL);
	return obj;
}

/*
 * Create object `HostGrp' in the specified instance.
 */
Xv_opaque
Props_PropsWin_HostGrp_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 30,
		XV_Y, 20,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->HostEdit,
			ip->HostListGrp,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_LEFT_EDGES,
		GROUP_VERTICAL_SPACING, 10,
		GROUP_ANCHOR_OBJ, ip->HostCtrl,
		GROUP_ANCHOR_POINT, GROUP_NORTHWEST,
		GROUP_REFERENCE_POINT, GROUP_NORTHWEST,
		GROUP_HORIZONTAL_OFFSET, 30,
		GROUP_VERTICAL_OFFSET, 20,
		NULL);
	return obj;
}

/*
 * Create object `HostName' in the specified instance.
 */
Xv_opaque
Props_PropsWin_HostName_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:HostName",
		XV_X, 55,
		XV_Y, 261,
		PANEL_VALUE_DISPLAY_LENGTH, 20,
		PANEL_VALUE_STORED_LENGTH, 64,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Host Name:"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `HostPwdClear' in the specified instance.
 */
Xv_opaque
Props_PropsWin_HostPwdClear_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	extern void		Props_PropsWin_HostPwdClear_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:HostPwdClear",
		XV_X, 310,
		XV_Y, 286,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Clear"),
		PANEL_NOTIFY_PROC, Props_PropsWin_HostPwdClear_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `HostPwd' in the specified instance.
 */
Xv_opaque
Props_PropsWin_HostPwd_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	extern void		Props_PropsWin_HostPwd_event_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:HostPwd",
		XV_X, 30,
		XV_Y, 288,
		PANEL_VALUE_DISPLAY_LENGTH, 20,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Root Password:"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_LEVEL, PANEL_ALL,
		PANEL_EVENT_PROC, Props_PropsWin_HostPwd_event_callback,
		NULL);
	return obj;
}

/*
 * Create object `HostPwdGrp' in the specified instance.
 */
Xv_opaque
Props_PropsWin_HostPwdGrp_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 30,
		XV_Y, 286,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->HostPwd,
			ip->HostPwdClear,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 10,
		NULL);
	return obj;
}

/*
 * Create object `HostParmGrp' in the specified instance.
 */
Xv_opaque
Props_PropsWin_HostParmGrp_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 30,
		XV_Y, 261,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->HostName,
			ip->HostPwdGrp,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_LABELS,
		GROUP_VERTICAL_SPACING, 10,
		GROUP_ANCHOR_OBJ, ip->HostGrp,
		GROUP_ANCHOR_POINT, GROUP_SOUTHWEST,
		GROUP_REFERENCE_POINT, GROUP_NORTHWEST,
		GROUP_HORIZONTAL_OFFSET, 0,
		GROUP_VERTICAL_OFFSET, 20,
		NULL);
	return obj;
}

/*
 * Create object `HostApply' in the specified instance.
 */
Xv_opaque
Props_PropsWin_HostApply_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	extern void		Props_PropsWin_HostApply_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:HostApply",
		XV_X, 138,
		XV_Y, 335,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Apply"),
		PANEL_NOTIFY_PROC, Props_PropsWin_HostApply_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `HostReset' in the specified instance.
 */
Xv_opaque
Props_PropsWin_HostReset_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	extern void		Props_PropsWin_HostReset_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "swmtool:HostReset",
		XV_X, 201,
		XV_Y, 335,
		PANEL_LABEL_STRING, dgettext("SUNW_INSTALL_SWM", "Reset"),
		PANEL_NOTIFY_PROC, Props_PropsWin_HostReset_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `HostLowButtons' in the specified instance.
 */
Xv_opaque
Props_PropsWin_HostLowButtons_create(Props_PropsWin_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 138,
		XV_Y, 335,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->HostApply,
			ip->HostReset,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 10,
		GROUP_ANCHOR_OBJ, ip->HostParmGrp,
		GROUP_ANCHOR_POINT, GROUP_SOUTH,
		GROUP_REFERENCE_POINT, GROUP_NORTH,
		GROUP_HORIZONTAL_OFFSET, 0,
		GROUP_VERTICAL_OFFSET, 30,
		NULL);
	return obj;
}

