/*
 * swmtool.h - Contains the object declarations for project swmtool
 * This file was generated by `gxv'.
 */


#include "Base_ui.h"
#include "Client_ui.h"
#include "Cmd_ui.h"
#include "File_ui.h"
#include "Meter_ui.h"
#include "Pkg_ui.h"
#include "Props_ui.h"


extern	Base_BaseWin_objects	*Base_BaseWin;
extern	Client_ClientWin_objects	*Client_ClientWin;
extern	Cmd_CmdWin_objects	*Cmd_CmdWin;
extern	File_FileWin_objects	*File_FileWin;
extern	Meter_MeterWin_objects	*Meter_MeterWin;
extern	Pkg_ProdWin_objects	*Pkg_ProdWin;
extern	Pkg_PkgWin_objects	*Pkg_PkgWin;
extern	Props_PropsWin_objects	*Props_PropsWin;

