#
#ident  "@(#)Makefile 1.7     96/04/18 SMI"
#
# Copyright (c) 1989,1996 by Sun Microsystems, Inc.
# All rights reserved.
#

FSTYPE=		ufs
LIBPROG=	ff
ATTMK=		$(LIBPROG)


include		../../Makefile.fstype

CPPFLAGS +=	-D_LARGEFILE64_SOURCE
LDLIBS +=
CFLAGS += 
lint:		lint_PROG
