#
#pragma ident	"@(#)Makefile	1.2	94/02/01 SMI"
#
# Copyright (c) 1994 by Sun Microsystems, Inc.
#
# cmd/adb/ppc/kadb/prep/Makefile
#
# The common makefile does all the work; this makefile is here to give the NSE
# a private place to record dependencies.
#

# this deliberately avoids macro names ARCH and KERNARCH for local control
ARCH=  prep
KARCH= ppc

include ../Makefile.com
