#!/sbin/sh
#	Copyright (c) 1984, 1986, 1987, 1988, 1989 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#
#	Copyright (c) 1991-1993, Sun Microsystems Inc.
#

#ident	"@(#)devlinks	1.5	93/10/06 SMI"

if [ -n "${_INIT_RECONFIG}" ]
then
	echo "Configuring the /dev directory"
	/usr/sbin/devlinks
	/usr/sbin/disks
	/usr/sbin/ports
	/usr/sbin/tapes
	/usr/sbin/audlinks
	if [ -x /usr/ucb/ucblinks -a -f /usr/ucblib/ucblinks.awk ]
	then
		echo "Configuring the /dev directory (compatibility devices)"
		/usr/ucb/ucblinks > /dev/null 2>&1
	fi
fi

#
# Establish the default framebuffer name.
#
fbdev=`/usr/sbin/prtconf -F 2>/dev/null`
if [ $? -eq 0 ]
then
	set /devices$fbdev*
	fbdev=$1
	if test -c $fbdev
	then
		rm -f /dev/fb
		ln -s $fbdev /dev/fb
	fi
fi
