#!/bin/sh
#ident	"@(#)mkdtab	1.8	96/10/02 SMI"	/* SVr4.0 1.1.1.1	*/

#
# Update device.tab and dgroup.tab files to reflect configuration.
# Script runs once at installation time and then removes itself.
#

if [ -x /usr/sadm/sysadm/bin/mkdtab ]
then
	/usr/sadm/sysadm/bin/mkdtab
	rm -f /etc/rc2.d/S82mkdtab
fi
