#!/bin/sh
#ident	"@(#)sysetup	1.14	96/10/02 SMI"	/* SVr4.0 1.4.2.1	*/

#   This file contains system setup requirements for the system.

#   First, the ps_data file is always removed so that the ps command
#   will be forced to read the /unix file, since it may have been
#   created recently.

set `/usr/bin/who -r`
if [ $9 != "S" -a $9 != "1" ]
then
	exit
fi

#   if the prtconf command exists, then, the system configuration
#   is printed
#   Default is not to do this. Too noisy, to long.

#if [ -x /usr/sbin/prtconf ]
#then
#	/usr/sbin/prtconf
#fi

#  If there are trademark files, print them.

if [ -d /etc/tm ]
then
	/usr/bin/cat /etc/tm/* 2> /dev/null
fi

##
## Default is to not do a savecore
##
#if [ ! -d /var/crash/`uname -n` ]
#then mkdir -m 0700 -p /var/crash/`uname -n`
#fi
#                echo 'checking for crash dump...\c '
#savecore /var/crash/`uname -n`
#                echo ''
