#
#ident	"@(#)Makefile	1.1	96/02/27 SMI"
#
# Copyright (c) 1996 by Sun Microsystems, Inc.
# All rights reserved.

include		$(SRC)/cmd/sgs/librtld/Makefile.com

.KEEP_STATE:

all:		$(DYNLIB) $(LIBLINKS)

install:	all $(ROOTDYNLIB)

lint:		$(LINTLIB)

include		$(SRC)/cmd/sgs/librtld/Makefile.targ
