#
#ident	"@(#)Makefile	1.5	96/03/18 SMI"
#
# Copyright (c) 1989 by Sun Microsystems, Inc.
#

PROG= checknr

include ../Makefile.cmd

.KEEP_STATE:

all: $(PROG) 

install: all $(ROOTPROG)

clean:

lint:	lint_PROG

include ../Makefile.targ
