#
#
#ident @(#)Makefile	1.4	95/02/24
#
#
include ../../../../Makefile.cmd

HELPTYPE = howto

HELPFILES = Howto	\
	boot.h.hlp \
	freedisk.h.hlp \
	hetserver.h.hlp \
	navigate.h.hlp \
	platform.h.hlp \
	preserve.h.hlp \
	resolve.h.hlp \
	softgroup.h.hlp \
	swap.h.hlp

all clean clobber:

install: ${ROOTGUIHDIR} ${ROOTGUIHELPFILES}

include ../../../../Makefile.targ
