#
#
#ident "@(#)Makefile 1.5 95/02/24"
#
#
include ../../../../Makefile.cmd

HELPTYPE = howto

HELPFILES = Howto	\
	boot.h.hlp \
	freedisk.h.hlp \
	platform.h.hlp \
	resolve.h.hlp \
	softgroup.h.hlp \
	vtoc.h.hlp

all clean clobber:

install: ${ROOTHDIR} ${ROOTHELPFILES}

include ../../../../Makefile.targ
