#
#ident	"@(#)Makefile	1.3	94/06/01 SMI"
#
# Copyright (c) 1989 by Sun Microsystems, Inc.
#

include 	../Makefile.com

.PARALLEL:	$(PICS)
.KEEP_STATE:

install all:	$(LIBRARY) .WAIT

lint:		$(LINTLIB)

include 	../Makefile.targ
