#!/bin/sh
#
#	@(#)postinstall 1.4 96/02/09
#
# Copyright (c) 1992-1996 Sun Microsystems, Inc.  All Rights Reserved. Sun
# considers its source code as an unpublished, proprietary trade secret, and
# it is available only under strict license provisions.  This copyright
# notice is placed here only to protect Sun in the event the source is
# deemed a published work.  Dissassembly, decompilation, or other means of
# reducing the object code to human readable form is prohibited by the
# license agreement under which this code is provided to the user or company
# in possession of this copy.
#
# RESTRICTED RIGHTS LEGEND: Use, duplication, or disclosure by the Government
# is subject to restrictions as set forth in subparagraph (c)(1)(ii) of the
# Rights in Technical Data and Computer Software clause at DFARS 52.227-7013
# and in similar clauses in the FAR and NASA FAR Supplement.
#
# Constants
#

ROOT=$PKG_INSTALL_ROOT
PROTO=$ROOT/proto

#
# Create the flag file that guarantees that install intro
# is presented only once
#
touch ${PROTO}/.run_install_intro

#
# Create an ASCII cpio archive of the root proto
# area
#
mv $PROTO $ROOT/.tmp_proto
