#
#ident	"@(#)Makefile	1.4	92/12/16 SMI"
#
# Copyright (c) 1989 by Sun Microsystems, Inc.
#
# lib/libplot/t4014/Makefile
#
LIBRARY= lib4014.a

OBJECTS=  \
arc.o     box.o     circle.o  close.o   dot.o     erase.o   label.o   line.o  \
linemod.o move.o    open.o    point.o   scale.o   space.o   subr.o

# include library definitions
include ../../Makefile.lib


all: $(LIBS)

install: $(ROOTLIBS)

# include library targets
include ../../Makefile.targ
