#
# ident	"@(#)Makefile	1.2	92/09/26 SMI"
#
# Copyright (c) 1992 by Sun Microsystems, Inc.
#
# cmd/psradm/Makefile
#

PROG=	psradm

include	../Makefile.cmd

OWNER = root
GROUP = sys

.KEEP_STATE:

all: $(PROG)

install: all $(ROOTUSRSBINPROG)

clean:

lint: lint_SRCS

include	../Makefile.targ
