#
#
#ident @(#)Makefile   1.6     96/07/01
#
#
include ../../../../Makefile.cmd

HELPTYPE = reference

HELPFILES = Reference	\
	allocate.r.hlp \
	constraints.r.hlp \
	filechanges.r.hlp \
	glossary.r.hlp \
	mount.r.hlp \
	navigate.r.hlp \
	selectmedia.r.hlp \
	spotchangedisk.r.hlp \
	spotcustdisk.r.hlp \
	spotcylinder.r.hlp \
	spotpreserve.r.hlp \
	spotseldisk.r.hlp \
	spotsoftcust.r.hlp \
	version.r.hlp

all clean clobber:

install: ${ROOTGUIHDIR} ${ROOTGUIHELPFILES}

include ../../../../Makefile.targ
