#
#ident	"@(#)Makefile	1.4	94/02/03 SMI"
#
# Copyright (c) 1993, 1994 by Sun Microsystems, Inc.
#
# cmd/sgs/dis/i386/Makefile
#

MACHOBJS=	bits.o tables.o

DEFLIST=	-DAR32WR -DI386 -DRBO -DPORTAR -DELF

include		../common/Makefile.com
