/*
 * Copyright (c) 1987-1989 by Sun Microsystems, Inc.
 */

#ident	"@(#)confunix.c	1.8	94/04/07 SMI"

/* Boot configuration. This file generated by config(8) */

#include <sys/bootconf.h>

#ifdef SAS
struct bootobj rootfs = {
	{ { "" },	{ "simd00a" } }
};

struct bootobj swapfile = {
	{ { "" },	{ "simd00b" } }
};
#else SAS
struct bootobj rootfs = {
	{ { "" },	{ "sd3a" } }
};

struct bootobj swapfile = {
	{ { "" },	{ "" } }
};
#endif SAS

struct bootobj frontfs = {
	{ { "" },	{ "" } }
};

struct bootobj backfs = {
	{ { "" },	{ "" } }
};

struct bootobj dumpfile = {
	{ { "" },	{ "" } }
};

#if 0
/*
 * not sure what this is for, swap size can be overridden
 * by a field given to swapfile above.  No other code
 * references this anyway.
 */
int nswap = 0;
#endif
