/*
 * Copyright (c) 1994, by Sun Microsytems, Inc.
 */

#pragma ident  "@(#)help.c 1.8 95/07/20 SMI"

#include <stdio.h>

static char	*helpstr =
"grammar for non-terminals:\n"
"__________________________\n"
"\n"
"filename ::=	QUOTED_STR\n"
"\n"
"selector_list ::= 	/* empty */ |\n"
"		<selector_list> <selector>\n"
"\n"
"spec_list ::=	/*empty */ |\n"
"		<spec_list> <spec>\n"
"\n"
"selector ::=	<spec>=<spec> |		/* whitespace around '=' optional */\n"
"		<spec>			/* keys attribute is default */\n"
"\n"
"spec ::= 	IDENT |\n"
"		QUOTED_STR |\n"
"		REGEXP\n"
"\n"
"pidlist ::=	<pid> |\n"
"		<pid> ',' <pidlist>\n"
"pid ::=		INT\n"
"\n"
"Reg-exps to match terminals:\n"
"____________________________\n"
"\n"
"IDENT 		= [a-zA-Z_\\.%]{[a-zA-Z0-9_\\.%]}+ \n"
"QUOTED_STR	= '[^\\n']*'		/* any string in single quotes	*/\n"
"REGEXP		= /[^\\n/]/		/* reg-exp's have to be in / /	*/\n"
"INT		= [0-9]+\n"
"\n"
"Commands:\n"
"_________\n"
"\n"
"# set creation and set listing\n"
"create $<set_name> <selector_list>\n"
"list sets				# list the defined sets\n"
"\n"
"# function listing\n"
"list fcns				# list the defined functions.\n"
"\n"
"# commands to connect and disconnect probe functions\n"
"# (not available in kernel mode)\n"
"connect &<fcn_handle> $<set_name>	# eg. connect &debug $all\n"
"connect &<fcn_handle> <selector_list>\n"
"\n"
"# command to disconnect all connected probe functions\n"
"# (not available in kernel mode)\n"
"clear $<set_name>\n"
"clear <selector_list>\n"
"\n"
"# commands to toggle the tracing mode\n"
"trace $<set_name>\n"
"trace <selector_list>\n"
"untrace $<set_name>\n"
"untrace <selector_list>\n"
"\n"
"# commands to enable and disable probes\n"
"enable $<set_name>\n"
"enable <selector_list>\n"
"disabe $<set_name>\n"
"disable <selector_list>\n"
"list history		# lists probe control commands issued\n"
"\n"
"# commands to list probes or to list values\n"
"list <spec_list> probes $<set_name>	#eg. list probes $all\n"
"list <spec_list> probes <selector_list> #eg. list name probes file=test.c\n"
"list values <spec_list>		# eg. list values keys\n"
"\n"
"# help command\n"
"help\n"
"\n"
"# source a file of prex commands\n"
"source <filename>\n"
"\n"
"# process control - ^C stops target and returns to 'prex>' prompt\n"
"# (In kernel mode, `continue' is a no-op, and 'quit' detaches prex\n"
"# from the kernel.)\n"
"continue		# continues target\n"
"quit kill		# quit prex, kill target\n"
"quit resume		# quit prex, continue target\n"
"quit suspend		# quit prex, leave target suspended\n"
"quit			# quit prex (continue or kill target)\n"
"\n"

"\n"
"# Kernel mode commands\n"
"# \"master switch\" enabling/disabling all tracing\n"
"ktrace on		# Enabled probes will generate trace output\n"
"ktrace off		# All trace output suppressed\n"
"# Create, destroy, or show the size of the kernel trace buffer\n"
"buffer [ alloc [ size ] | dealloc ]\n"
"# Control per-process kernel trace filtering\n"
"pfilter off		# Filtering off:  trace all processes\n"
"pfilter on		# Filtering on:  trace only processes in filter set\n"
"pfilter add <pidlist>		# Add specified process ids to the filter set\n"
"pfilter delete <pidlist>	# Drop specified pids from the filter set\n"
"\n"
;


void
help(void)
{
	(void) fputs(helpstr, stdout);

}				/* end help */
