#
#
#ident @(#)Makefile   1.7     96/07/29
#
#
include ../../../../Makefile.cmd

HELPTYPE = topics

HELPFILES = Topics	\
	allocate.t.hlp \
	autolayout.t.hlp \
	boot.t.hlp \
	diskless.t.hlp \
	diskname.t.hlp \
	diskpart.t.hlp \
	fdisk.t.hlp \
	hetserver.t.hlp \
	initial.t.hlp \
	language.t.hlp \
	load.t.hlp \
	morespace.t.hlp \
	mount.t.hlp \
	navigate.t.hlp \
	softgroup.t.hlp \
	upgrade.t.hlp

all clean clobber:

install: ${ROOTGUIHDIR} ${ROOTGUIHELPFILES}

include ../../../../Makefile.targ
