#
#ident	"@(#)Makefile 1.5 94/10/18 SMI"
#
# Copyright (c) 1993 by Sun Microsystems, Inc.
#

include ../Makefile.com

DATAFILES +=

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
