#! /bin/sh
#ident	"@(#)printer	1.1	94/02/04 SMI"
# Copyright (c) 1994 by Sun Microsystems, Inc.

/usr/openwin/bin/ttsession -c /etc/lp/alerts/sendMsg "lp_printer_alert" "/etc/lp/printers" "$1" "$3" "$2"
