#
#ident	"@(#)Makefile	1.1	95/08/16 SMI"
#
# Copyright (c) 1995 by Sun Microsystems, Inc.
# All rights reserved.
#

include		../Makefile.com

.KEEP_STATE:

all:		$(OBJDIR) .WAIT $(PROG)

install:	all $(ROOTONLDBINPROG)

lint:		$(LINTOUT)

include		../Makefile.targ
