#ifndef lint
#ident   "@(#)svc_templates.c 1.16 96/10/09 SMI"
#endif

/*
 * Copyright (c) 1995-1996, by Sun Microsystems, Inc. All rights reserved.
 *
 *
 * Implementation notes for DryRun support:
 * The arrays should be of the form:
 *	"shell script text",
 *	"...",
 *	"",
 *	"DryRun @TOKEN0@ @TOKEN1@ ...",
 *	"dryrun text",
 *	"...",
 *	""
 *  If the DryRun text doesn't need localization, then the @TOKEN@ tokens
 *  may be used.
 *  If the DryRun text is to be internationalized, it should be of the form:
 *	"gettext SUNW_INSTALL_LIBSVC 'Actual text user will see'",
 *  and any tokens should be replaced by "$0n" where n is the index of the
 *  token in the DryRun eyecatcher line.
 *  Although a little convoluted, this allows us to add DryRun with a minimum
 *  impact on other processes.
 */
char *script_start[] = {
"#!/bin/sh",
"#",
"# This shell function and the function suninstall_date_time found",
"# in .../src/bundled/app/files/suninstall.sh are the same.  If a change",
"# is made to one, the same change has to be made to the other.",
"templates_date_time() {",
"	old_name=$1 ",
"	mon=`ls -l $old_name | awk ' { printf(\"%s\", $6) } ' `",
"	day=`ls -l $old_name | awk ' { printf(\"%s\", $7) } ' `",
"	year=`ls -l $old_name | awk ' { printf(\"%s\", $8) } ' `",
"	mon_day=\"${mon}${day}\"",
"	if echo $year | grep ':' >/dev/null 2>&1",
"	then",
"	    case $mon in",
"	        Jan) mon_ndx=1 ;;",
"	        Feb) mon_ndx=2 ;;",
"	        Mar) mon_ndx=3 ;;",
"	        Apr) mon_ndx=4 ;;",
"	        May) mon_ndx=5 ;;",
"	        Jun) mon_ndx=6 ;;",
"	        Jul) mon_ndx=7 ;;",
"	        Aug) mon_ndx=8 ;;",
"	        Sep) mon_ndx=9 ;;",
"	        Oct) mon_ndx=10 ;;",
"	        Nov) mon_ndx=11 ;;",
"	        Dec) mon_ndx=12 ;;",
"	    esac",
"	    current_mon_ndx=`date \"+%m\"`",
"	    year=`date \"+%Y\"`",
"	    if [ \"$mon_ndx\" -gt \"$current_mon_ndx\" ] ; then",
"	    	year=`expr $year - 1`",
"	    fi",
"	fi",
"	new_name=\"${2}_${mon_day}_${year}\"",
"	ndx=\"0\"",
"	ndx_str=",
"	while [ -f ${new_name}${ndx_str} ] ; do",
"		ndx=`expr $ndx + 1`",
"		ndx_str=\"_$ndx\"",
"	done",
"	echo \"${mon_day}_${year}${ndx_str}\"",
"}",
"logprogress() {",
"	if [ \"$2\" = \"none\" ] ; then",
"		do_sig=no",
"	else",
"		do_sig=yes",
"	fi",
"	if [ \"$do_sig\" = \"yes\" ] ; then",
"		comp_acts=`expr $comp_acts + 1`",
"		echo $2 $3 $total_actions $comp_acts > /tmp/upg_prog",
"	fi",
"	echo \"LASTCMD=$1\\nTIMESTAMP=$timestamp\" > $restart",
"	echo \"TOTAL_ACTIONS=$total_actions\" >> $restart",
"	echo \"COMPLETED_ACTIONS=$comp_acts\" >> $restart",
"	sync",
"	cp $restart $restartbkup",
"	sync",
"	if [ \"$do_sig\" = \"yes\" -a \"$ppid\" != \"none\" ] ; then",
"		kill -USR1 $ppid",
"	fi",
"}",
"recover_file() {",
"	if [ -f $1.bk ] ; then",
"		cp $1.bk $1",
"		rm $1.bk",
"	fi",
"}",
"log_file_diff() {",
"	original_target=$3",
"	new_target=$4",
"	case $3 in",
"	f|e|v)",
"		actual_type=`gettext 'regular file'`",
"	;;",
"	d|x)",
"		actual_type=`gettext 'directory'`",
"	;;",
"	p)",
"		actual_type=`gettext 'named pipe'`",
"	;;",
"	c)",
"		actual_type=`gettext 'character special device'`",
"	;;",
"	b)",
"		actual_type=`gettext 'block special device'`",
"	;;",
"	s)",
"		actual_type=`gettext 'symbolic link'`",
"	;;",
"	esac",
"	case $4 in",
"	f|e|v)",
"		exp_type=`gettext 'regular file'`",
"	;;",
"	d|x)",
"		exp_type=`gettext 'directory'`",
"	;;",
"	p)",
"		exp_type=`gettext 'named pipe'`",
"	;;",
"	c)",
"		exp_type=`gettext 'character special device'`",
"	;;",
"	b)",
"		exp_type=`gettext 'block special device'`",
"	;;",
"	s)",
"		exp_type=`gettext 'symbolic link'`",
"	;;",
"	esac",
"	case $1 in",
"	DIFF_TYPE)",
"	eval echo `gettext SUNW_INSTALL_LIBSVC '$2: file type was changed from $exp_type to $actual_type.'` >> $coalesce",
"	;;",
"	DIFF_MISSING)",
"	eval echo `gettext SUNW_INSTALL_LIBSVC '$2: had been deleted and has now been restored.'` >> $coalesce",
"	;;",
"	DIFF_SLINK_TARGET)",
"	eval echo `gettext SUNW_INSTALL_LIBSVC '$2: target of symbolic link was changed from $original_target to $new_target.'` >> $coalesce",
"	;;",
"	DIFF_HLINK_TARGET)",
"	eval echo `gettext SUNW_INSTALL_LIBSVC '$2: target of hard link was changed from $original_target.'` >> $coalesce",
"	;;",
"	esac",
"	cleanup_needed=1",
"}",
"rename_file() {",
"	(cd $rbase; cd ./$1",
"	if [ -r ./$2:$3 ] ; then ",
"		mv ./$2:$3 ./$2:$3~",
"		arg1=\"$1$2:$3\"",
"		arg2=\"$1$2:$3~\"",
"	fi",
"	mv ./$2 ./$2:$3 )",
"	arg1=\"$1$2\"",
"	arg2=\"$1$2:$3\"",
"	eval echo `gettext SUNW_INSTALL_LIBSVC '$arg1: existing file renamed to $arg2'` >> $coalesce",
"	cleanup_needed=1",
"}",
"do_pkgadd() {",
"	eval echo `gettext SUNW_INSTALL_LIBSVC 'Doing pkgadd of $2 to $1.'`",
"	rm -f /tmp/CLEANUP",
"	(if [ \"$1\" = \"/\" ] ; then",
"	   if [ \"${rbase}\" = \"/\" ] ; then",
"	      pkgadd -S -M -d $3 -a /tmp/admin.$4.$$ -n $2",
"	   else",
"	      pkgadd -S -M -R ${rbase} -d $3 -a /tmp/admin.$4.$$ -n $2",
"	   fi",
"	else",
"	   pkgadd -S -M -R ${base}$1 -d $3 -a /tmp/admin.$4.$$ -n $2 ",
"	fi",
"	errcode=$?",
"	if [ $errcode != 0 ] ; then",
"		echo `gettext SUNW_INSTALL_LIBSVC 'pkgadd return code = '` $errcode",
"		echo $2 >> $failedpkgs",
"	fi) 2>&1 | sed -f /tmp/filter.$$",
"	if [ -f /tmp/CLEANUP ] ; then",
"		cat /tmp/CLEANUP | {",
"			while read key arg1 arg2",
"			do",
"				case $key in",
"				EXISTING_FILE_RENAMED:)",
"				eval echo `gettext SUNW_INSTALL_LIBSVC '$arg1: existing file renamed to $arg2'` ;;",
"				EXISTING_FILE_PRESERVED:)",
"				eval echo `gettext SUNW_INSTALL_LIBSVC '$arg1: existing file preserved, the new version was installed as $arg2'` ;; ",
"				SYSADMIN_NOT_14)",
"				echo",
"				eval echo `gettext SUNW_INSTALL_LIBSVC '$arg1:  Caution!'`",
"				gettext 'Group \"sysadmin\" is already defined in the above file.  However, the group\\nid for \"sysadmin\" is defined as something other than 14.  This is a hole in\\nsecurity, because admintool\\(1M\\) grants all users in group \"sysadmin\" the\\nright to run privileged admintool operations on remote hosts.  You must set\\ngroup \"sysadmin\" equal to group id 14 in the above file \\(the appropriate\\nentry of \"sysadmin::14:\" has been appended to the end of the above file\\nautomatically for you.\\)'",
"				echo \"\\n\" ;;",
"				GROUP14_IN_USE)",
"				echo",
"				eval echo `gettext SUNW_INSTALL_LIBSVC '$arg1:  Caution!'`",
"				gettext 'Group id 14 is already defined in the above file.  However, the group name\\nfor group id 14 is defined as something other than \"sysadmin\".  This is a\\nhole in security, because admintool\\(1M\\) grants all users in group id 14 the\\nright to run privileged admintool operations on remote hosts.  You must set\\ngroup id 14 equal to group \"sysadmin\" in the above file \\(the appropriate entry\\nof \"sysadmin::14:\" has been appended to the end of the above file\\nautomatically for you.\\) You will also have to change all files on your\\nsystem which are currently owned by group id 14 to the new group id.'",
"				echo \"\\n\" ;;",
"				*)",
"				echo $key $arg1 $arg2 ;;",
"				esac",
"			done",
"		} >> $coalesce",
"		cleanup_needed=1",
"		rm -f /tmp/CLEANUP",
"	fi",
"}",
"do_removef() {",
"	if [ \"$1\" = \"/\" ] ; then",
"	   cat /tmp/rmlist.$$ | xargs removef -M -R ${rbase} $2 | sort -r | \\",
"		while read path",
"		do",
"			if [ \"$path\" != \"\" ] ; then",
"				if [ -d \"$path\" ] ; then",
"					rmdir $path >/dev/null 2>&1",
"				else",
"					rm -f $path",
"				fi",
"			fi",
"		done",
"	else",
"	   cat /tmp/rmlist.$$ | xargs removef -M -R ${base}$1 $2 | sort -r | \\",
"		while read path",
"		do",
"			if [ \"$path\" != \"\" ] ; then",
"				if [ -d \"$path\" ] ; then",
"					rmdir $path >/dev/null 2>&1",
"				else",
"					rm -f $path",
"				fi",
"			fi",
"		done",
"	fi",
"	if [ \"$1\" = \"/\" ] ; then",
"	   removef -M -R ${rbase} -f $2 >/dev/null",
"	else",
"	   removef -M -R ${base}$1 -f $2 >/dev/null",
"	fi",
"	errcode=$?",
"	if [ $errcode != 0 ] ; then",
"		echo `gettext SUNW_INSTALL_LIBSVC 'removef return code = '` $errcode",
"	fi",
"}",
"add_rdot_files() {"
"	(if [ -d $1/var/sadm/pkg/$2/install ] ; then",
"	    cd $1/var/sadm/pkg/$2/install",
"	    for f in i.* ; do",
"		if [ \"$f\" = 'i.*' ] ; then",
"		    break;",
"		fi",
"		class=`expr $f : 'i\\.\\(.*\\)'`",
"		if [ ! -f r.$class ] ; then",
"		    echo \"exit 0\" > r.$class",
"		fi",
"	    done",
"	fi)",
"}",
"do_pkgrm() {",
"	if [ \"$1\" = \"/\" ] ; then",
"		rmbase=${rbase}",
"	else",
"		rmbase=${base}$1",
"	fi",
"	add_rdot_files $rmbase $2",
"	eval echo `gettext SUNW_INSTALL_LIBSVC 'Removing package $2:'`",
"	pkgrm -M -R ${rmbase} -a /tmp/admin.dflt.$$ -n $2",
"	errcode=$?",
"	if [ $errcode != 0 ] ; then",
"		echo `gettext SUNW_INSTALL_LIBSVC 'pkgrm return code = '` $errcode",
"	fi",
"}",
"do_pkgrm_f() {",
"	if [ \"$1\" = \"/\" ] ; then",
"		rmbase=${rbase}",
"	else",
"		rmbase=${base}$1",
"	fi",
"	add_rdot_files $rmbase $2",
"	pkgrm -M -R ${rmbase} -a /tmp/admin.dflt.$$ -F -n $2",
"	errcode=$?",
"	if [ $errcode != 0 ] ; then",
"		echo `gettext SUNW_INSTALL_LIBSVC 'pkgrm return code = '` $errcode",
"	fi",
"}",
"do_install_inetboot() {",
"  bootdir=$1",
"  karch=$2",
"  svcprod=$3",
"  svcver=$4",
"  (cd ${base}/${bootdir}",
"  if [ -f inetboot.${karch}.${svcprod}.${svcver} -a \\",
"	! -h inetboot.${karch}.${svcprod}.${svcver} ] ; then",
"     old=inetboot.${karch}.${svcprod}.${svcver}",
"  elif [ -f inetboot.${karch}.${svcprod}_${svcver} -a \\",
"	! -h inetboot.${karch}.${svcprod}_${svcver} ] ; then",
"     old=inetboot.${karch}.${svcprod}_${svcver}",
"  else",
"     old=",
"  fi",
"  inetcopy=",
"  if [ \"$old\" != \"\" ] ; then",
"	for i in inetboot.* ; do",
"	    if [ \"$i\" = \"inetboot.*\" ] ; then",
"		break",
"	    fi",
"	    if [ ! -h $i ] ; then",
"		continue",
"	    fi",
"	    link=`/bin/ls -l $i | sed 's/^.*-> \\(.*\\)/\\1/'`",
"	    link2=`expr $link : '\\.\\/\\(.*\\)'`",
"	    if [ \"$link2\" != \"\" ] ; then",
"		link=$link2",
"	    fi",
"	    if [ \"$link\" = \"$old\" ] ; then",
"		rm -f $i",
"		if [ \"$inetcopy\" != \"\" ] ; then",
"		    ln -s $inetcopy $i",
"		else",
"		    mv $old $i",
"		    inetcopy=$i",
"		fi",
"	    fi",
"	done",
"   fi",
"   rm -f inetboot.${karch}.${svcprod}[._]${svcver}",
"   for i in inetboot.*.${svcprod}_${svcver} ; do",
"	    if cmp -s $i $inetboot ; then",
"		ln -s $i inetboot.${karch}.${svcprod}_${svcver}",
"		break",
"	    fi",
"   done",
"   if [ ! -h inetboot.${karch}.${svcprod}_${svcver} ] ; then",
"       cp $inetboot inetboot.${karch}.${svcprod}_${svcver}",
"   fi",
"   if [ \"${bootdir}\" = \"rplboot\" ] ; then",
"	cp $gluedir/gluecode.com .",
"	cp $gluedir/smc.com .",
"   fi",
"   )",
"}",
"mount_filesys() {",
"/usr/sbin/fsck -m -F $1 $4 >/dev/null 2>&1",
"case $? in",
"  0)	/sbin/mount -F $1 $2 ${base}$3",
"	if [ $? -ne 0 ]; then",
"		eval echo `gettext SUNW_INSTALL_LIBSVC 'Unable to mount ${base}$4'` $? ",
"		exit 2",
"	fi",
"	;;",
"  32)	mount | grep \" $2 \"  >/dev/null 2>&1 ",
"	if [ $? -ne 0 ]; then",
"		eval echo `gettext SUNW_INSTALL_LIBSVC 'The ${base}$3 file system $4 is being checked.'`",
"		/usr/sbin/fsck -F $1 -o p $4",
"		case $? in",
"		  0|40)	;;",
"		  *)	eval echo `gettext SUNW_INSTALL_LIBSVC 'Unable to fsck ${base}$3'` $?",
"			exit 2 ;;",
"		esac",
"		/sbin/mount -F $1 $2 ${base}$3",
"		if [ $? -ne 0 ]; then",
"			eval echo `gettext SUNW_INSTALL_LIBSVC 'Unable to mount ${base}$3'` $?",
"			exit 2",
"		fi",
"	else",
"		mount | grep \" $2 \" | while read real_mntpt junk real_device junk",
"		do",
"		if [ \"$real_mntpt\" != \"$3\" ]; then",
"			eval echo `gettext SUNW_INSTALL_LIBSVC 'Unable to mount ${base}$3'` $?",
"			eval echo `gettext SUNW_INSTALL_LIBSVC '$2 mounted at ${base}$real_mntpt'` $?",
"			exit 2",
"		fi",
"		done",
"	fi",
"	;;",
"  33)  ;;",
"  *)	eval echo `gettext SUNW_INSTALL_LIBSVC 'Unrecognized error from fsck of ${base}$3'` $?",
"	exit 2 ;;",
"esac",
"}",
"remove_patch() {",
"ls -L ${base}$1/var/sadm/patch >/dev/null 2>&1",
"if [ $? = 0 ] ; then",
"  eval echo `gettext SUNW_INSTALL_LIBSVC 'Removing patch $2 from the system.'`",
"  rm -fr ${base}$1/var/sadm/patch/$2",
"else",
"  if [ -h ${base}$1/var/sadm/patch ] ; then",
"	link=`ls -l ${base}$1/var/sadm/patch | sed -n 's,.* \\(/.*\\),\\1,p'`",
"	if [ \"$link\" != \"\" ] ; then",
"		mv ${base}$1/var/sadm/patch ${base}$1/var/sadm/patch.save.$$",
"		rm -fr ${base}$1/var/sadm/patch",
"		ln -s ${base}$1/${link} ${base}$1/var/sadm/patch",
"		ls -L ${base}$1/var/sadm/patch >/dev/null 2>&1",
"		if [ $? = 0 ] ; then",
"			eval echo `gettext SUNW_INSTALL_LIBSVC 'Removing patch $2 from the system.'`",
"			rm -fr ${base}$1/var/sadm/patch/$2",
"		fi",
"		rm ${base}$1/var/sadm/patch",
"	fi",
"		mv ${base}$1/var/sadm/patch.save.$$ ${base}$1/var/sadm/patch",
"  fi",
"fi",
"}",
"# Execution start",
"base=$1",
"Usage='usage: upgrade_script <basedir> [<parent-pid>] [restart]'",
"if [ \"$base\" = \"\" ] ; then",
"	echo $Usage",
"	exit 1",
"fi",
"tbase=`expr ${base}/ : '\\(/.*\\)/'`",
"if [ \"$tbase\" = \"\" -o ! -d \"$tbase\" ] ; then",
"	echo 'first argument not a basedir'",
"	exit 1",
"fi",
"# total_actions is hardcoded at script generation time",
"total_actions=0",
"comp_acts=0",
"do_restart=no",
"ppid=none",
"shift",
"# Get optional ppid and restart",
"for A in $*",
"do",
"	case $A in",
"	restart)	if [ $do_restart = \"yes\" ] ; then",
"				echo $Usage",
"				exit 1",
"			fi",
"			do_restart=yes",
"			;;",
"	*)		if [ \"$ppid\" != \"none\" ] ; then",
"				echo $Usage",
"				exit 1",
"			fi",
"			tmp=`expr $A : '\\([0-9][0-9]*\\)'`",
"			if [ \"$tmp\" != \"$A\" ] ; then",
"				echo \"invalid PID: $A\"",
"				exit 1",
"			fi",
"			ppid=$tmp",
"			;;",
"	esac",
"done",
"rbase=$base",
"if [ \"$base\" = \"/\" ] ; then",
"	base=\"\"",
"fi",
"timestamp=@TIMESTAMP@",
"restart=${base}@RESTART_PATH@",
"restartbkup=${base}@RESTART_PATH@.bkup",
"coalesce=${base}@CLEANUP_PATH@",
" ",
"if [ -h ${base}/var/sadm/install_data/upgrade_cleanup ] ; then",
"	rm -f ${base}/var/sadm/install_data/upgrade_cleanup",
"fi",
"if [ -h ${base}/var/sadm/system/data/upgrade_cleanup ] ; then",
"	rm -f ${base}/var/sadm/system/data/upgrade_cleanup",
"fi",
"if [ -f ${base}/var/sadm/install_data/upgrade_cleanup ] ; then",
"	date_time=`templates_date_time ${base}/var/sadm/install_data/upgrade_cleanup ${base}/var/sadm/system/data/upgrade_cleanup`",
"	mv ${base}/var/sadm/install_data/upgrade_cleanup ${base}/var/sadm/system/data/upgrade_cleanup_${date_time}",
"	chmod 644 ${base}/var/sadm/system/data/upgrade_cleanup_${date_time}",
"fi",
"if [ -f ${base}/var/sadm/system/data/upgrade_cleanup ] ; then",
"	date_time=`templates_date_time ${base}/var/sadm/system/data/upgrade_cleanup ${base}/var/sadm/system/data/upgrade_cleanup`",
"	mv ${base}/var/sadm/system/data/upgrade_cleanup ${base}/var/sadm/system/data/upgrade_cleanup_${date_time}",
"	chmod 644 ${base}/var/sadm/system/data/upgrade_cleanup_${date_time}",
"fi",
" ",
"failedpkgs=${base}@UPGRADE_FAILED_PKGS@",
"cleanup_needed=0",
"EXIT_CODE=0",
"resumecnt=0",
"savestamp=",
"restarting=no",
"TEXTDOMAIN=SUNW_INSTALL_LIBSVC",
"export TEXTDOMAIN",
"if [ \"$do_restart\" = \"yes\" ] ; then",
"	if [ -f $restart ] ; then",
"	    resumecnt=`grep LASTCMD $restart | sed 's/^.*=//'`",
"	    savestamp=`grep TIMESTAMP $restart | sed 's/^.*=//'`",
"	    comp_acts=`grep COMPLETED_ACTIONS $restart | sed 's/^.*=//'`",
"	    restarting=yes",
"	fi",
"	if [ \"$savestamp\" != \"$timestamp\" ] ; then",
"	    if [ -f $restartbkup ] ; then",
"		resumecnt=`grep LASTCMD $restartbkup | sed 's/^.*=//'`",
"		savestamp=`grep TIMESTAMP $restartbkup | sed 's/^.*=//'`",
"		comp_acts=`grep COMPLETED_ACTIONS $restartbkup | sed 's/^.*=//'`",
"		restarting=yes",
"	    fi",
"	fi",
"	if [ \"$savestamp\" != \"$timestamp\" ] ; then",
"		gettext SUNW_INSTALL_LIBSVC 'Cannot restart upgrade.  No valid upgrade log.'; echo",
"	    exit 2",
"	fi",
"fi",
"if [ $restarting = yes ] ; then",
"	gettext SUNW_INSTALL_LIBSVC 'Restarting upgrade:'; echo",
"else",
"	gettext SUNW_INSTALL_LIBSVC 'Starting upgrade:'; echo",
"fi",
"file /usr/sbin/pkgadd >/dev/null 2>&1",
"if [ $? != 0 ] ; then",
"	gettext SUNW_INSTALL_LIBSVC 'Fatal error:  cannot access the command /usr/sbin/pkgadd.'; echo",
"	exit 2",
"fi",
"if [ ! -d ${base}/var/spool/mqueue ]; then",
"	mkdir ${base}/var/spool/mqueue",
"fi",
"cat > /tmp/filter.$$ << EOF",
"/^WARNING: .*<no longer .*>/d",
"/^WARNING: quick verify of <.*>; wrong mod time./d",
"EOF",
"",
"DryRun",
""
};

char *init_swm_coalesce[] = {
"if [ $restarting = no ] ; then",
"	rm -f $coalesce",
"	rm -f $failedpkgs",
"	> $coalesce",
"	chmod 644 $coalesce",
"fi",
"",
"DryRun",
""
};

char *init_coalesce[] = {
"if [ $restarting = no ] ; then",
"	rm -f $coalesce",
"	rm -f $failedpkgs",
"	touch $coalesce",
"	chmod 644 $coalesce",
"(gettext SUNW_INSTALL_LIBSVC 'This file contains a list of files on the upgraded system that may need\\nto be manually modified after the upgrade.  Typically, the files in this\\nlist are files that were modified since their original installation.'",
"echo \"\\n\"",
"gettext SUNW_INSTALL_LIBSVC 'The following text explains the entries in this file:'",
"echo '\\n'",
"gettext SUNW_INSTALL_LIBSVC 'ENTRY:'; echo",
"gettext SUNW_INSTALL_LIBSVC '<file1>: existing file renamed to <file2>'",
"echo '\\n'",
"gettext SUNW_INSTALL_LIBSVC 'EXPLANATION:'; echo",
"gettext SUNW_INSTALL_LIBSVC 'The file with the name <file1> was present on the system at the time of\\nthe upgrade.  It had been modified since its original installation,\\nso the upgrade program renamed it to <file2>.'",
"echo '\\n'",
"gettext SUNW_INSTALL_LIBSVC 'RECOMMENDED ACTION:'; echo",
"gettext SUNW_INSTALL_LIBSVC 'The user should examine the contents of the renamed file to determine\\nwhether the modifications made to the file should be made to the\\nnewly installed version of the file, which will have name <file1>\\nafter the upgrade completes.'",
"echo '\\n\\n'",
"gettext SUNW_INSTALL_LIBSVC 'ENTRY'; echo",
"gettext SUNW_INSTALL_LIBSVC '<file1>: existing file preserved, the new version was installed as <file2>'",
"echo '\\n'",
"gettext SUNW_INSTALL_LIBSVC 'EXPLANATION'; echo",
"gettext SUNW_INSTALL_LIBSVC 'The file with the name <file1> has been preserved.  The new version of\\nthe file was installed as <file2>.'",
"echo '\\n'",
"gettext SUNW_INSTALL_LIBSVC 'RECOMMENDED ACTION:'; echo",
"gettext SUNW_INSTALL_LIBSVC 'The user should examine <file2> to determine whether changes made to\\n<file2> should be incorporated into the preserved version of the file.'",
"echo '\\n\\n'",
"gettext SUNW_INSTALL_LIBSVC 'ENTRY'; echo",
"gettext SUNW_INSTALL_LIBSVC '<file>: had been deleted and has now been restored'",
"echo '\\n'",
"gettext SUNW_INSTALL_LIBSVC 'EXPLANATION'; echo",
"gettext SUNW_INSTALL_LIBSVC 'The file with the name <file> had been deleted from the system since\\nits original installation.  The upgrade has installed the new version\\nof the file.'",
"echo '\\n'",
"gettext SUNW_INSTALL_LIBSVC 'RECOMMENDED ACTION:'; echo",
"gettext SUNW_INSTALL_LIBSVC 'The user should determine whether the new version of the file should be\\ndeleted also.'",
"echo '\\n\\n'",
"gettext SUNW_INSTALL_LIBSVC 'ENTRY'; echo",
"gettext SUNW_INSTALL_LIBSVC '<file>: file type was changed from <type1> to <type2>'",
"echo '\\n'",
"gettext SUNW_INSTALL_LIBSVC 'EXPLANATION'; echo",
"gettext SUNW_INSTALL_LIBSVC 'At its original installation, the file with the name <file> was of type\\n<type1>.  Later, it was replaced by a file of type <type2>.  For example,\\na symbolic link may have been replaced by a regular file.  In most cases,\\nthe upgrade will restore the file to its original type.'",
"echo '\\n'",
"gettext SUNW_INSTALL_LIBSVC 'RECOMMENDED ACTION:'; echo",
"gettext SUNW_INSTALL_LIBSVC 'The user should determine whether the new version of the file should also\\nbe replaced by a file of type <type2>.'",
"echo '\\n\\n'",
"gettext SUNW_INSTALL_LIBSVC 'ENTRY'; echo",
"gettext SUNW_INSTALL_LIBSVC '<file>: target of symbolic link was changed from <target1> to <target2>'",
"echo '\\n'",
"gettext SUNW_INSTALL_LIBSVC 'EXPLANATION'; echo",
"gettext SUNW_INSTALL_LIBSVC 'At the time of its original installation, <file> was a symbolic link\\nto <target1>.  It was changed to be a symbolic link to <target2>.\\nThe upgrade would have changed the link to point to its original\\ntarget.'",
"echo '\\n'",
"gettext SUNW_INSTALL_LIBSVC 'RECOMMENDED ACTION:'; echo",
"gettext SUNW_INSTALL_LIBSVC 'The user should determine whether the symbolic link should be changed\\nto point to the target to which it pointed before the upgrade.'",
"echo '\\n\\n'",
"gettext SUNW_INSTALL_LIBSVC 'ENTRY'; echo",
"gettext SUNW_INSTALL_LIBSVC '<file1>: target of hard link was changed from <file2>'",
"echo '\\n'",
"gettext SUNW_INSTALL_LIBSVC 'EXPLANATION'; echo",
"gettext SUNW_INSTALL_LIBSVC 'When originally installed, <file1> was a hard link to <file2>.  At the\\ntime of upgrade, it was no longer a hard link to <file2>.  The upgrade\\nwould have restored the original link.'",
"echo '\\n'",
"gettext SUNW_INSTALL_LIBSVC 'RECOMMENDED ACTION:'; echo",
"gettext SUNW_INSTALL_LIBSVC 'The user should determine whether the restored link should be changed\\nto what it was before the upgrade.'",
"echo '\\n\\n'",
"gettext SUNW_INSTALL_LIBSVC 'Before the system is rebooted, all files listed below should be\\nreferenced relative to /a.'",
"echo '\\n'",
"echo '---------------------------------------------------------------------------'",
") >> $coalesce",
"fi",
"",
"DryRun",
""
};

char *add_swap_cmd[] = {
"/usr/sbin/swap -l | /bin/grep @MNTDEV@ >/dev/null 2>&1",
"if [ $? != 0 ] ; then",
"	/usr/sbin/swap -a @MNTDEV@",
"	if [ $? != 0 ]; then",
"		echo `gettext SUNW_INSTALL_LIBSVC 'add swap failure'` $?",
"		exit 2",
"	fi",
"fi",
"",
"DryRun @MNTDEV@",
"gettext SUNW_INSTALL_LIBSVC 'Add swap on $00'",
""
};

char *del_swap_cmd[] = {
"/usr/sbin/swap -d @MNTDEV@",
"if [ $? != 0 ]; then",
"	echo `gettext SUNW_INSTALL_LIBSVC 'delete swap failure'` $?",
"fi",
"",
"DryRun @MNTDEV@",
"gettext SUNW_INSTALL_LIBSVC 'Delete swap on $00'",
""
};

char *mount_fs_cmd[] = {
"mount_filesys @FSTYPE@ @MNTDEV@ @MNTPNT@ @FSCKDEV@",
"",
"DryRun",
"fsck @FSCKDEV@",
"mount -F @FSTYPE@ @MNTDEV@ @MNTPNT@",
""
};

char *build_admin_file[] = {
"cat > /tmp/admin.@NAME@.$$ << EOF",
"mail=",
"instance=@INSTANCE@",
"partial=nocheck",
"runlevel=nocheck",
"idepend=nocheck",
"rdepend=nocheck",
"space=nocheck",
"setuid=nocheck",
"conflict=nocheck",
"action=nocheck",
"basedir=@BASEDIR@",
"EOF",
"",
"DryRun @NAME@ @INSTANCE@ @BASEDIR@",
"gettext SUNW_INSTALL_LIBSVC 'Building admin file $00, instance = $01, basedir = $02'",
""
};

char *touch_upgrade[] = {
"touch @BASEDIR@/.UPGRADE",
"",
"DryRun",
"touch @BASEDIR@/.UPGRADE",
""
};

char *do_pkgadd[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	do_pkgadd @ROOT@ @PKG@ @SPOOL@ @ADMIN@",
"	logprogress @SEQ@ pkgadd @PKG@",
"fi",
"",
"DryRun",
"pkgadd -M -R @ROOT@ -d @SPOOL@ -a @ADMIN@ @PKG@",
""
};

char *print_copyright[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	echo",
"	gettext SUNW_INSTALL_LIBSVC 'Installing new packages'; echo; echo",
"	sleep 3",
"	cat @SPOOL@/@PKG@/install/copyright",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"gettext SUNW_INSTALL_LIBSVC 'Installing new packages'",
""
};

char *print_rmpkg_msg[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	gettext SUNW_INSTALL_LIBSVC 'Removing obsolete packages and saving modified files'; echo; echo",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"gettext SUNW_INSTALL_LIBSVC 'Removing obsolete packages and saving modified files'",
""
};

char *do_pkgrm[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	do_pkgrm @ROOT@ @PKG@",
"	logprogress @SEQ@ pkgrm @PKG@",
"fi",
"",
"DryRun",
"pkgrm -M -R @ROOT@ @PKG@",
""
};

char *do_pkgrm_f[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	do_pkgrm_f @ROOT@ @PKG@",
"	logprogress @SEQ@ pkgrm @PKG@",
"fi",
"",
"DryRun",
"pkgrm -F -R @ROOT@ @PKG@",
""
};

char *rename_file[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	rename_file @DIR@ @FILE@ @VER@",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun @DIR@ @FILE@ @VER@",
"gettext SUNW_INSTALL_LIBSVC '$00$01: existing file renamed to $00$01:$02'",
""
};

char *do_rm_fr[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	echo rm -fr ${base}@DIR@",
"	rm -fr ${base}@DIR@",
"	logprogress @SEQ@ rmdir @DIR@",
"fi",
"",
"DryRun",
"rm -fr ${base}@DIR@",
""
};

char *remove_template[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	rmtemplate=@DIR@",
"	eval echo `gettext SUNW_INSTALL_LIBSVC 'Removing $rmtemplate:'`",
"	rm -fr ${base}@DIR@",
"	logprogress @SEQ@ rm_template @DIR@",
"fi",
"",
"DryRun",
"rm -fr ${base}@DIR@",
""
};

char *move_template[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	mv ${base}/@OLDDIR@ ${base}/export/root/templates/@NEWSVC@/@PKG@_@VER@_@ARCH@",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"mv ${base}/@OLDDIR@ ${base}/export/root/templates/@NEWSVC@/@PKG@_@VER@_@",
"@ARCH@",
""
};

char *do_rm[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	echo rm -f ${base}@ROOT@@FILE@",
"	rm -f ${base}@ROOT@@FILE@",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"rm -f ${base}@ROOT@@FILE@",
""
};

char *do_removef[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	do_removef @ROOT@ @PKG@",
"	logprogress @SEQ@ removef @PKG@",
"fi",
"",
"DryRun",
"removef @ROOT@ @PKG@",
""
};

char *spool_pkg[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	pkg=@PKG@",
"	eval echo `gettext SUNW_INSTALL_LIBSVC 'Transferring $pkg package'`",
"	mkdir ${base}@SPOOLDIR@",
"	(cd @MEDIA@; tar cf - @PKG@ | (cd ${base}@SPOOLDIR@; tar xf -) )",
"	logprogress @SEQ@ spool_pkg @PKG@",
"fi",
"",
"DryRun @PKG@ @SPOOLDIR@",
"gettext 'Transferring $00 package to $01'",
""
};

char *echo_INST_RELEASE[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"   if [ ! -h ${base}/@ROOT@/var/sadm/softinfo/INST_RELEASE ]; then",
"	rm -f ${base}/@ROOT@/var/sadm/softinfo/INST_RELEASE",
"   fi",
"   echo \"OS=@OS@\" > ${base}/@ROOT@@INST_REL_PATH@",
"   echo \"VERSION=@VERSION@\" >> ${base}/@ROOT@@INST_REL_PATH@",
"   echo \"REV=@REVISION@\" >> ${base}/@ROOT@@INST_REL_PATH@",
"   chmod 644 ${base}/@ROOT@@INST_REL_PATH@",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"echo \"OS=@OS@\" > ${base}/@ROOT@@INST_REL_PATH@",
"echo \"VERSION=@VERSION@\" >> ${base}/@ROOT@@INST_REL_PATH@",
"echo \"REV=@REVISION@\" >> ${base}/@ROOT@@INST_REL_PATH@",
""
};

char *echo_softinfo[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"    rm -f ${base}@SERVICE_PATH@@OS@_2.*",
"    rm -f ${base}/var/sadm/softinfo/@OS@_2.*",
"    echo \"OS=@OS@\" > ${base}@SERVICE_PATH@@OS@_@VERSION@",
"    echo \"VERSION=@VERSION@\" >> ${base}@SERVICE_PATH@@OS@_@VERSION@",
"    echo \"REV=@REVISION@\" >> ${base}@SERVICE_PATH@@OS@_@VERSION@",
"    chmod 644 ${base}@SERVICE_PATH@@OS@_@VERSION@",
"    logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"echo \"OS=@OS@\" > ${base}@SERVICE_PATH@@OS@_@VERSION@",
"echo \"VERSION=@VERSION@\" >> ${base}@SERVICE_PATH@@OS@_@VERSION@",
"echo \"REV=@REVISION@\" >> ${base}@SERVICE_PATH@@OS@_@VERSION@",
""
};

char *touch_reconfig[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	touch ${base}/reconfigure",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"touch ${base}/reconfigure",
""
};

char *rm_tmp[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	rm /tmp/*.$$",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun",
""
};

char *umount_cmd[] = {
"	umount @MNTDEV@",
"",
"DryRun",
"umount @MNTDEV@",
""
};

char *rm_service[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	rm -fr ${base}/export/@PRODVER@",
"	rm -fr ${base}/export/exec/@PRODVER@_*",
"	rm -fr ${base}/export/exec/kvm/@PRODVER@_*",
"	rm -fr ${base}/export/share/@PRODVER@",
"	rm -fr ${base}/export/root/templates/@PRODVER@",
"	rm -f ${base}/var/sadm/system/admin/services/@PRODVER@",
"	rm -f ${base}/var/sadm/softinfo/@PRODVER@",
"	rmdir ${base}/export/root/templates > /dev/null 2>&1",
"	rmdir ${base}/export/root > /dev/null 2>&1",
"	rmdir ${base}/export/share> /dev/null 2>&1",
"	rmdir ${base}/export/exec/kvm > /dev/null 2>&1",
"	rmdir ${base}/export/exec > /dev/null 2>&1",
"	logprogress @SEQ@ remove_svc @PRODVER@",
"fi",
"",
"DryRun @PRODVER@",
"gettext SUNW_INSTALL_LIBSVC 'Remove service $00'",
""
};

char *mv_whole_svc[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	(cd ${base}/export",
"	rm -f ./@OLD@/usr_*",
"	rm -f ./@OLD@/usr.kvm_*",
"	if [ -d ./@OLD@ ] ; then",
"		mv ./@OLD@ ./@NEW@",
"	fi",
"	if [ -h ./share/@OLD@ -o -d ./share/@OLD@ ] ; then",
"		mv ./share/@OLD@ ./share/@NEW@",
"	fi",
"	if [ ! -d ./root ] ; then",
"		mkdir ./root",
"	fi",
"	if [ ! -d ./root/templates ] ; then",
"		mkdir ./root/templates",
"	fi",
"	if [ ! -d ./root/templates/@NEW@ ] ; then",
"		mkdir ./root/templates/@NEW@",
"	fi",
"	)",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun @OLD@ @NEW@",
"gettext SUNW_INSTALL_LIBSVC 'Move service $00 to $01'",
""
};

char *mv_isa_svc[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	(cd ${base}/export",
"	if [ -d ./exec/@OLD@_@PARCH@.all ] ; then",
"		mv ./exec/@OLD@_@PARCH@.all ./exec/@NEW@_@PARCH@.all",
"	fi",
"	rm -fr ./@NEW@/usr_@PARCH@.all",
"	ln -s ../exec/@NEW@_@PARCH@.all ./@NEW@/usr_@PARCH@.all",
"	)",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"mv ./exec/@OLD@_@PARCH@.all ./exec/@NEW@_@PARCH@.all",
"rm -fr ./@NEW@/usr_@PARCH@.all",
"ln -s ../exec/@NEW@_@PARCH@.all ./@NEW@/usr_@PARCH@.all",
""
};

char *add_varsadm_usr[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	(cd ${base}/export",
"	mkdir ./@SVC@",
"	mkdir ./@SVC@/var",
"	mkdir ./@SVC@/var/sadm",
"	if [ \"postKBI\" = \"@POST_KBI@\" ]; then",
"		mkdir ./@SVC@/var/sadm/system",
"		mkdir ./@SVC@/var/sadm/system/admin",
"		mkdir ./@SVC@/var/sadm/system/admin/services",
"		mkdir ./@SVC@/var/sadm/system/logs",
"		mkdir ./@SVC@/var/sadm/system/data",
"	else",
"		mkdir ./@SVC@/var/sadm/softinfo",
"	fi",
"	mkdir ./@SVC@/var/sadm/install_data",
"	if [ ! -d ./exec ] ; then",
"		mkdir ./exec",
"	fi",
"	if [ ! -d ./share ] ; then",
"		mkdir ./share",
"	fi",
"	if [ ! -d ./root ] ; then",
"		mkdir ./root",
"	fi",
"	if [ ! -d ./root/templates ] ; then",
"		mkdir ./root/templates",
"	fi",
"	if [ ! -d ./root/templates/@SVC@ ] ; then",
"		mkdir ./root/templates/@SVC@",
"	fi",
"	)",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun @SVC@",
"gettext SUNW_INSTALL_LIBSVC 'Create ./$00/var/sadm/system directories'",
""
};

char *link_varsadm_usr[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	(cd ${base}/export",
"	mkdir ./@SVC@",
"	mkdir ./@SVC@/var",
"	rm -fr ./@SVC@/var/sadm",
"	ln -s /var/sadm ./@SVC@/var/sadm",
"	if [ ! -d ./exec ] ; then",
"		mkdir ./exec",
"	fi",
"	if [ ! -d ./share ] ; then",
"		mkdir ./share",
"	fi",
"	if [ ! -d ./root ] ; then",
"		mkdir ./root",
"	fi",
"	if [ ! -d ./root/templates ] ; then",
"		mkdir ./root/templates",
"	fi",
"	if [ ! -d ./root/templates/@SVC@ ] ; then",
"		mkdir ./root/templates/@SVC@",
"	fi",
"	)",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"ln -s /var/sadm ${base}/export/@SVC@/var/sadm",
""
};

char *rm_kvm_svc[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"     rm -fr ${base}/export/exec/kvm/@OLD@_@ARCH@",
"     rmdir ${base}/export/exec/kvm > /dev/null 2>&1",
"     logprogress @SEQ@ remove_svc @OLD@_@ARCH@",
"fi",
"",
"DryRun",
"rm -fr ${base}/export/exec/kvm/@OLD@_@ARCH@",
""
};

char *mv_kvm_svc[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	(cd ${base}/export",
"	if [ -d ./exec/kvm/@OLD@_@ARCH@ ] ; then",
"		mv ./exec/kvm/@OLD@_@ARCH@ ./exec/kvm/@NEW@_@ARCH@",
"	fi",
"	rm -fr ./@NEW@/usr.kvm_@ARCH@",
"	ln -s ../exec/kvm/@NEW@_@ARCH@ ./@NEW@/usr.kvm_@ARCH@",
"	)",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"mv ./exec/kvm/@OLD@_@ARCH@ ./exec/kvm/@NEW@_@ARCH@",
"rm -fr ./@NEW@/usr.kvm_@ARCH@",
"ln -s ../exec/kvm/@NEW@_@ARCH@ ./@NEW@/usr.kvm_@ARCH@",
""
};

char *add_kvm_svc[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	(cd ${base}/export",
"	if [ ! -d ./exec/kvm ] ; then",
"		mkdir ./exec/kvm",
"	fi",
"	if [ ! -d ./exec/kvm/@NEW@_@ARCH@ ] ; then",
"		mkdir ./exec/kvm/@NEW@_@ARCH@",
"	fi",
"	rm -fr ./@NEW@/usr.kvm_@ARCH@",
"	ln -s ../exec/kvm/@NEW@_@ARCH@ ./@NEW@/usr.kvm_@ARCH@",
"	)",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun @NEW@ @ARCH@",
"gettext SUNW_INSTALL_LIBSVC 'Add $00_$01 kvm service'",
""
};

char *link_kvm_svc[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	(cd ${base}/export",
"	if [ ! -d ./exec/kvm ] ; then",
"		mkdir ./exec/kvm",
"	fi",
"	if [ ! -d ./exec/kvm/@NEW@_@ARCH@ ] ; then",
"		mkdir ./exec/kvm/@NEW@_@ARCH@",
"	fi",
"	if [ ! -d ./exec/kvm/@NEW@_@ARCH@/usr ] ; then",
"		mkdir ./exec/kvm/@NEW@_@ARCH@/usr",
"	fi",
"	rm -fr ./exec/kvm/@NEW@_@ARCH@/usr/kvm",
"	ln -s /usr/kvm ./exec/kvm/@NEW@_@ARCH@/usr/kvm",
"	rm -fr ./@NEW@/usr.kvm_@ARCH@",
"	ln -s ../exec/kvm/@NEW@_@ARCH@ ./@NEW@/usr.kvm_@ARCH@",
"	)",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun @NEW@ @ARCH@",
"gettext SUNW_INSTALL_LIBSVC 'Link /usr/kvm to appropriate $00_$01 directories'",
""
};

char *move_files_in_contents[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
" if [ -f ${base}/@ROOT@/var/sadm/install/sav.contents ] ; then",
"   mv ${base}/@ROOT@/var/sadm/install/sav.contents ${base}/@ROOT@/var/sadm/install/contents",
" fi",
" cat ${base}/@ROOT@/var/sadm/install/contents | \\",
" sed \\",
" -e 's,^/export/exec/kvm/@OLD@_,/export/exec/kvm/@NEW@_,' \\",
" -e 's,^/export/exec/@OLD@_,/export/exec/@NEW@_,' \\",
" -e '/^#/d'    | sort > ${base}/@ROOT@/var/sadm/install/sav.contents",
" mv $base/@ROOT@/var/sadm/install/sav.contents $base/@ROOT@/var/sadm/install/contents",
" (cd ${base}/@ROOT@/var/sadm/pkg",
" for i in *; do",
"   if [ \"$i\" = \"*\" ] ; then",
"	break",
"   fi",
"   if [ -f $i/pkginfo.upgsav ] ; then",
"      mv $i/pkginfo.upgsav $i/pkginfo",
"   fi",
"   grep '^BASEDIR=/export/exec/' $i/pkginfo >/dev/null 2>&1",
"   if [ $? = 0 ] ; then",
"      sed -e 's,^BASEDIR=/export/exec/@OLD@_,BASEDIR=/export/exec/@NEW@_,' \\",
"         -e 's,^BASEDIR=/export/exec/kvm/@OLD@_,BASEDIR=/export/exec/kvm/@NEW@_,'\\",
"        -e 's,^CLIENT_BASEDIR=/export/exec/@OLD@_,CLIENT_BASEDIR=/export/exec/@NEW@_,' \\",
"	 -e 's,^CLIENT_BASEDIR=/export/exec/kvm/@OLD@_,CLIENT_BASEDIR=/export/exec/kvm/@NEW@_,' $i/pkginfo > \\",
"      $i/pkginfo.upgsav",
"      mv $i/pkginfo.upgsav $i/pkginfo",
"   fi",
" done)",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun @OLD@ @NEW@ @ROOT@",
"gettext SUNW_INSTALL_LIBSVC 'Clean up contents file from $00 to $01, root=$02'",
""
};

char *start_softinfo[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"rm -f ${base}@SERVICE_PATH@@OS@_@VER@",
"touch ${base}@SERVICE_PATH@@OS@_@VER@",
"chmod 644 ${base}@SERVICE_PATH@@OS@_@VER@",
"cat >> ${base}@SERVICE_PATH@@OS@_@VER@ << EOF",
"FORMAT_VERSION=2",
"OS=@OS@",
"VERSION=@VER@",
"REV=@REVISION@",
"",
"DryRun @SERVICE_PATH@ @OS@ @VER@ @REVISION@",
"gettext SUNW_INSTALL_LIBSVC 'Start softinfo $00$01_$02 REV=$03'",
""
};

char *usr_softinfo[] = {
"USR_PATH=@ARCH@.all:/export/exec/@OS@_@VER@_@ARCH@.all/usr",
"",
"DryRun",
"USR_PATH=@ARCH@.all:/export/exec/@OS@_@VER@_@ARCH@.all/usr",
""
};

char *kvm_softinfo[] = {
"KVM_PATH=@ARCH@:/export/exec/kvm/@OS@_@VER@_@ARCH@/usr/kvm",
"",
"DryRun",
"KVM_PATH=@ARCH@:/export/exec/kvm/@OS@_@VER@_@ARCH@/usr/kvm",
""
};

char *root_softinfo[] = {
"SPOOLED_ROOT=@ARCH@:@PATH@",
"ROOT=@ARCH@:@PKG@,@SIZE@,@VERSION@",
"",
"DryRun",
"SPOOLED_ROOT=@ARCH@:@PATH@",
"ROOT=@ARCH@:@PKG@,@SIZE@,@VERSION@",
""
};

char *locale_softinfo[] = {
"LOCALE=@ARCH@:@LOC@",
"",
"DryRun",
"LOCALE=@ARCH@:@LOC@",
""
};

char *rm_softinfo[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	rm -f ${base}/var/sadm/softinfo/@OLD@",
"	rm -f ${base}@SERVICE_PATH@@OLD@",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"rm -f ${base}/var/sadm/softinfo/@OLD@",
"rm -f ${base}@SERVICE_PATH@@OLD@",
""
};

char *rm_svc_dfstab[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"    if [ -f ${base}/etc/dfs/dfstab ] ; then",
"	cat ${base}/etc/dfs/dfstab | \\",
"	   sed -e '/export\\/exec\\/@NAME@_[^_\\.][^_\\.]*\\.all\\/usr$/d' \\",
"	       -e '/export\\/exec\\/kvm\\/@NAME@_[^_\\.][^_\\.]*\\.[^\\/]*\\/usr\\/kvm/d' \\",
"	       -e '/export\\/share\\/@NAME@[ 	]*$/d' > /tmp/tmp.$$",
"	   mv /tmp/tmp.$$ ${base}/etc/dfs/dfstab",
"    fi",
"    logprogress @SEQ@ none",
"fi",
"",
"DryRun @NAME@",
"gettext SUNW_INSTALL_LIBSVC 'Remove $00 from etc/dfs/dfstab'",
""
};

char *add_usr_svc_dfstab[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"    echo share -F nfs -o ro /export/exec/@NAME@_@ISA@.all/usr >> ${base}/etc/dfs/dfstab",
"    logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"share /export/exec/@NAME@_@ISA@.all/usr",
""
};

char *sed_dfstab_usr[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"    if [ -f ${base}/etc/dfs/dfstab ] ; then",
"	cat ${base}/etc/dfs/dfstab | \\",
"	sed -e 's,/@OLD@_@ISA@.all/usr,/@NEW@_@ISA@.all/usr,' > /tmp/tmp.$$",
"	mv /tmp/tmp.$$ ${base}/etc/dfs/dfstab",
"    fi",
"    logprogress @SEQ@ none",
"fi",
"",
"DryRun @OLD@ @NEW@ @ISA@",
"gettext SUNW_INSTALL_LIBSVC 'Change $00_$02 to $01_$02 in etc/dfs/dfstab'",
""
};

char *add_kvm_svc_dfstab[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"    echo share -F nfs -o ro /export/exec/kvm/@NAME@_@ARCH@/usr/kvm >> \\",
"        ${base}/etc/dfs/dfstab",
"    logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"share /export/exec/kvm/@NAME@_@ARCH@/usr/kvm",
""
};

char *share_usr_svc_dfstab[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"    share -F nfs -o ro /export/exec/@NAME@_@PARCH@.all/usr > /dev/null 2>&1",
"    logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"share -F nfs -o ro /export/exec/@NAME@_@PARCH@.all/usr",
""
};

char *share_kvm_svc_dfstab[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"    share -F nfs -o ro /export/exec/kvm/@NAME@_@ARCH@/usr/kvm > /dev/null 2>&1",
"    logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"share -F nfs -o ro /export/exec/kvm/@NAME@_@ARCH@/usr/kvm",
""
};

/*
 * DVB 5/14/93
 * Make both types of directories, since we are not yet sure what the arch
 * will be. This doesn't really hurt anything.
 */
char *init_inetboot_dir[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"       if [ ! -d ${base}/tftpboot ] ; then",
"		mkdir ${base}/tftpboot",
"		ln -s . ${base}/tftpboot/tftpboot",
"	fi",
"       if [ ! -d ${base}/rplboot ] ; then",
"		mkdir ${base}/rplboot",
"	fi",
"    logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"gettext SUNW_INSTALL_LIBSVC 'Make network boot directories'",
""
};

char *rm_inetboot[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	rm -f ${base}/tftpboot/inetboot.*.@SVCPROD@[._]@SVCVER@",
"	rm -f ${base}/rplboot/inetboot.*.@SVCPROD@[._]@SVCVER@",
"    logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"rm -f ${base}/*boot/inetboot.*.@SVCPROD@[._]@SVCVER@",
""
};

char *cp_shared_inetboot[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"   inetboot=${base}/usr/platform/@KARCH@/lib/fs/nfs/inetboot",
"   gluedir=${base}/usr/platform/@KARCH@/lib/fs/nfs",
"   if [ ! -f $inetboot ] ; then",
"	inetboot=${base}/usr/lib/fs/nfs/inetboot",
"	gluedir=${base}/usr/lib/fs/nfs/drv.@KARCH@",
"   fi",
"   logprogress @SEQ@ none",
"fi",
"",
"DryRun",
""
};

char *cp_svc_inetboot[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"   inetboot=${base}/export/exec/@SVCPROD@_@SVCVER@_@ARCH@.all/usr/platform/@KARCH@/lib/fs/nfs/inetboot",
"   gluedir=${base}/export/exec/@SVCPROD@_@SVCVER@_@ARCH@.all/usr/platform/@KARCH@/lib/fs/nfs",
"   if [ ! -f $inetboot ] ; then",
"	inetboot=${base}/export/exec/@SVCPROD@_@SVCVER@_@ARCH@.all/usr/lib/fs/nfs/inetboot",
"	gluedir=${base}/export/exec/@SVCPROD@_@SVCVER@_@ARCH@.all/usr/lib/fs/nfs/drv.@KARCH@",
"   fi",
"    logprogress @SEQ@ none",
"fi",
"",
"DryRun",
""
};

char *cp_inetboot[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"  do_install_inetboot @BOOTDIR@ @KARCH@ @SVCPROD@ @SVCVER@",
"  logprogress @SEQ@ none",
"fi",
"",
"DryRun @BOOTDIR@ @KARCH@ @SVCPROD@ @SVCVER@",
"gettext SUNW_INSTALL_LIBSVC 'Install inetboot $00 $01 $02 $03'",
""
};

char *sed_vfstab[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"    cat ${base}/@CLIENTROOT@/etc/vfstab | \\",
"    sed -e 's,/@OLD@_@ARCH@.all,/@NEW@_@ARCH@.all,' \\",
"        -e 's,/@OLD@_@ARCH@.@KARCH@,/@NEW@_@ARCH@.@KARCH@,' \\",
"        -e 's,/@OLD@[ 	],/@NEW@	,' > /tmp/tmp.$$",
"    mv /tmp/tmp.$$ ${base}/@CLIENTROOT@/etc/vfstab",
"    logprogress @SEQ@ none",
"fi",
"",
"DryRun @CLIENTROOT@ @OLD@ @NEW@ @ARCH@ @KARCH@",
"gettext SUNW_INSTALL_LIBSVC 'Update etc/vfstab from $01 to $02'",
""
};

char *sed_vfstab_rm_kvm[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"    cat ${base}/@CLIENTROOT@/etc/vfstab | \\",
"    sed -e '/\\/usr\\/kvm/d' > /tmp/tmp.$$",
"    mv /tmp/tmp.$$ ${base}/@CLIENTROOT@/etc/vfstab",
"    logprogress @SEQ@ none",
"fi",
"",
"DryRun @CLIENTROOT@",
"gettext SUNW_INSTALL_LIBSVC 'Update $00 etc/vfstab'",
""
};

char *touch_client_reconfigure[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	touch ${base}/@CLIENTROOT@/reconfigure",
"    logprogress @SEQ@ none",
"fi",
"",
"DryRun",
""
};

char *upgrade_client_inetboot[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
" (cd ${base}/@BOOTDIR@;",
" for i in @SEARCHFILE@ @SEARCHFILE@.*; do",
"	[ ! -h $i ] && continue;",
"	rm -f $i",
"	ln -s inetboot.@KARCH@.@SVCPROD@_@SVCVER@ $i",
" done)",
" logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"ln -s inetboot.@KARCH@.@SVCPROD@_@SVCVER@ @SEARCHFILE@ ...etc.",
""
};

char *remove_restart_files[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	rm -f $restart $restartbkup",
"fi",
"",
"DryRun",
""
};

char *exit_ok[] = {
"exit $EXIT_CODE",
"",
"DryRun",
""
};

char *remove_coalesce[] = {
"	rm -f $coalesce",
"",
"DryRun",
""
};

char *print_cleanup_msg[] = {
"echo",
"gettext SUNW_INSTALL_LIBSVC 'The messages printed to the screen by this upgrade have been saved to:'; echo '\\n'",
"echo \"	${base}@UPGRADE_LOG@\\n\"",
"gettext  SUNW_INSTALL_LIBSVC 'After this system is rebooted, the upgrade log can be found in the file:'; echo '\\n'",
"echo '	@UPGRADE_LOG@\\n\\n'",
"if [ -f $failedpkgs ]; then",
"	gettext SUWN_INSTALL_LIBSVC 'The following packages failed to install correctly'",
"	echo '\\n\\n'",
"	cat $failedpkgs",
"	chmod 444 $failedpkgs",
"fi",
"if [ $cleanup_needed = 1 ] ; then",
"	gettext SUNW_INSTALL_LIBSVC 'Please examine the file:'; echo '\\n'",
"	echo  \"	${base}@UPGRADE_CLEANUP@\\n\"",
"	gettext SUNW_INSTALL_LIBSVC 'It contains a list of actions that may need to be performed to complete\\nthe upgrade.  After this system is rebooted, this file can be found at:'; echo '\\n'",
"	echo  '	@UPGRADE_CLEANUP@\\n'",
"	gettext SUNW_INSTALL_LIBSVC 'After performing any necessary cleanup actions, the system should\\nbe rebooted.'; echo",
"	# ",
"	# move the new upgrade_cleanup to a dated log name and then create ",
"	# the necessary symbolic links ",
"	# ",
"	",
"	date_time=`templates_date_time ${base}/var/sadm/system/data/upgrade_cleanup ${base}/var/sadm/system/data/upgrade_cleanup`",
"	mv ${base}/var/sadm/system/data/upgrade_cleanup ${base}/var/sadm/system/data/upgrade_cleanup_${date_time}",
"	ln -s upgrade_cleanup_${date_time} ${base}/var/sadm/system/data/upgrade_cleanup ",
"else",
"	rm -f $coalesce",
"	gettext SUNW_INSTALL_LIBSVC 'Please reboot the system.'; echo",
"fi",
"",
"DryRun",
""
};

char *remove_patch[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	remove_patch @ROOT@ @PATCHID@",
"	logprogress @SEQ@ remove_patch @PATCHID@",
"fi",
"",
"DryRun @ROOT@ @PATCHID@",
"gettext SUNW_INSTALL_LIBSVC 'Removing patch $00 $01 from the system.'",
""
};

char *rm_template_dir[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	rm -fr ${base}/export/root/templates/@SVC@",
"	logprogress @SEQ@ rm_template_dir @SVC@",
"fi",
"",
"DryRun",
"rm -rf ${base}/export/root/templates/@SVC@",
""
};

char *write_CLUSTER[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	rm -f ${base}/@ROOT@/var/sadm/install_data/CLUSTER",
"	rm -f ${base}/@ROOT@@CLUSTER_PATH@",
"	echo CLUSTER=@CLUSTER@ > ${base}/@ROOT@@CLUSTER_PATH@",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"CLUSTER=@CLUSTER@ > ${base}/@ROOT@@CLUSTER_PATH@",
""
};

char *write_clustertoc[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	rm -f ${base}/@ROOT@/var/sadm/install_data/.clustertoc",
"	rm -f ${base}/@ROOT@@CLUSTERTOC_PATH@",
"	cp @TOC@ ${base}/@ROOT@@CLUSTERTOC_PATH@",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"cp @TOC@ ${base}/@ROOT@@CLUSTERTOC_PATH@",
""
};

char *start_rmlist[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"cat > /tmp/rmlist.$$ << EOF",
"",
"DryRun",
"gettext SUNW_INSTALL_LIBSVC 'Removing the following files'",
""
};

char *addto_rmlist[] = {
"@FILE@",
"",
"DryRun",
"@FILE@",
""
};

char *end_rmlist[] = {
"EOF",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun",
""
};

char *log_file_diff[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	log_file_diff @ERR@ @FILE@ @ARG3@ @ARG4@",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"log_file_diff @ERR@ @FILE@ @ARG3@ @ARG4@",
""
};

char *copy_ppc_vof[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	vof=/platform/`uname -i`/openfirmware.x41",
"	if [ -f /tmp/root/$vof ] ; then",
"		rm -f $base/$vof",
"		echo cp /tmp/root/$vof $base/$vof",
"		cp /tmp/root/$vof $base/$vof",
"	fi",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"cp /tmp/root/platform/<UNAME>/openfirmware.x41 $base/platform/<UNAME>/openfirmware.x41",
""
};

char *gen_installboot_cmd[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	(cd $rbase",
"	isa=`uname -p`",
"	uname -i >/dev/null 2>&1",
"	if [ $? = 0 ] ; then",
"	    platform=`uname -i`",
"	    bootblk=$base/usr/platform/$platform/lib/fs/ufs/bootblk",
"	    if [ ! -f $bootblk ] ; then",
"		bootblk=$base/usr/platform/`uname -m`/lib/fs/ufs/bootblk",
"		if [ ! -f $bootblk ] ; then",
"		    bootblk=$base/usr/lib/fs/ufs/bootblk",
"		fi",
"	    fi",
"	    if [ ! -f $bootblk ] ; then",
"	    	bootblk=/usr/platform/$platform/lib/fs/ufs/bootblk",
"		if [ ! -f $bootblk ] ; then",
"		    bootblk=/usr/platform/`uname -m`/lib/fs/ufs/bootblk",
"		    if [ ! -f $bootblk ] ; then",
"			bootblk=/usr/lib/fs/ufs/bootblk",
"		    fi",
"		fi",
"	    fi",
"	    if [ \"$isa\" = \"i386\" ] ; then",
"	        pboot=$base/usr/platform/$platform/lib/fs/ufs/pboot",
"	        if [ ! -f $pboot ] ; then",
"		    pboot=$base/usr/platform/`uname -m`/lib/fs/ufs/pboot",
"		    if [ ! -f $pboot ] ; then",
"		        pboot=$base/usr/lib/fs/ufs/pboot",
"		    fi",
"	        fi",
"	        if [ ! -f $pboot ] ; then",
"		    pboot=/usr/platform/$platform/lib/fs/ufs/pboot",
"		    if [ ! -f $pboot ] ; then",
"			pboot=/usr/platform/`uname -m`/lib/fs/ufs/pboot",
"			if [ ! -f $pboot ] ; then",
"			    pboot=/usr/lib/fs/ufs/pboot",
"			fi",
"		    fi",
"	        fi",
"	    fi",
"	else",
"	    bootblk=$base/usr/lib/fs/ufs/bootblk",
"	    if [ ! -f $bootblk ]; then",
"		bootblk=/usr/lib/fs/ufs/bootblk",
"	    fi",
"	    pboot=$base/usr/lib/fs/ufs/pboot",
"	    if [ ! -f pboot ]; then",
"		pboot=/usr/lib/fs/ufs/pboot",
"	    fi",
"	fi",
"	if [ \"$isa\" = \"sparc\" ] ; then",
"	    echo /usr/sbin/installboot $bootblk @RAWROOT@",
"	    /usr/sbin/installboot $bootblk @RAWROOT@",
"	elif [ \"$isa\" = \"i386\" ] ; then",
"	    echo /usr/sbin/installboot $pboot $bootblk @RAWROOTS2@",
"	    /usr/sbin/installboot $pboot $bootblk @RAWROOTS2@",
"	elif [ \"$isa\" = \"ppc\" ] ; then",
"	  vof=$base/platform/`uname -i`/openfirmware.x41",
"	  if [ -f $vof ] ; then",
"	    echo /usr/sbin/installboot -f $vof $bootblk @RAWROOTS2@",
"	    /usr/sbin/installboot -f $vof $bootblk @RAWROOTS2@",
"	  else",
"	    echo /usr/sbin/installboot $bootblk @RAWROOTS2@",
"	    /usr/sbin/installboot $bootblk @RAWROOTS2@",
"	  fi",
"	else",
"	    echo Unknown instruction set architecture",
"	fi)",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun @RAWROOT@ @RAWROOTS2@",
"gettext SUNW_INSTALL_LIBSVC 'installboot $00 (SPARC) or $01'",
""
};

char *start_perm_restores[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"",
"DryRun",
""
};

char *chmod_file[] = {
"/bin/ls -d $base@DIR@@FILE@ >/dev/null 2>&1",
"if [ $? = 0 ] ; then chmod @MODE@ $base@DIR@@FILE@; fi",
"",
"DryRun",
"chmod @MODE@ $base@DIR@@FILE@",
""
};

char *chown_file[] = {
"/bin/ls -d $base@DIR@@FILE@ >/dev/null 2>&1",
"if [ $? = 0 ] ; then chown @OWNER@ $base@DIR@@FILE@; fi",
"",
"DryRun",
"chown @OWNER@ $base@DIR@@FILE@",
""
};

char *chgrp_file[] = {
"/bin/ls -d $base@DIR@@FILE@ >/dev/null 2>&1",
"if [ $? = 0 ] ; then chgrp @GROUP@ $base@DIR@@FILE@; fi",
"",
"DryRun",
"chgrp @GROUP@ $base@DIR@@FILE@",
""
};

char *end_perm_restores[] = {
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun",
""
};

char *link_usr_svc[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	(cd ${base}/export",
"	if [ ! -d ./exec/@SVC@_@ISA@.all ] ; then",
"		mkdir ./exec/@SVC@_@ISA@.all",
"	fi",
"	rm -fr ./exec/@SVC@_@ISA@.all/usr",
"	rm -fr ./@SVC@/usr_@ISA@.all",
"	ln -s /usr ./exec/@SVC@_@ISA@.all/usr",
"	ln -s ../exec/@SVC@_@ISA@.all ./@SVC@/usr_@ISA@.all",
"	if [ \\( ! -d ./share/@SVC@ \\) -a \\( ! -h ./share/@SVC@ \\) ] ; then",
"		rm -fr ./share/@SVC@",
"		ln -s /export/exec/@SVC@_@ISA@.all/usr/share ./share/@SVC@",
"	fi",
"	)",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"ln -s /usr ./exec/@SVC@_@ISA@.all/usr ...etc.",
""
};

char *add_usr_svc[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	(cd ${base}/export",
"	if [ ! -d ./exec/@SVC@_@ISA@.all ] ; then",
"		mkdir ./exec/@SVC@_@ISA@.all",
"	fi",
"	rm -fr ./@SVC@/usr_@ISA@.all",
"	ln -s ../exec/@SVC@_@ISA@.all ./@SVC@/usr_@ISA@.all",
"	if [ \\( ! -d ./share/@SVC@ \\) -a \\( ! -h ./share/@SVC@ \\) ] ; then",
"		rm -fr ./share/@SVC@",
"		ln -s /export/exec/@SVC@_@ISA@.all/usr/share ./share/@SVC@",
"	fi",
"	)",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun",
"ln -s ../exec/@SVC@_@ISA@.all ./@SVC@/usr_@ISA@.all",
""
};

char *mk_varsadm_dirs[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	mkdir -m 755 -p $base/@CLIENTROOT@/var/sadm/system/admin/services >/dev/null 2>&1",
"	mkdir -m 755 -p $base/@CLIENTROOT@/var/sadm/system/logs >/dev/null 2>&1",
"	mkdir -m 755 -p $base/@CLIENTROOT@/var/sadm/system/data >/dev/null 2>&1",
"	chgrp -f -R sys $base/@CLIENTROOT@/var/sadm/system",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun @CLIENTROOT@",
"gettext SUNW_INSTALL_LIBSVC 'Create $00/var/sadm/system directories'",
""
};

char *mv_varsadm_files[] = {
"if [ @SEQ@ -gt $resumecnt ] ; then",
"	(cd ${base}/@CLIENTROOT@/var/sadm",
"	if [ -h install_data/install_log ] ; then",
"		rm -f install_data/install_log",
"	fi",
"	if [ -f install_data/install_log ] ; then",
"		mv install_data/install_log system/logs/install_log",
"	fi",
"	if [ -f system/admin/upgrade_script ] ; then",
"		date_time=`templates_date_time system/admin/upgrade_script system/admin/upgrade_script`",
"		mv system/admin/upgrade_script system/admin/upgrade_script_${date_time}",
"		chmod 644 system/admin/upgrade_script_${date_time}",
"		ln -s upgrade_script_${date_time} system/admin/upgrade_script",
"	fi",
"	",
"	[ ! -h install_data/upgrade_space_required ] && rm -f install_data/upgrade_space_required",
"	)",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun @CLIENTROOT@",
"gettext SUNW_INSTALL_LIBSVC 'Move $00/var/sadm/system directories'",
""
};

char *end_softinfo[] = {
"EOF",
"	logprogress @SEQ@ none",
"fi",
"",
"DryRun",
""
};
