#
#ident	"@(#)Makefile	1.4	93/01/14 SMI"
#
# Copyright (c) 1990 by Sun Microsystems, Inc.
#
# cmd/adb/sparc/kadb/sun4c/Makefile
#
# The common makefile does all the work; this makefile is here to give the NSE
# a private place to record dependencies.
#

# this deliberately avoids macro names ARCH and KERNARCH for local control
KARCH= sun4c
MMU= sunmmu

include ../Makefile.com
