#
#
#ident "@(#)Makefile 1.7 96/07/24"
#
#
include ../../../../Makefile.cmd

HELPTYPE = reference

HELPFILES = Reference	\
	allocate.r.hlp \
	bootdev.r.hlp \
	bootdisk.r.hlp \
	constraints.r.hlp \
	filechanges.r.hlp \
	glossary.r.hlp \
	mount.r.hlp \
	selectdisk.r.hlp \
	selectmedia.r.hlp \
	spotcustdisk.r.hlp \
	spotdiskprops.r.hlp \
	spotpreserve.r.hlp \
	spotseldisk.r.hlp \
	spotserverexp.r.hlp \
	spotsoft_cust.r.hlp \
	version.r.hlp

all clean clobber:

install: ${ROOTHDIR} ${ROOTHELPFILES}

include ../../../../Makefile.targ
