#
#ident	"@(#)Makefile	1.3	94/11/04 SMI"
#
# Copyright (c) 1994 by Sun Microsystems, Inc.
#
# uts/adb/ppc/Makefile
#

ADB_BASE_DIR	= ..
ISADIR		= .
COMMONDIR	= $(ADB_BASE_DIR)/common
SYSDIR		= $(ADB_BASE_DIR)/..

SRCS +=

include	$(COMMONDIR)/Makefile.com
