/*
 * Copyright (c) 1994 by Sun Microsystems, Inc.
 * All rights reserved.
 */

#pragma	ident	"@(#)sysman_codes.h	1.13	95/08/22 SMI"

#ifndef _SYSMAN_CODES_H
#define _SYSMAN_CODES_H


/* Generic return failures */

#define SYSMAN_SUCCESS		0
#define SYSMAN_INFO		1
#define SYSMAN_FAILURE		-1

#define SYSMAN_SECURITY_ERR	-2	/* denied, you're not an admin */

#define SYSMAN_BAD_INPUT	-11
#define SYSMAN_MALLOC_ERR	-12


/* User Mgr return codes */

#define SYSMAN_USER_FAILED		SYSMAN_FAILURE
#define SYSMAN_USER_NO_USER		-50
#define SYSMAN_USER_NO_PASSWD		-51
#define SYSMAN_USER_BAD_GROUP		-52
#define SYSMAN_USER_BAD_HOME		-53
#define SYSMAN_USER_ADD_FAILED		-54
#define SYSMAN_USER_DEL_FAILED		-55
#define SYSMAN_USER_MOD_FAILED		-56
#define SYSMAN_USER_GET_FAILED		-57
#define SYSMAN_USER_HOME_DIR_FAILED	-58
#define SYSMAN_USER_GROUP_FAILED	-59


/* Group Mgr return codes */

#define SYSMAN_GROUP_FAILED		SYSMAN_FAILURE
#define SYSMAN_GROUP_ADD_FAILED		-60
#define SYSMAN_GROUP_DEL_FAILED		-61
#define SYSMAN_GROUP_MOD_FAILED		-62
#define SYSMAN_GROUP_GET_FAILED		-63


/* Host Mgr return codes */

#define SYSMAN_HOST_FAILED		SYSMAN_FAILURE
#define SYSMAN_HOST_ADD_FAILED		-70
#define SYSMAN_HOST_DEL_FAILED		-71
#define SYSMAN_HOST_MOD_FAILED		-72
#define SYSMAN_HOST_GET_FAILED		-73


/* Printer Mgr return codes */

#define	SYSMAN_PRINTER_FAILED			SYSMAN_FAILURE
#define SYSMAN_PRINTER_NON_UNIQUE		-80
#define SYSMAN_PRINTER_LPADMIN_FAILED		-81
#define SYSMAN_PRINTER_LPSYSTEM_FAILED		-82
#define SYSMAN_PRINTER_LPSTAT_FAILED		-83
#define SYSMAN_PRINTER_ENABLE_FAILED		-84
#define SYSMAN_PRINTER_ACCEPT_FAILED		-85
#define SYSMAN_PRINTER_DISABLE_FAILED		-86
#define SYSMAN_PRINTER_REJECT_FAILED		-87
#define SYSMAN_PRINTER_NETACCESS_FAILED		-88
#define SYSMAN_PRINTER_GET_DEFAULT_FAILED	-89


/* SerialPort Mgr return codes */

#define	SYSMAN_SERIAL_FAILED			SYSMAN_FAILURE
#define	SYSMAN_SERIAL_ERR_IS_CONSOLE		-90
#define	SYSMAN_SERIAL_ERR_START_PORTMON		-91
#define	SYSMAN_SERIAL_ERR_ENABLE_PORTMON	-92
#define	SYSMAN_SERIAL_ERR_EEPROM		-93
#define	SYSMAN_SERIAL_ERR_TTYDEFS		-94
#define	SYSMAN_SERIAL_ERR_TTYADM		-95
#define	SYSMAN_SERIAL_ERR_PMADM			-96
#define	SYSMAN_SERIAL_ERR_NOTFOUND		-97


/* Alias Mgr return codes */

#define SYSMAN_ALIAS_FAILED		SYSMAN_FAILURE
#define SYSMAN_ALIAS_ADD_FAILED		-100
#define SYSMAN_ALIAS_DEL_FAILED		-101
#define SYSMAN_ALIAS_MOD_FAILED		-102
#define SYSMAN_ALIAS_GET_FAILED		-103


/* Job Sched (at, cron) return codes */

#define SYSMAN_JOBSCHED_FAILED			SYSMAN_FAILURE
#define SYSMAN_JOBSCHED_ADD_FAILED		-110
#define SYSMAN_JOBSCHED_DEL_FAILED		-111
#define SYSMAN_JOBSCHED_MOD_FAILED		-112
#define SYSMAN_JOBSCHED_GET_FAILED		-113
#define	SYSMAN_JOBSCHED_OVFLW			-114
#define	SYSMAN_JOBSCHED_PERM_DENIED		-115


/* utility function return codes */

#define	SYSMAN_CONFLICT_NONE			0
#define	SYSMAN_CONFLICT_BOTH_USED		1
#define	SYSMAN_CONFLICT_NAME_USED		2
#define	SYSMAN_CONFLICT_ID_USED			3


#endif /*_SYSMAN_CODES_H */
