#
#ident	"@(#)Makefile	1.2	94/10/12 SMI"
#
# Copyright (c) 1994 by Sun Microsystems, Inc.
#
# lib/libdl/ppc/Makefile

include		../Makefile.com

.KEEP_STATE:

all:		$(DYNLIB) $(LINTLIB)

install:	all $(ROOTDYNLIB) $(ETCDYNLIB) $(ROOTLINKS) \
		$(ROOTLINTLIB)

lint:		$(LINTLIB)

include		../Makefile.targ
