#
#ident	"@(#)Makefile	1.5	94/08/09 SMI"
#
# Copyright (c) 1993 by Sun Microsystems, Inc.
#
# cmd/sgs/gprof/i386/Makefile
#

PROG=		gprof

include 	../Makefile.com

.KEEP_STATE:

all:		$(PROG)

install:	all .WAIT $(ROOTCCSBINPROG) $(ROOTCCSBLURB)

include		../Makefile.targ
