#
#ident	"@(#)Makefile	1.4	96/06/12 SMI"
#
# Copyright (c) 1993, 1996 by Sun Microsystems, Inc.
# All rights reserved.
#

include ../Makefile.com

#DATAFILES += depend
DATAFILES += i.preserve

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
