#
#ident	"@(#)Makefile	1.1	93/11/18 SMI"
#
# Copyright (c) 1993 by Sun Microsystems, Inc.
#
# uts/adb/i386/Makefile
#

ADB_BASE_DIR	= ..
ISADIR		= .
COMMONDIR	= $(ADB_BASE_DIR)/common
SYSDIR		= $(ADB_BASE_DIR)/..

SRCS +=

include	$(COMMONDIR)/Makefile.com
