#
#ident  "@(#)Makefile 1.3     93/05/05 SMI"        /*      */
#
# Copyright (c) 1993 by Sun Microsystems, Inc.
#
# cmd/fs.d/nfs/nfsfind/Makefile

FSTYPE=		nfs
LIBPROG=	nfsfind

SRCS=		nfsfind.sh

include		../../Makefile.fstype
