#
#ident	"@(#)Makefile	1.4	96/03/11 SMI"
#
# Copyright (c) 1995, by Sun Microsystems, Inc.
# All rights reserved.
#
# psm/stand/lib/ppc/prep/Makefile
#
# Platform-specific, but shared between platforms.
#

PLATFORM =	prep
TOPDIR =	../../../../../..
PLATSRC=	uname-i.c

include ../Makefile.com

FRC:

