
/****************************************************************
 *
 * Name      : pfgAllocateSvcQuery_ui.h
 *
 * File is generated by TeleUSE
 * Version : TeleUSE v3.0.2 / Solaris 2.4
 *
 * Copyright (c) 1994-1995 by Sun MicroSystems, Inc.
 * All rights reserved.
 *
 ****************************************************************/

#ifndef _PFGALLOCATESVCQUERY_UI_H_
#define _PFGALLOCATESVCQUERY_UI_H_

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Shell.h>

#include "tu_runtime.h"


/* widget creation functions */

extern Widget tu_baseWindow_widget(char * name,
                                   Widget parent,
                                   Widget ** warr_ret);

extern Widget tu_formWindow_widget(char * name,
                                   Widget parent,
                                   Widget ** warr_ret);

extern Widget tu_twolistWindow_widget(char * name,
                                      Widget parent,
                                      Widget ** warr_ret);

extern Widget tu_allocatesvc_dialog_widget(char * name,
                                           Widget parent,
                                           Widget ** warr_ret);

#define WI_BASEWINDOW 0
#define WI_PANELHELPTEXT 1
#define WI_MESSAGEBOX 2
#define WI_BUTTON1 3
#define WI_BUTTON2 4
#define WI_BUTTON3 5
#define WI_BUTTON4 6
#define WI_BUTTON5 7

#define WI_FORMWINDOW 0
#define WI_PANELHELPTEXT1 1
#define WI_FORM 2
#define WI_MESSAGEBOX1 3
#define WI_BUTTON6 4
#define WI_BUTTON7 5
#define WI_BUTTON8 6
#define WI_BUTTON9 7
#define WI_BUTTON10 8

#define WI_TWOLISTWINDOW 0
#define WI_PANELHELPTEXT2 1
#define WI_FORM1 2
#define WI_AVAILABLELABEL 3
#define WI_AVAILABLESCROLLEDLIST 4
#define WI_BUTTONFORM 5
#define WI_ADDBUTTON 6
#define WI_REMOVEBUTTON 7
#define WI_SELECTEDLABEL 8
#define WI_SELECTEDSCROLLEDLIST 9
#define WI_MESSAGEBOX2 10
#define WI_CONTINUEBUTTON 11
#define WI_GOBACKBUTTON 12
#define WI_EXITBUTTON 13
#define WI_HELPBUTTON 14
#define WI_BUTTON11 15

#define WI_ALLOCATESVC_DIALOG 0
#define WI_PANELHELPTEXT3 1
#define WI_MESSAGEBOX3 2
#define WI_CONTINUEBUTTON1 3
#define WI_GOBACKBUTTON1 4
#define WI_ALLOCATEBUTTON 5
#define WI_EXITBUTTON1 6
#define WI_HELPBUTTON1 7


#endif
