
/****************************************************************
 *
 * Name      : pfgBootDiskSelect_ui.h
 *
 * File is generated by TeleUSE
 * Version : TeleUSE v3.0.2 / Solaris 2.4
 *
 * Copyright (c) 1994-1995 by Sun MicroSystems, Inc.
 * All rights reserved.
 *
 ****************************************************************/

#ifndef _PFGBOOTDISKSELECT_UI_H_
#define _PFGBOOTDISKSELECT_UI_H_

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Shell.h>

#include "tu_runtime.h"


/* widget creation functions */

extern Widget tu_bootdisk_dialog2_widget(char * name,
                                         Widget parent,
                                         Widget ** warr_ret);

extern Widget tu_disk_id1_widget(char * name,
                                 Widget parent,
                                 Widget ** warr_ret);

extern Widget tu_promToggle_widget(char * name,
                                   Widget parent,
                                   Widget ** warr_ret);

#define WI_BOOTDISK_DIALOG2 0
#define WI_PANELHELPTEXT 1
#define WI_DISK_FORM 2
#define WI_BOOTDISKSCROLLEDWINDOW 3
#define WI_FORM_LIST 4
#define WI_LABEL_FORM 5
#define WI_DISK_LABEL 6
#define WI_DEVICE_LABEL 7
#define WI_DEVICES_FORM 8
#define WI_REBOOTBUTTON 9
#define WI_LABEL_FORM1 10
#define WI_EXISTING_LABEL 11
#define WI_EXISTING_VALUE 12
#define WI_MESSAGEBOX 13
#define WI_OKBUTTON 14
#define WI_CANCELBUTTON 15
#define WI_RESETBUTTON 16
#define WI_CUSTOMBUTTON 17
#define WI_HELPBUTTON 18

#define WI_DISK_ID1 0
#define WI_PULLDOWNMENU 1
#define WI_DISKTOGGLE1 2
#define WI_OPTIONMENU 3
#define WI_SOLAR_PART_DEVICE_LABEL 4

#define WI_PROMTOGGLE 0


#endif
