
/****************************************************************
 *
 * Name      : pfgClientQuery_ui.h
 * Creator   : mtraub
 *
 * File is generated by TeleUSE
 * Version : TeleUSE v3.0.1 / Solaris 2.3
 *
 ****************************************************************/

#ifndef _PFGCLIENTQUERY_UI_H_
#define _PFGCLIENTQUERY_UI_H_

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Shell.h>

#include "tu_runtime.h"


/* widget creation functions */

extern Widget tu_initial_client_query_widget(char * name,
                                             Widget parent,
                                             Widget ** warr_ret);

#define WI_INITIAL_CLIENT_QUERY 0
#define WI_QUERY_TEXT 1
#define WI_QUERYMESSAGEBOX 2
#define WI_QUERY_CONTINUE 3
#define WI_QUERY_GOBACK 4
#define WI_QUERY_CANCEL 5
#define WI_QUERY_EXIT 6
#define WI_QUERY_HELP 7


#endif
