
/****************************************************************
 *
 * Name      : pfgDSRSpaceReq_ui.h
 *
 * File is generated by TeleUSE
 * Version : TeleUSE v3.0.2 / Solaris 2.4
 *
 * Copyright (c) 1994-1995 by Sun MicroSystems, Inc.
 * All rights reserved.
 *
 ****************************************************************/

#ifndef _PFGDSRSPACEREQ_UI_H_
#define _PFGDSRSPACEREQ_UI_H_

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Shell.h>

#include "tu_runtime.h"


/* widget creation functions */

extern Widget tu_dsr_space_req_dialog_widget(char * name,
                                             Widget parent,
                                             Widget ** warr_ret);

extern Widget tu_dsr_space_req_filesys_entry_widget(char * name,
                                                    Widget parent,
                                                    Widget ** warr_ret);

#define WI_DSR_SPACE_REQ_DIALOG 0
#define WI_PANELHELPTEXT 1
#define WI_SPACEFORM 2
#define WI_FSCOLUMNLABEL 3
#define WI_SLICECOLUMNLABEL 4
#define WI_CURRSIZECOLUMNLABEL 5
#define WI_REQSIZECOLUMNLABEL 6
#define WI_SPACEREQSCROLLEDWINDOW 7
#define WI_SPACEREQROWCOLUMN 8
#define WI_MESSAGEBOX 9
#define WI_CONTINUEBUTTON 10
#define WI_GOBACKBUTTON 11
#define WI_BUTTON3 12
#define WI_EXITBUTTON 13
#define WI_HELPBUTTON 14

#define WI_DSR_SPACE_REQ_FILESYS_ENTRY 0
#define WI_FSVALUE 1
#define WI_SLICEVALUE 2
#define WI_CURRSIZEVALUE 3
#define WI_REQSIZEVALUE 4


#endif
