
/****************************************************************
 *
 * Name      : pfgDSRFSRedist.c
 *
 * File is generated by TeleUSE
 * Version : TeleUSE v3.0.2 / Solaris 2.4
 *
 * Copyright (c) 1994-1995 by Sun MicroSystems, Inc.
 * All rights reserved.
 *
 ****************************************************************/

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Shell.h>
#include <Xm/Xm.h>
#include <Xm/Protocols.h>

#include "tu_runtime.h"

#include <stdarg.h>

#include <stdio.h>
#include <stdlib.h>
#include "pfgDSRFSRedist_ui.h"


#include <Xm/CascadeB.h>
#include <Xm/CascadeBG.h>
#include <Xm/Form.h>
#include <Xm/Frame.h>
#include <Xm/Label.h>
#include <Xm/MessageB.h>
#include <Xm/MwmUtil.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/ScrolledW.h>
#include <Xm/Separator.h>
#include <Xm/Text.h>
#include <Xm/TextF.h>
#include <Xm/ToggleB.h>


/* Local variables used when selecting screen & display */
static Display * sDisplay = NULL;
static Screen  * sScreen  = NULL;

/* forward declaration */
static void class_init(void);

extern void pfgExit(Widget widget,
                    tu_ccb_arg_p closure,
                    XtPointer calldata);
extern void dsr_fsredist_collapse_cb(Widget widget,
                                     tu_ccb_arg_p closure,
                                     XtPointer calldata);
extern void dsr_fsredist_filter_button_cb(Widget widget,
                                          tu_ccb_arg_p closure,
                                          XtPointer calldata);
extern void dsr_fsredist_continue_cb(Widget widget,
                                     tu_ccb_arg_p closure,
                                     XtPointer calldata);
extern void dsr_fsredist_goback_cb(Widget widget,
                                   tu_ccb_arg_p closure,
                                   XtPointer calldata);
extern void dsr_fsredist_reset_cb(Widget widget,
                                  tu_ccb_arg_p closure,
                                  XtPointer calldata);
extern void dsr_fsredist_option_cb(Widget widget,
                                   tu_ccb_arg_p closure,
                                   XtPointer calldata);
extern void dsr_fsredist_finalsize_cb(Widget widget,
                                      tu_ccb_arg_p closure,
                                      XtPointer calldata);
extern void dsr_fsredist_filter_toggle_value_cb(Widget widget,
                                                tu_ccb_arg_p closure,
                                                XtPointer calldata);
extern void dsr_fsredist_filter_ok_cb(Widget widget,
                                      tu_ccb_arg_p closure,
                                      XtPointer calldata);
extern void dsr_fsredist_filter_cancel_cb(Widget widget,
                                          tu_ccb_arg_p closure,
                                          XtPointer calldata);
extern void dsr_fsredist_collapse_ok_cb(Widget widget,
                                        tu_ccb_arg_p closure,
                                        XtPointer calldata);
extern void dsr_fsredist_collapse_cancel_cb(Widget widget,
                                            tu_ccb_arg_p closure,
                                            XtPointer calldata);
extern void dsr_fsredist_collapse_toggle_value_cb(Widget widget,
                                                  tu_ccb_arg_p closure,
                                                  XtPointer calldata);
extern void unregister_as_dropsite(Widget widget,
                                   tu_ccb_arg_p closure,
                                   XtPointer calldata);
extern void pfgHelp(Widget widget,
                    XtPointer closure,
                    XtPointer calldata);


/****************************************************************
 * get_constraint_widget:
 ****************************************************************/
static Widget get_constraint_widget(Widget child, Widget parent)
{
  Widget w;

  w = child;
  while (XtParent(w) != parent)
    w = XtParent(w);
  return (w);
}


/****************************************************************
 * put_client_data_arg:
 *    set up a client data argument.
 ****************************************************************/
static tu_ccb_arg_p put_client_data_arg(unsigned int cnt, ...)
{
  va_list pvar;
  int i;
  tu_ccb_arg_p rv;

  rv = (tu_ccb_arg_p) malloc(cnt*sizeof(tu_ccb_arg_t));
  if (rv == NULL) return NULL;

  va_start(pvar, cnt);

  for (i=0;i<cnt;i++) {
    rv[i].name = va_arg(pvar, char *);
    rv[i].value = va_arg(pvar, char *);
    rv[i].next = &rv[i+1];
  }
  va_end(pvar);
  rv[cnt-1].next = NULL;
  return rv;
}



/****************************************************************
 * class_init:
 *     Initializes the classes used by the user interface.
 ****************************************************************/
static void class_init(void)
{
  static int inited = 0;

  if (inited != 0)
    return;

  inited = 1;
  sDisplay = sDisplay;

  XtInitializeWidgetClass(xmFormWidgetClass);
  XtInitializeWidgetClass(xmTextWidgetClass);
  XtInitializeWidgetClass(xmLabelWidgetClass);
  XtInitializeWidgetClass(xmTextFieldWidgetClass);
  XtInitializeWidgetClass(xmFrameWidgetClass);
  XtInitializeWidgetClass(xmScrolledWindowWidgetClass);
  XtInitializeWidgetClass(xmRowColumnWidgetClass);
  XtInitializeWidgetClass(xmPushButtonWidgetClass);
  XtInitializeWidgetClass(xmMessageBoxWidgetClass);
  XtInitializeWidgetClass(xmSeparatorWidgetClass);
  XtInitializeWidgetClass(xmToggleButtonWidgetClass);
}



/****************************************************************
 *
 *  Main C code for presentation component
 *
 ****************************************************************/

/**************************************************************
 * tu_dsr_fsredist_dialog_widget:
 **************************************************************/
Widget tu_dsr_fsredist_dialog_widget(char    * name,
                                     Widget    parent,
                                     Widget ** warr_ret)
{
  Arg args[28];
  Widget widget_array[39];
  XtTranslations ttbl;
  int n;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmFormDialog *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  widget_array[WI_DSR_FSREDIST_DIALOG] =
    XmCreateFormDialog(parent, name, args, n);

  /***************** panelhelpText : XmText *****************/
  n = 0;
  XtSetArg(args[n], XmNautoShowCursorPosition, False); n++;
  XtSetArg(args[n], XmNcursorPositionVisible, False); n++;
  XtSetArg(args[n], XmNeditMode, XmMULTI_LINE_EDIT); n++;
  XtSetArg(args[n], XmNtraversalOn, False); n++;
  XtSetArg(args[n], XmNresizeHeight, True); n++;
  XtSetArg(args[n], XmNwordWrap, True); n++;
  XtSetArg(args[n], XmNshadowThickness, 0); n++;
  XtSetArg(args[n], XmNmarginWidth, 18); n++;
  XtSetArg(args[n], XmNmarginHeight, 18); n++;
  XtSetArg(args[n], XmNvalue, "message_text"); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_PANELHELPTEXT] =
    XmCreateText(widget_array[WI_DSR_FSREDIST_DIALOG], "panelhelpText", args, n);

  /***************** fsredistForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_FSREDISTFORM] =
    XmCreateForm(widget_array[WI_DSR_FSREDIST_DIALOG], "fsredistForm", args, n);

  /***************** entrySizeForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_ENTRYSIZEFORM] =
    XmCreateForm(widget_array[WI_FSREDISTFORM], "entrySizeForm", args, n);

  /***************** activeSliceLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_ACTIVESLICELABEL] =
    XmCreateLabel(widget_array[WI_ENTRYSIZEFORM], "activeSliceLabel", args, n);

  /***************** activeSliceTextField : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNeditable, False); n++;
  XtSetArg(args[n], XmNcursorPositionVisible, False); n++;
  XtSetArg(args[n], XmNtraversalOn, False); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_ACTIVESLICETEXTFIELD] =
    XmCreateTextField(widget_array[WI_ENTRYSIZEFORM], "activeSliceTextField", args, n);

  /***************** activeReqSizeLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_ACTIVEREQSIZELABEL] =
    XmCreateLabel(widget_array[WI_ENTRYSIZEFORM], "activeReqSizeLabel", args, n);

  /***************** activeReqSizeTextField : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNeditable, False); n++;
  XtSetArg(args[n], XmNcursorPositionVisible, False); n++;
  XtSetArg(args[n], XmNtraversalOn, False); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_ACTIVEREQSIZETEXTFIELD] =
    XmCreateTextField(widget_array[WI_ENTRYSIZEFORM], "activeReqSizeTextField", args, n);

  /***************** activeCurrSizeLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_ACTIVECURRSIZELABEL] =
    XmCreateLabel(widget_array[WI_ENTRYSIZEFORM], "activeCurrSizeLabel", args, n);

  /***************** activeCurrSizeTextField : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNeditable, False); n++;
  XtSetArg(args[n], XmNcursorPositionVisible, False); n++;
  XtSetArg(args[n], XmNtraversalOn, False); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_ACTIVECURRSIZETEXTFIELD] =
    XmCreateTextField(widget_array[WI_ENTRYSIZEFORM], "activeCurrSizeTextField", args, n);

  /***************** frame : XmFrame *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_FRAME] =
    XmCreateFrame(widget_array[WI_FSREDISTFORM], "frame", args, n);

  /***************** frameForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  widget_array[WI_FRAMEFORM] =
    XmCreateForm(widget_array[WI_FRAME], "frameForm", args, n);

  /***************** slicesForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_SLICESFORM] =
    XmCreateForm(widget_array[WI_FRAMEFORM], "slicesForm", args, n);

  /***************** sliceLabelForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_SLICELABELFORM] =
    XmCreateForm(widget_array[WI_SLICESFORM], "sliceLabelForm", args, n);

  /***************** fsColumnLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_FSCOLUMNLABEL] =
    XmCreateLabel(widget_array[WI_SLICELABELFORM], "fsColumnLabel", args, n);

  /***************** sliceColumnLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_SLICECOLUMNLABEL] =
    XmCreateLabel(widget_array[WI_SLICELABELFORM], "sliceColumnLabel", args, n);

  /***************** vfstabColumnLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_VFSTABCOLUMNLABEL] =
    XmCreateLabel(widget_array[WI_SLICELABELFORM], "vfstabColumnLabel", args, n);

  /***************** currFreeSizeColumnLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_CURRFREESIZECOLUMNLABEL] =
    XmCreateLabel(widget_array[WI_SLICELABELFORM], "currFreeSizeColumnLabel", args, n);

  /***************** spaceNeededColumnLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_SPACENEEDEDCOLUMNLABEL] =
    XmCreateLabel(widget_array[WI_SLICELABELFORM], "spaceNeededColumnLabel", args, n);

  /***************** ALOptionsColumnLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_ALOPTIONSCOLUMNLABEL] =
    XmCreateLabel(widget_array[WI_SLICELABELFORM], "ALOptionsColumnLabel", args, n);

  /***************** finalSizeColumnLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_FINALSIZECOLUMNLABEL] =
    XmCreateLabel(widget_array[WI_SLICELABELFORM], "finalSizeColumnLabel", args, n);

  /***************** slicesScrolledWindow : XmScrolledWindow *****************/
  n = 0;
  XtSetArg(args[n], XmNscrollingPolicy, XmAUTOMATIC); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_SLICESSCROLLEDWINDOW] =
    XmCreateScrolledWindow(widget_array[WI_SLICESFORM], "slicesScrolledWindow", args, n);

  /***************** slicesRowColumn : XmRowColumn *****************/
  widget_array[WI_SLICESROWCOLUMN] =
    XmCreateRowColumn(widget_array[WI_SLICESSCROLLEDWINDOW], "slicesRowColumn", NULL, 0);

  /***************** infoForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_INFOFORM] =
    XmCreateForm(widget_array[WI_FRAMEFORM], "infoForm", args, n);

  /***************** moreButtonsForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_MOREBUTTONSFORM] =
    XmCreateForm(widget_array[WI_INFOFORM], "moreButtonsForm", args, n);

  /***************** collapseButton : XmPushButton *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_COLLAPSEBUTTON] =
    XmCreatePushButton(widget_array[WI_MOREBUTTONSFORM], "collapseButton", args, n);

  /***************** filterButton : XmPushButton *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_FILTERBUTTON] =
    XmCreatePushButton(widget_array[WI_MOREBUTTONSFORM], "filterButton", args, n);

  /***************** totalsForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_TOTALSFORM] =
    XmCreateForm(widget_array[WI_INFOFORM], "totalsForm", args, n);

  /***************** additionalSpaceLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_END); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_ADDITIONALSPACELABEL] =
    XmCreateLabel(widget_array[WI_TOTALSFORM], "additionalSpaceLabel", args, n);

  /***************** allocatedSpaceLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_END); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_ALLOCATEDSPACELABEL] =
    XmCreateLabel(widget_array[WI_TOTALSFORM], "allocatedSpaceLabel", args, n);

  /***************** additionalSpaceValue : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_END); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_ADDITIONALSPACEVALUE] =
    XmCreateLabel(widget_array[WI_TOTALSFORM], "additionalSpaceValue", args, n);

  /***************** allocatedSpaceValue : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_END); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_ALLOCATEDSPACEVALUE] =
    XmCreateLabel(widget_array[WI_TOTALSFORM], "allocatedSpaceValue", args, n);

  /***************** messageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdialogType, XmDIALOG_TEMPLATE); n++;
  XtSetArg(args[n], XmNminimizeButtons, True); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_MESSAGEBOX] =
    XmCreateMessageBox(widget_array[WI_DSR_FSREDIST_DIALOG], "messageBox", args, n);

  /***************** continueButton : XmPushButton *****************/
  widget_array[WI_CONTINUEBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "continueButton", NULL, 0);

  /***************** gobackButton : XmPushButton *****************/
  widget_array[WI_GOBACKBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "gobackButton", NULL, 0);

  /***************** resetButton : XmPushButton *****************/
  widget_array[WI_RESETBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "resetButton", NULL, 0);

  /***************** exitButton : XmPushButton *****************/
  widget_array[WI_EXITBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "exitButton", NULL, 0);

  /***************** helpButton : XmPushButton *****************/
  widget_array[WI_HELPBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "helpButton", NULL, 0);

  /* Terminate the widget array */
  widget_array[38] = NULL;


  /***************** object of type : XmFormDialog *****************/
  n = 0;
  XtSetArg(args[n], XmNinitialFocus, widget_array[WI_CONTINUEBUTTON]); n++;
  XtSetValues(widget_array[WI_DSR_FSREDIST_DIALOG], args, n);


  /***************** panelhelpText : XmText *****************/
  n = 0;
  ttbl = XtParseTranslationTable("#override\n\
~Ctrl ~Meta<BtnDown>:\n\
~Ctrl ~Meta<BtnUp>:");
  XtOverrideTranslations(widget_array[WI_PANELHELPTEXT], ttbl);
  unregister_as_dropsite(widget_array[WI_PANELHELPTEXT],
                         NULL,
                         NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_PANELHELPTEXT], args, n);

  XtManageChild(widget_array[WI_PANELHELPTEXT]);

  /***************** fsredistForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_PANELHELPTEXT]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_MESSAGEBOX]); n++;
  XtSetArg(args[n], XmNtopOffset, 0); n++;
  XtSetArg(args[n], XmNleftOffset, 0); n++;
  XtSetArg(args[n], XmNrightOffset, 0); n++;
  XtSetValues(widget_array[WI_FSREDISTFORM], args, n);


  /***************** entrySizeForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNleftOffset, 10); n++;
  XtSetArg(args[n], XmNrightOffset, 40); n++;
  XtSetValues(widget_array[WI_ENTRYSIZEFORM], args, n);


  /***************** activeSliceLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_ACTIVESLICELABEL], args, n);

  XtManageChild(widget_array[WI_ACTIVESLICELABEL]);

  /***************** activeSliceTextField : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_ACTIVESLICELABEL]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_ACTIVESLICELABEL]); n++;
  XtSetValues(widget_array[WI_ACTIVESLICETEXTFIELD], args, n);

  XtManageChild(widget_array[WI_ACTIVESLICETEXTFIELD]);

  /***************** activeReqSizeLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_ACTIVECURRSIZELABEL]); n++;
  XtSetArg(args[n], XmNrightOffset, 25); n++;
  XtSetValues(widget_array[WI_ACTIVEREQSIZELABEL], args, n);

  XtManageChild(widget_array[WI_ACTIVEREQSIZELABEL]);

  /***************** activeReqSizeTextField : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_ACTIVEREQSIZELABEL]); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_ACTIVEREQSIZELABEL]); n++;
  XtSetValues(widget_array[WI_ACTIVEREQSIZETEXTFIELD], args, n);

  XtManageChild(widget_array[WI_ACTIVEREQSIZETEXTFIELD]);

  /***************** activeCurrSizeLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightOffset, 0); n++;
  XtSetValues(widget_array[WI_ACTIVECURRSIZELABEL], args, n);

  XtManageChild(widget_array[WI_ACTIVECURRSIZELABEL]);

  /***************** activeCurrSizeTextField : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_ACTIVECURRSIZELABEL]); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_ACTIVECURRSIZELABEL]); n++;
  XtSetValues(widget_array[WI_ACTIVECURRSIZETEXTFIELD], args, n);

  XtManageChild(widget_array[WI_ACTIVECURRSIZETEXTFIELD]);
  XtManageChild(widget_array[WI_ENTRYSIZEFORM]);

  /***************** frame : XmFrame *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_ENTRYSIZEFORM]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftOffset, 10); n++;
  XtSetArg(args[n], XmNrightOffset, 10); n++;
  XtSetArg(args[n], XmNtopOffset, 10); n++;
  XtSetValues(widget_array[WI_FRAME], args, n);


  /***************** slicesForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftOffset, 10); n++;
  XtSetArg(args[n], XmNrightOffset, 10); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_INFOFORM]); n++;
  XtSetArg(args[n], XmNbottomOffset, 10); n++;
  XtSetValues(widget_array[WI_SLICESFORM], args, n);


  /***************** sliceLabelForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_SLICELABELFORM], args, n);


  /***************** fsColumnLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_FSCOLUMNLABEL], args, n);

  XtManageChild(widget_array[WI_FSCOLUMNLABEL]);

  /***************** sliceColumnLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_FSCOLUMNLABEL]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_SLICECOLUMNLABEL], args, n);

  XtManageChild(widget_array[WI_SLICECOLUMNLABEL]);

  /***************** vfstabColumnLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_SLICECOLUMNLABEL]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_VFSTABCOLUMNLABEL], args, n);


  /***************** currFreeSizeColumnLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_SLICECOLUMNLABEL]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_CURRFREESIZECOLUMNLABEL], args, n);

  XtManageChild(widget_array[WI_CURRFREESIZECOLUMNLABEL]);

  /***************** spaceNeededColumnLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_CURRFREESIZECOLUMNLABEL]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_SPACENEEDEDCOLUMNLABEL], args, n);

  XtManageChild(widget_array[WI_SPACENEEDEDCOLUMNLABEL]);

  /***************** ALOptionsColumnLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_SPACENEEDEDCOLUMNLABEL]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_ALOPTIONSCOLUMNLABEL], args, n);

  XtManageChild(widget_array[WI_ALOPTIONSCOLUMNLABEL]);

  /***************** finalSizeColumnLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_ALOPTIONSCOLUMNLABEL]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_FINALSIZECOLUMNLABEL], args, n);

  XtManageChild(widget_array[WI_FINALSIZECOLUMNLABEL]);
  XtManageChild(widget_array[WI_SLICELABELFORM]);

  /***************** slicesScrolledWindow : XmScrolledWindow *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_SLICELABELFORM]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SLICESSCROLLEDWINDOW], args, n);

  XtManageChild(widget_array[WI_SLICESROWCOLUMN]);
  XtManageChild(widget_array[WI_SLICESSCROLLEDWINDOW]);
  XtManageChild(widget_array[WI_SLICESFORM]);

  /***************** infoForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftOffset, 10); n++;
  XtSetArg(args[n], XmNrightOffset, 30); n++;
  XtSetArg(args[n], XmNbottomOffset, 10); n++;
  XtSetValues(widget_array[WI_INFOFORM], args, n);


  /***************** moreButtonsForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_MOREBUTTONSFORM], args, n);


  /***************** collapseButton : XmPushButton *****************/
  n = 0;
  XtAddCallback(widget_array[WI_COLLAPSEBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)dsr_fsredist_collapse_cb,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_COLLAPSEBUTTON], args, n);

  XtManageChild(widget_array[WI_COLLAPSEBUTTON]);

  /***************** filterButton : XmPushButton *****************/
  n = 0;
  XtAddCallback(widget_array[WI_FILTERBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)dsr_fsredist_filter_button_cb,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_COLLAPSEBUTTON]); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_COLLAPSEBUTTON]); n++;
  XtSetArg(args[n], XmNleftOffset, 10); n++;
  XtSetValues(widget_array[WI_FILTERBUTTON], args, n);

  XtManageChild(widget_array[WI_FILTERBUTTON]);
  XtManageChild(widget_array[WI_MOREBUTTONSFORM]);

  /***************** totalsForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_MOREBUTTONSFORM]); n++;
  XtSetValues(widget_array[WI_TOTALSFORM], args, n);


  /***************** additionalSpaceLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_ADDITIONALSPACEVALUE]); n++;
  XtSetArg(args[n], XmNrightOffset, 5); n++;
  XtSetValues(widget_array[WI_ADDITIONALSPACELABEL], args, n);

  XtManageChild(widget_array[WI_ADDITIONALSPACELABEL]);

  /***************** allocatedSpaceLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_ADDITIONALSPACELABEL]); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_ADDITIONALSPACELABEL]); n++;
  XtSetArg(args[n], XmNrightOffset, 0); n++;
  XtSetValues(widget_array[WI_ALLOCATEDSPACELABEL], args, n);

  XtManageChild(widget_array[WI_ALLOCATEDSPACELABEL]);

  /***************** additionalSpaceValue : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_ADDITIONALSPACEVALUE], args, n);

  XtManageChild(widget_array[WI_ADDITIONALSPACEVALUE]);

  /***************** allocatedSpaceValue : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_ADDITIONALSPACEVALUE]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_ALLOCATEDSPACEVALUE], args, n);

  XtManageChild(widget_array[WI_ALLOCATEDSPACEVALUE]);
  XtManageChild(widget_array[WI_TOTALSFORM]);
  XtManageChild(widget_array[WI_INFOFORM]);
  XtManageChild(widget_array[WI_FRAMEFORM]);
  XtManageChild(widget_array[WI_FRAME]);
  XtManageChild(widget_array[WI_FSREDISTFORM]);

  /***************** messageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdefaultButton, widget_array[WI_CONTINUEBUTTON]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_MESSAGEBOX], args, n);

  XtAddCallback(widget_array[WI_CONTINUEBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)dsr_fsredist_continue_cb,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_CONTINUEBUTTON]);
  XtAddCallback(widget_array[WI_GOBACKBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)dsr_fsredist_goback_cb,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_GOBACKBUTTON]);
  XtAddCallback(widget_array[WI_RESETBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)dsr_fsredist_reset_cb,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_RESETBUTTON]);
  XtAddCallback(widget_array[WI_EXITBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)pfgExit,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_EXITBUTTON]);
  XtAddCallback(widget_array[WI_HELPBUTTON],
                XmNactivateCallback,
                pfgHelp,
                (XtPointer)"constraints.r");

  XtManageChild(widget_array[WI_HELPBUTTON]);
  XtManageChild(widget_array[WI_MESSAGEBOX]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*39);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*39);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_DSR_FSREDIST_DIALOG]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_DSR_FSREDIST_DIALOG]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_DSR_FSREDIST_DIALOG];
}


/**************************************************************
 * tu_dsr_fsredist_entry_widget:
 **************************************************************/
Widget tu_dsr_fsredist_entry_widget(char    * name,
                                    Widget    parent,
                                    Widget ** warr_ret)
{
  Arg args[17];
  Widget widget_array[17];
  int n;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  widget_array[WI_DSR_FSREDIST_ENTRY] =
    XmCreateForm(parent, name, args, n);

  /***************** frame : XmFrame *****************/
  widget_array[WI_FRAME1] =
    XmCreateFrame(widget_array[WI_DSR_FSREDIST_ENTRY], "frame", NULL, 0);

  /***************** form : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  widget_array[WI_FORM] =
    XmCreateForm(widget_array[WI_FRAME1], "form", args, n);

  /***************** pulldownMenu : XmPulldownMenu *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_PULLDOWNMENU] =
    XmCreatePulldownMenu(widget_array[WI_FORM], "pulldownMenu", args, n);

  /***************** fixedButton : XmPushButton *****************/
  widget_array[WI_FIXEDBUTTON] =
    XmCreatePushButton(widget_array[WI_PULLDOWNMENU], "fixedButton", NULL, 0);

  /***************** moveButton : XmPushButton *****************/
  widget_array[WI_MOVEBUTTON] =
    XmCreatePushButton(widget_array[WI_PULLDOWNMENU], "moveButton", NULL, 0);

  /***************** changeButton : XmPushButton *****************/
  widget_array[WI_CHANGEBUTTON] =
    XmCreatePushButton(widget_array[WI_PULLDOWNMENU], "changeButton", NULL, 0);

  /***************** availableButton : XmPushButton *****************/
  widget_array[WI_AVAILABLEBUTTON] =
    XmCreatePushButton(widget_array[WI_PULLDOWNMENU], "availableButton", NULL, 0);

  /***************** collapseFSButton : XmPushButton *****************/
  widget_array[WI_COLLAPSEFSBUTTON] =
    XmCreatePushButton(widget_array[WI_PULLDOWNMENU], "collapseFSButton", NULL, 0);

  /***************** fsValue : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_BEGINNING); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_FSVALUE] =
    XmCreateLabel(widget_array[WI_FORM], "fsValue", args, n);

  /***************** sliceValue : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_SLICEVALUE] =
    XmCreateLabel(widget_array[WI_FORM], "sliceValue", args, n);

  /***************** vfstabValue : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_VFSTABVALUE] =
    XmCreateLabel(widget_array[WI_FORM], "vfstabValue", args, n);

  /***************** currFreeSizeValue : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_CURRFREESIZEVALUE] =
    XmCreateLabel(widget_array[WI_FORM], "currFreeSizeValue", args, n);

  /***************** spaceNeededValue : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_SPACENEEDEDVALUE] =
    XmCreateLabel(widget_array[WI_FORM], "spaceNeededValue", args, n);

  /***************** ALOptionsMenu : XmOptionMenu *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_ALOPTIONSMENU] =
    XmCreateOptionMenu(widget_array[WI_FORM], "ALOptionsMenu", args, n);

  /***************** finalSizeTextField : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_FINALSIZETEXTFIELD] =
    XmCreateTextField(widget_array[WI_FORM], "finalSizeTextField", args, n);

  /* Terminate the widget array */
  widget_array[16] = NULL;


  /***************** pulldownMenu : XmPulldownMenu *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_PULLDOWNMENU], args, n);

  XtAddCallback(widget_array[WI_FIXEDBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)dsr_fsredist_option_cb,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_FIXEDBUTTON]);
  XtAddCallback(widget_array[WI_MOVEBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)dsr_fsredist_option_cb,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_MOVEBUTTON]);
  XtAddCallback(widget_array[WI_CHANGEBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)dsr_fsredist_option_cb,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_CHANGEBUTTON]);
  XtAddCallback(widget_array[WI_AVAILABLEBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)dsr_fsredist_option_cb,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_AVAILABLEBUTTON]);
  XtAddCallback(widget_array[WI_COLLAPSEFSBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)dsr_fsredist_option_cb,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_COLLAPSEFSBUTTON]);

  /***************** fsValue : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_FSVALUE], args, n);

  XtManageChild(widget_array[WI_FSVALUE]);

  /***************** sliceValue : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_FSVALUE]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_SLICEVALUE], args, n);

  XtManageChild(widget_array[WI_SLICEVALUE]);

  /***************** vfstabValue : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_SLICEVALUE]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_VFSTABVALUE], args, n);


  /***************** currFreeSizeValue : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_SLICEVALUE]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_CURRFREESIZEVALUE], args, n);

  XtManageChild(widget_array[WI_CURRFREESIZEVALUE]);

  /***************** spaceNeededValue : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_CURRFREESIZEVALUE]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_SPACENEEDEDVALUE], args, n);

  XtManageChild(widget_array[WI_SPACENEEDEDVALUE]);

  /***************** ALOptionsMenu : XmOptionMenu *****************/
  n = 0;
  XtSetArg(args[n], XmNsubMenuId, widget_array[WI_PULLDOWNMENU]); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_SPACENEEDEDVALUE]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_ALOPTIONSMENU], args, n);

  XtManageChild(widget_array[WI_ALOPTIONSMENU]);

  /***************** finalSizeTextField : XmTextField *****************/
  n = 0;
  XtAddCallback(widget_array[WI_FINALSIZETEXTFIELD],
                XmNactivateCallback,
                (XtCallbackProc)dsr_fsredist_finalsize_cb,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_ALOPTIONSMENU]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_FINALSIZETEXTFIELD], args, n);

  XtManageChild(widget_array[WI_FINALSIZETEXTFIELD]);
  XtManageChild(widget_array[WI_FORM]);
  XtManageChild(widget_array[WI_FRAME1]);
  XtManageChild(widget_array[WI_DSR_FSREDIST_ENTRY]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*17);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*17);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_DSR_FSREDIST_ENTRY]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_DSR_FSREDIST_ENTRY]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_DSR_FSREDIST_ENTRY];
}


/**************************************************************
 * tu_dsr_fsredist_filter_dialog_widget:
 **************************************************************/
Widget tu_dsr_fsredist_filter_dialog_widget(char    * name,
                                            Widget    parent,
                                            Widget ** warr_ret)
{
  Arg args[29];
  Widget widget_array[21];
  XtTranslations ttbl;
  int n;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmFormDialog *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  widget_array[WI_DSR_FSREDIST_FILTER_DIALOG] =
    XmCreateFormDialog(parent, name, args, n);

  /***************** panelhelpText : XmText *****************/
  n = 0;
  XtSetArg(args[n], XmNautoShowCursorPosition, False); n++;
  XtSetArg(args[n], XmNcursorPositionVisible, False); n++;
  XtSetArg(args[n], XmNeditMode, XmMULTI_LINE_EDIT); n++;
  XtSetArg(args[n], XmNtraversalOn, False); n++;
  XtSetArg(args[n], XmNresizeHeight, True); n++;
  XtSetArg(args[n], XmNwordWrap, True); n++;
  XtSetArg(args[n], XmNshadowThickness, 0); n++;
  XtSetArg(args[n], XmNmarginWidth, 18); n++;
  XtSetArg(args[n], XmNmarginHeight, 18); n++;
  XtSetArg(args[n], XmNvalue, "message_text"); n++;
  widget_array[WI_PANELHELPTEXT1] =
    XmCreateText(widget_array[WI_DSR_FSREDIST_FILTER_DIALOG], "panelhelpText", args, n);

  /***************** separator : XmSeparator *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_SEPARATOR] =
    XmCreateSeparator(widget_array[WI_DSR_FSREDIST_FILTER_DIALOG], "separator", args, n);

  /***************** filterform : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  XtSetArg(args[n], XmNfractionBase, 4); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_FILTERFORM] =
    XmCreateForm(widget_array[WI_DSR_FSREDIST_FILTER_DIALOG], "filterform", args, n);

  /***************** radioLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_RADIOLABEL] =
    XmCreateLabel(widget_array[WI_FILTERFORM], "radioLabel", args, n);

  /***************** radioBox : XmRadioBox *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_RADIOBOX] =
    XmCreateRadioBox(widget_array[WI_FILTERFORM], "radioBox", args, n);

  /***************** allToggle : XmToggleButton *****************/
  widget_array[WI_ALLTOGGLE] =
    XmCreateToggleButton(widget_array[WI_RADIOBOX], "allToggle", NULL, 0);

  /***************** failedFSToggle : XmToggleButton *****************/
  widget_array[WI_FAILEDFSTOGGLE] =
    XmCreateToggleButton(widget_array[WI_RADIOBOX], "failedFSToggle", NULL, 0);

  /***************** vfstabSlicesToggle : XmToggleButton *****************/
  widget_array[WI_VFSTABSLICESTOGGLE] =
    XmCreateToggleButton(widget_array[WI_RADIOBOX], "vfstabSlicesToggle", NULL, 0);

  /***************** nonVfstabSlicesToggle : XmToggleButton *****************/
  widget_array[WI_NONVFSTABSLICESTOGGLE] =
    XmCreateToggleButton(widget_array[WI_RADIOBOX], "nonVfstabSlicesToggle", NULL, 0);

  /***************** sliceNameToggle : XmToggleButton *****************/
  widget_array[WI_SLICENAMETOGGLE] =
    XmCreateToggleButton(widget_array[WI_RADIOBOX], "sliceNameToggle", NULL, 0);

  /***************** mntpntNameToggle : XmToggleButton *****************/
  widget_array[WI_MNTPNTNAMETOGGLE] =
    XmCreateToggleButton(widget_array[WI_RADIOBOX], "mntpntNameToggle", NULL, 0);

  /***************** reLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_RELABEL] =
    XmCreateLabel(widget_array[WI_FILTERFORM], "reLabel", args, n);

  /***************** reTextField : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_RETEXTFIELD] =
    XmCreateTextField(widget_array[WI_FILTERFORM], "reTextField", args, n);

  /***************** messageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdialogType, XmDIALOG_TEMPLATE); n++;
  widget_array[WI_MESSAGEBOX1] =
    XmCreateMessageBox(widget_array[WI_DSR_FSREDIST_FILTER_DIALOG], "messageBox", args, n);

  /***************** okButton : XmPushButton *****************/
  widget_array[WI_OKBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX1], "okButton", NULL, 0);

  /***************** cancelButton : XmPushButton *****************/
  widget_array[WI_CANCELBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX1], "cancelButton", NULL, 0);

  /***************** button3 : XmPushButton *****************/
  widget_array[WI_BUTTON3] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX1], "button3", NULL, 0);

  /***************** button4 : XmPushButton *****************/
  widget_array[WI_BUTTON4] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX1], "button4", NULL, 0);

  /***************** helpButton : XmPushButton *****************/
  widget_array[WI_HELPBUTTON1] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX1], "helpButton", NULL, 0);

  /* Terminate the widget array */
  widget_array[20] = NULL;


  /***************** panelhelpText : XmText *****************/
  n = 0;
  ttbl = XtParseTranslationTable("#override\n\
~Ctrl ~Meta<BtnDown>:\n\
~Ctrl ~Meta<BtnUp>:");
  XtOverrideTranslations(widget_array[WI_PANELHELPTEXT1], ttbl);
  unregister_as_dropsite(widget_array[WI_PANELHELPTEXT1],
                         NULL,
                         NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftOffset, 0); n++;
  XtSetArg(args[n], XmNrightOffset, 0); n++;
  XtSetArg(args[n], XmNtopOffset, 0); n++;
  XtSetValues(widget_array[WI_PANELHELPTEXT1], args, n);

  XtManageChild(widget_array[WI_PANELHELPTEXT1]);

  /***************** separator : XmSeparator *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_PANELHELPTEXT1]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_SEPARATOR], args, n);

  XtManageChild(widget_array[WI_SEPARATOR]);

  /***************** filterform : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_SEPARATOR]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_MESSAGEBOX1]); n++;
  XtSetArg(args[n], XmNtopOffset, 10); n++;
  XtSetArg(args[n], XmNleftOffset, 10); n++;
  XtSetArg(args[n], XmNrightOffset, 10); n++;
  XtSetValues(widget_array[WI_FILTERFORM], args, n);


  /***************** radioLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_RADIOLABEL], args, n);

  XtManageChild(widget_array[WI_RADIOLABEL]);

  /***************** radioBox : XmRadioBox *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNleftOffset, 10); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_RADIOLABEL]); n++;
  XtSetValues(widget_array[WI_RADIOBOX], args, n);

  XtAddCallback(widget_array[WI_ALLTOGGLE],
                XmNvalueChangedCallback,
                (XtCallbackProc)dsr_fsredist_filter_toggle_value_cb,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_ALLTOGGLE]);
  XtAddCallback(widget_array[WI_FAILEDFSTOGGLE],
                XmNvalueChangedCallback,
                (XtCallbackProc)dsr_fsredist_filter_toggle_value_cb,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_FAILEDFSTOGGLE]);
  XtAddCallback(widget_array[WI_VFSTABSLICESTOGGLE],
                XmNvalueChangedCallback,
                (XtCallbackProc)dsr_fsredist_filter_toggle_value_cb,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_VFSTABSLICESTOGGLE]);
  XtAddCallback(widget_array[WI_NONVFSTABSLICESTOGGLE],
                XmNvalueChangedCallback,
                (XtCallbackProc)dsr_fsredist_filter_toggle_value_cb,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_NONVFSTABSLICESTOGGLE]);
  XtAddCallback(widget_array[WI_SLICENAMETOGGLE],
                XmNvalueChangedCallback,
                (XtCallbackProc)dsr_fsredist_filter_toggle_value_cb,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_SLICENAMETOGGLE]);
  XtAddCallback(widget_array[WI_MNTPNTNAMETOGGLE],
                XmNvalueChangedCallback,
                (XtCallbackProc)dsr_fsredist_filter_toggle_value_cb,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_MNTPNTNAMETOGGLE]);
  XtManageChild(widget_array[WI_RADIOBOX]);

  /***************** reLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_RADIOBOX]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopOffset, 20); n++;
  XtSetValues(widget_array[WI_RELABEL], args, n);

  XtManageChild(widget_array[WI_RELABEL]);

  /***************** reTextField : XmTextField *****************/
  n = 0;
  XtAddCallback(widget_array[WI_RETEXTFIELD],
                XmNactivateCallback,
                (XtCallbackProc)dsr_fsredist_filter_ok_cb,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNleftOffset, 10); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_RELABEL]); n++;
  XtSetArg(args[n], XmNtopOffset, 0); n++;
  XtSetArg(args[n], XmNrightOffset, 10); n++;
  XtSetValues(widget_array[WI_RETEXTFIELD], args, n);

  XtManageChild(widget_array[WI_RETEXTFIELD]);
  XtManageChild(widget_array[WI_FILTERFORM]);

  /***************** messageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_MESSAGEBOX1], args, n);

  XtAddCallback(widget_array[WI_OKBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)dsr_fsredist_filter_ok_cb,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_OKBUTTON]);
  XtAddCallback(widget_array[WI_CANCELBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)dsr_fsredist_filter_cancel_cb,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_CANCELBUTTON]);
  XtAddCallback(widget_array[WI_HELPBUTTON1],
                XmNactivateCallback,
                pfgHelp,
                (XtPointer)"constraints.r");

  XtManageChild(widget_array[WI_HELPBUTTON1]);
  XtManageChild(widget_array[WI_MESSAGEBOX1]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*21);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*21);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_DSR_FSREDIST_FILTER_DIALOG]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_DSR_FSREDIST_FILTER_DIALOG]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_DSR_FSREDIST_FILTER_DIALOG];
}


/**************************************************************
 * tu_dsr_fsredist_collapse_dialog_widget:
 **************************************************************/
Widget tu_dsr_fsredist_collapse_dialog_widget(char    * name,
                                              Widget    parent,
                                              Widget ** warr_ret)
{
  Arg args[30];
  Widget widget_array[14];
  XtTranslations ttbl;
  int n;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmFormDialog *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  widget_array[WI_DSR_FSREDIST_COLLAPSE_DIALOG] =
    XmCreateFormDialog(parent, name, args, n);

  /***************** panelhelpText : XmText *****************/
  n = 0;
  XtSetArg(args[n], XmNautoShowCursorPosition, False); n++;
  XtSetArg(args[n], XmNcursorPositionVisible, False); n++;
  XtSetArg(args[n], XmNeditMode, XmMULTI_LINE_EDIT); n++;
  XtSetArg(args[n], XmNtraversalOn, False); n++;
  XtSetArg(args[n], XmNresizeHeight, True); n++;
  XtSetArg(args[n], XmNwordWrap, True); n++;
  XtSetArg(args[n], XmNshadowThickness, 0); n++;
  XtSetArg(args[n], XmNmarginWidth, 18); n++;
  XtSetArg(args[n], XmNmarginHeight, 18); n++;
  XtSetArg(args[n], XmNvalue, "message_text"); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_PANELHELPTEXT2] =
    XmCreateText(widget_array[WI_DSR_FSREDIST_COLLAPSE_DIALOG], "panelhelpText", args, n);

  /***************** collapseForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNfractionBase, 6); n++;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_COLLAPSEFORM] =
    XmCreateForm(widget_array[WI_DSR_FSREDIST_COLLAPSE_DIALOG], "collapseForm", args, n);

  /***************** fsColumnLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_BEGINNING); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_FSCOLUMNLABEL1] =
    XmCreateLabel(widget_array[WI_COLLAPSEFORM], "fsColumnLabel", args, n);

  /***************** parentColumnLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_PARENTCOLUMNLABEL] =
    XmCreateLabel(widget_array[WI_COLLAPSEFORM], "parentColumnLabel", args, n);

  /***************** scrolledWindow : XmScrolledWindow *****************/
  n = 0;
  XtSetArg(args[n], XmNscrollingPolicy, XmAUTOMATIC); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_SCROLLEDWINDOW] =
    XmCreateScrolledWindow(widget_array[WI_COLLAPSEFORM], "scrolledWindow", args, n);

  /***************** collapseRowColumn : XmRowColumn *****************/
  widget_array[WI_COLLAPSEROWCOLUMN] =
    XmCreateRowColumn(widget_array[WI_SCROLLEDWINDOW], "collapseRowColumn", NULL, 0);

  /***************** messageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdialogType, XmDIALOG_TEMPLATE); n++;
  widget_array[WI_MESSAGEBOX2] =
    XmCreateMessageBox(widget_array[WI_DSR_FSREDIST_COLLAPSE_DIALOG], "messageBox", args, n);

  /***************** okButton : XmPushButton *****************/
  widget_array[WI_OKBUTTON1] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX2], "okButton", NULL, 0);

  /***************** cancelButton : XmPushButton *****************/
  widget_array[WI_CANCELBUTTON1] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX2], "cancelButton", NULL, 0);

  /***************** button3 : XmPushButton *****************/
  widget_array[WI_BUTTON5] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX2], "button3", NULL, 0);

  /***************** button4 : XmPushButton *****************/
  widget_array[WI_BUTTON6] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX2], "button4", NULL, 0);

  /***************** helpButton : XmPushButton *****************/
  widget_array[WI_HELPBUTTON2] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX2], "helpButton", NULL, 0);

  /* Terminate the widget array */
  widget_array[13] = NULL;


  /***************** panelhelpText : XmText *****************/
  n = 0;
  ttbl = XtParseTranslationTable("#override\n\
~Ctrl ~Meta<BtnDown>:\n\
~Ctrl ~Meta<BtnUp>:");
  XtOverrideTranslations(widget_array[WI_PANELHELPTEXT2], ttbl);
  unregister_as_dropsite(widget_array[WI_PANELHELPTEXT2],
                         NULL,
                         NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftOffset, 0); n++;
  XtSetArg(args[n], XmNrightOffset, 0); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_PANELHELPTEXT2], args, n);

  XtManageChild(widget_array[WI_PANELHELPTEXT2]);

  /***************** collapseForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_PANELHELPTEXT2]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_MESSAGEBOX2]); n++;
  XtSetArg(args[n], XmNleftOffset, 10); n++;
  XtSetArg(args[n], XmNrightOffset, 10); n++;
  XtSetValues(widget_array[WI_COLLAPSEFORM], args, n);


  /***************** fsColumnLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_POSITION); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNleftPosition, 1); n++;
  XtSetValues(widget_array[WI_FSCOLUMNLABEL1], args, n);

  XtManageChild(widget_array[WI_FSCOLUMNLABEL1]);

  /***************** parentColumnLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_FSCOLUMNLABEL1]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_PARENTCOLUMNLABEL], args, n);

  XtManageChild(widget_array[WI_PARENTCOLUMNLABEL]);

  /***************** scrolledWindow : XmScrolledWindow *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_POSITION); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_POSITION); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_FSCOLUMNLABEL1]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNleftPosition, 1); n++;
  XtSetArg(args[n], XmNrightPosition, 5); n++;
  XtSetValues(widget_array[WI_SCROLLEDWINDOW], args, n);

  XtManageChild(widget_array[WI_COLLAPSEROWCOLUMN]);
  XtManageChild(widget_array[WI_SCROLLEDWINDOW]);
  XtManageChild(widget_array[WI_COLLAPSEFORM]);

  /***************** messageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdefaultButton, widget_array[WI_OKBUTTON1]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_MESSAGEBOX2], args, n);

  XtAddCallback(widget_array[WI_OKBUTTON1],
                XmNactivateCallback,
                (XtCallbackProc)dsr_fsredist_collapse_ok_cb,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_OKBUTTON1]);
  XtAddCallback(widget_array[WI_CANCELBUTTON1],
                XmNactivateCallback,
                (XtCallbackProc)dsr_fsredist_collapse_cancel_cb,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_CANCELBUTTON1]);
  XtAddCallback(widget_array[WI_HELPBUTTON2],
                XmNactivateCallback,
                pfgHelp,
                (XtPointer)"constraints.r");

  XtManageChild(widget_array[WI_HELPBUTTON2]);
  XtManageChild(widget_array[WI_MESSAGEBOX2]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*14);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*14);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_DSR_FSREDIST_COLLAPSE_DIALOG]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_DSR_FSREDIST_COLLAPSE_DIALOG]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_DSR_FSREDIST_COLLAPSE_DIALOG];
}


/**************************************************************
 * tu_dsr_fsredist_collapse_entry_widget:
 **************************************************************/
Widget tu_dsr_fsredist_collapse_entry_widget(char    * name,
                                             Widget    parent,
                                             Widget ** warr_ret)
{
  Arg args[17];
  Widget widget_array[4];
  int n;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  widget_array[WI_DSR_FSREDIST_COLLAPSE_ENTRY] =
    XmCreateForm(parent, name, args, n);

  /***************** fsValue : XmToggleButton *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_BEGINNING); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_FSVALUE1] =
    XmCreateToggleButton(widget_array[WI_DSR_FSREDIST_COLLAPSE_ENTRY], "fsValue", args, n);

  /***************** parentValue : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_BEGINNING); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_PARENTVALUE] =
    XmCreateLabel(widget_array[WI_DSR_FSREDIST_COLLAPSE_ENTRY], "parentValue", args, n);

  /* Terminate the widget array */
  widget_array[3] = NULL;


  /***************** fsValue : XmToggleButton *****************/
  n = 0;
  XtAddCallback(widget_array[WI_FSVALUE1],
                XmNvalueChangedCallback,
                (XtCallbackProc)dsr_fsredist_collapse_toggle_value_cb,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_FSVALUE1], args, n);

  XtManageChild(widget_array[WI_FSVALUE1]);

  /***************** parentValue : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_FSVALUE1]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_PARENTVALUE], args, n);

  XtManageChild(widget_array[WI_PARENTVALUE]);
  XtManageChild(widget_array[WI_DSR_FSREDIST_COLLAPSE_ENTRY]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*4);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*4);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_DSR_FSREDIST_COLLAPSE_ENTRY]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_DSR_FSREDIST_COLLAPSE_ENTRY]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_DSR_FSREDIST_COLLAPSE_ENTRY];
}



/****************************************************************
 * create_method:
 *     This function creates a widget hierarchy using the
 *     functions generated above.
 ****************************************************************/
static Widget create_method(char               * temp,
                            char               * name,
                            Widget               parent,
                            Display            * disp,
                            Screen             * screen,
                            tu_template_descr  * retval)
{
  Widget w;

  sDisplay = disp;
  sScreen = screen;

  /* check each node against its name and call its
   * create function if appropriate */
  w = NULL;
  if (strcmp(temp, "dsr_fsredist_dialog") == 0){
    w = tu_dsr_fsredist_dialog_widget(name, parent, (Widget **)retval);
  }
  else if (strcmp(temp, "dsr_fsredist_entry") == 0){
    w = tu_dsr_fsredist_entry_widget(name, parent, (Widget **)retval);
  }
  else if (strcmp(temp, "dsr_fsredist_filter_dialog") == 0){
    w = tu_dsr_fsredist_filter_dialog_widget(name, parent, (Widget **)retval);
  }
  else if (strcmp(temp, "dsr_fsredist_collapse_dialog") == 0){
    w = tu_dsr_fsredist_collapse_dialog_widget(name, parent, (Widget **)retval);
  }
  else if (strcmp(temp, "dsr_fsredist_collapse_entry") == 0){
    w = tu_dsr_fsredist_collapse_entry_widget(name, parent, (Widget **)retval);
  }

  sDisplay = NULL;
  sScreen = NULL;
  return w;
}

