
/****************************************************************
 *
 * Name      : pfgInstallClients.c
 *
 * File is generated by TeleUSE
 * Version : TeleUSE v3.0.2 / Solaris 2.4
 *
 * Copyright (c) 1994-1995 by Sun MicroSystems, Inc.
 * All rights reserved.
 *
 ****************************************************************/

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Shell.h>
#include <Xm/Xm.h>
#include <Xm/Protocols.h>

#include "tu_runtime.h"

#include <stdarg.h>

#include <stdio.h>
#include <stdlib.h>
#include "pfgInstallClients_ui.h"


#include <Xm/CascadeB.h>
#include <Xm/CascadeBG.h>
#include <Xm/Form.h>
#include <Xm/Frame.h>
#include <Xm/Label.h>
#include <Xm/MessageB.h>
#include <Xm/MwmUtil.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/ScrolledW.h>
#include <Xm/Text.h>
#include <Xm/TextF.h>
#include <Xm/ToggleB.h>


/* Local variables used when selecting screen & display */
static Display * sDisplay = NULL;
static Screen  * sScreen  = NULL;

/* forward declaration */
static void class_init(void);

extern void clientGobackCB(Widget widget,
                           tu_ccb_arg_p closure,
                           XtPointer calldata);
extern void setSwapSize_traverse(Widget widget,
                                 tu_ccb_arg_p closure,
                                 XtPointer calldata);
extern void setSwapSize(Widget widget,
                        tu_ccb_arg_p closure,
                        XtPointer calldata);
extern void reset_to_none(Widget widget,
                          tu_ccb_arg_p closure,
                          XtPointer calldata);
extern void clientContinueCB(Widget widget,
                             tu_ccb_arg_p closure,
                             XtPointer calldata);
extern void set_separate_swap(Widget widget,
                              tu_ccb_arg_p closure,
                              XtPointer calldata);
extern void unregister_as_dropsite(Widget widget,
                                   tu_ccb_arg_p closure,
                                   XtPointer calldata);
extern void clientExitCB(Widget widget,
                         tu_ccb_arg_p closure,
                         XtPointer calldata);
extern void verify_text_is_digit(Widget widget,
                                 tu_ccb_arg_p closure,
                                 XtPointer calldata);
extern void clientCancelCB(Widget widget,
                           tu_ccb_arg_p closure,
                           XtPointer calldata);
extern void setRootSize_traverse(Widget widget,
                                 tu_ccb_arg_p closure,
                                 XtPointer calldata);
extern void setRootSize(Widget widget,
                        tu_ccb_arg_p closure,
                        XtPointer calldata);
extern void show_root_entry(Widget widget,
                            tu_ccb_arg_p closure,
                            XtPointer calldata);
extern void show_root_and_swap_entries(Widget widget,
                                       tu_ccb_arg_p closure,
                                       XtPointer calldata);
extern void show_root_only(Widget widget,
                           tu_ccb_arg_p closure,
                           XtPointer calldata);
extern void show_root_and_swap(Widget widget,
                               tu_ccb_arg_p closure,
                               XtPointer calldata);
extern void compute_size_total(Widget widget,
                               tu_ccb_arg_p closure,
                               XtPointer calldata);
extern void show_swap_entry(Widget widget,
                            tu_ccb_arg_p closure,
                            XtPointer calldata);
extern void show_swap_on_root(Widget widget,
                              tu_ccb_arg_p closure,
                              XtPointer calldata);
extern void pfgHelp(Widget widget,
                    XtPointer closure,
                    XtPointer calldata);
extern void setNumberOfClients_traverse(Widget widget,
                                        tu_ccb_arg_p closure,
                                        XtPointer calldata);
extern void setNumberOfClients(Widget widget,
                               tu_ccb_arg_p closure,
                               XtPointer calldata);


/****************************************************************
 * get_constraint_widget:
 ****************************************************************/
static Widget get_constraint_widget(Widget child, Widget parent)
{
  Widget w;

  w = child;
  while (XtParent(w) != parent)
    w = XtParent(w);
  return (w);
}


/****************************************************************
 * put_client_data_arg:
 *    set up a client data argument.
 ****************************************************************/
static tu_ccb_arg_p put_client_data_arg(unsigned int cnt, ...)
{
  va_list pvar;
  int i;
  tu_ccb_arg_p rv;

  rv = (tu_ccb_arg_p) malloc(cnt*sizeof(tu_ccb_arg_t));
  if (rv == NULL) return NULL;

  va_start(pvar, cnt);

  for (i=0;i<cnt;i++) {
    rv[i].name = va_arg(pvar, char *);
    rv[i].value = va_arg(pvar, char *);
    rv[i].next = &rv[i+1];
  }
  va_end(pvar);
  rv[cnt-1].next = NULL;
  return rv;
}



/****************************************************************
 * class_init:
 *     Initializes the classes used by the user interface.
 ****************************************************************/
static void class_init(void)
{
  static int inited = 0;

  if (inited != 0)
    return;

  inited = 1;
  sDisplay = sDisplay;

  XtInitializeWidgetClass(xmRowColumnWidgetClass);
  XtInitializeWidgetClass(xmFormWidgetClass);
  XtInitializeWidgetClass(xmFrameWidgetClass);
  XtInitializeWidgetClass(xmPushButtonWidgetClass);
  XtInitializeWidgetClass(xmLabelWidgetClass);
  XtInitializeWidgetClass(xmTextFieldWidgetClass);
  XtInitializeWidgetClass(xmToggleButtonWidgetClass);
  XtInitializeWidgetClass(xmTextWidgetClass);
  XtInitializeWidgetClass(xmScrolledWindowWidgetClass);
  XtInitializeWidgetClass(xmMessageBoxWidgetClass);
}



/****************************************************************
 *
 *  Main C code for presentation component
 *
 ****************************************************************/

/**************************************************************
 * tu_client_setup_table_widget:
 **************************************************************/
Widget tu_client_setup_table_widget(char    * name,
                                    Widget    parent,
                                    Widget ** warr_ret)
{
  Arg args[22];
  Widget widget_array[32];
  int n;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNadjustLast, False); n++;
  XtSetArg(args[n], XmNorientation, XmVERTICAL); n++;
  widget_array[WI_CLIENT_SETUP_TABLE] =
    XmCreateRowColumn(parent, name, args, n);

  /***************** client_setup : XmForm *****************/
  /* Form for No Swap definiton.  The platform option menu will */
  /* be created with the platform choices from a previous screen. */
  /* All other fields will be initially filled in with default values that */
  /* can later be changed by the user.  The total size will be */
  /* calculated, but can later be changed by the user also. */
  n = 0;
  XtSetArg(args[n], XmNverticalSpacing, 8); n++;
  XtSetArg(args[n], XmNhorizontalSpacing, 6); n++;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  widget_array[WI_CLIENT_SETUP] =
    XmCreateForm(widget_array[WI_CLIENT_SETUP_TABLE], "client_setup", args, n);

  /***************** client_types_frame : XmFrame *****************/
  n = 0;
  XtSetArg(args[n], XmNshadowThickness, 0); n++;
  widget_array[WI_CLIENT_TYPES_FRAME] =
    XmCreateFrame(widget_array[WI_CLIENT_SETUP], "client_types_frame", args, n);

  /***************** client_types : XmOptionMenu *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNspacing, 0); n++;
  XtSetArg(args[n], XmNmarginHeight, 2); n++;
  widget_array[WI_CLIENT_TYPES] =
    XmCreateOptionMenu(widget_array[WI_CLIENT_TYPES_FRAME], "client_types", args, n);

  /***************** ctypeMenu : XmPulldownMenu *****************/
  widget_array[WI_CTYPEMENU] =
    XmCreatePulldownMenu(widget_array[WI_CLIENT_TYPES_FRAME], "ctypeMenu", NULL, 0);
  {
    Arg args[1];
    XtSetArg(args[0], XmNsubMenuId, widget_array[WI_CTYPEMENU]);
    XtSetValues(widget_array[WI_CLIENT_TYPES], args, 1);
  }

  /***************** root_only : XmPushButton *****************/
  widget_array[WI_ROOT_ONLY] =
    XmCreatePushButton(widget_array[WI_CTYPEMENU], "root_only", NULL, 0);

  /***************** swap_only : XmPushButton *****************/
  widget_array[WI_SWAP_ONLY] =
    XmCreatePushButton(widget_array[WI_CTYPEMENU], "swap_only", NULL, 0);

  /***************** root_and_swap : XmPushButton *****************/
  widget_array[WI_ROOT_AND_SWAP] =
    XmCreatePushButton(widget_array[WI_CTYPEMENU], "root_and_swap", NULL, 0);

  /***************** root_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNwidth, 64); n++;
  XtSetArg(args[n], XmNrecomputeSize, False); n++;
  widget_array[WI_ROOT_LABEL] =
    XmCreateLabel(widget_array[WI_CLIENT_SETUP], "root_label", args, n);

  /***************** numClients : XmTextField *****************/
  /* The number of clients.  The default value is 5. */
  n = 0;
  XtSetArg(args[n], XmNmaxLength, 4); n++;
  XtSetArg(args[n], XmNwidth, 80); n++;
  widget_array[WI_NUMCLIENTS] =
    XmCreateTextField(widget_array[WI_CLIENT_SETUP], "numClients", args, n);

  /***************** multiply : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  widget_array[WI_MULTIPLY] =
    XmCreateLabel(widget_array[WI_CLIENT_SETUP], "multiply", args, n);

  /***************** root_size_per : XmTextField *****************/
  /* The default size of /root. */
  n = 0;
  XtSetArg(args[n], XmNwidth, 90); n++;
  XtSetArg(args[n], XmNmaxLength, 4); n++;
  widget_array[WI_ROOT_SIZE_PER] =
    XmCreateTextField(widget_array[WI_CLIENT_SETUP], "root_size_per", args, n);

  /***************** equals : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_EQUALS] =
    XmCreateLabel(widget_array[WI_CLIENT_SETUP], "equals", args, n);

  /***************** total_root_size : XmLabel *****************/
  /* The computed total from a multiplcation of number */
  /* of clients times size per client desired.  This field is */
  /* calculated, but can also be edited. -- Changed to a label for this release, will be changed back to an editable text field later. */
  n = 0;
  XtSetArg(args[n], XmNwidth, 130); n++;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNrecomputeSize, False); n++;
  widget_array[WI_TOTAL_ROOT_SIZE] =
    XmCreateLabel(widget_array[WI_CLIENT_SETUP], "total_root_size", args, n);

  /***************** root_mount_point : XmLabel *****************/
  /* The desired mount point for /root.  The default is /export/root. --- This will be changed back to an editable text field for the next release. */
  n = 0;
  XtSetArg(args[n], XmNwidth, 130); n++;
  XtSetArg(args[n], XmNrecomputeSize, False); n++;
  widget_array[WI_ROOT_MOUNT_POINT] =
    XmCreateLabel(widget_array[WI_CLIENT_SETUP], "root_mount_point", args, n);

  /***************** swap_setup : XmForm *****************/
  /* Form for Separate Swap definition. */
  n = 0;
  XtSetArg(args[n], XmNverticalSpacing, 8); n++;
  XtSetArg(args[n], XmNhorizontalSpacing, 6); n++;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  widget_array[WI_SWAP_SETUP] =
    XmCreateForm(widget_array[WI_CLIENT_SETUP_TABLE], "swap_setup", args, n);

  /***************** swap_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNwidth, 64); n++;
  XtSetArg(args[n], XmNrecomputeSize, False); n++;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  widget_array[WI_SWAP_LABEL] =
    XmCreateLabel(widget_array[WI_SWAP_SETUP], "swap_label", args, n);

  /***************** swap_numClients : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNmaxLength, 4); n++;
  XtSetArg(args[n], XmNwidth, 80); n++;
  XtSetArg(args[n], XtNmappedWhenManaged, False); n++;
  widget_array[WI_SWAP_NUMCLIENTS] =
    XmCreateTextField(widget_array[WI_SWAP_SETUP], "swap_numClients", args, n);

  /***************** swap_multiply : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  widget_array[WI_SWAP_MULTIPLY] =
    XmCreateLabel(widget_array[WI_SWAP_SETUP], "swap_multiply", args, n);

  /***************** swap_size_per : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNwidth, 90); n++;
  XtSetArg(args[n], XmNmaxLength, 4); n++;
  widget_array[WI_SWAP_SIZE_PER] =
    XmCreateTextField(widget_array[WI_SWAP_SETUP], "swap_size_per", args, n);

  /***************** swap_equals : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  widget_array[WI_SWAP_EQUALS] =
    XmCreateLabel(widget_array[WI_SWAP_SETUP], "swap_equals", args, n);

  /***************** total_swap_size : XmLabel *****************/
  /* Changed to a label for now.  Will be changed back to editable for the next release. */
  n = 0;
  XtSetArg(args[n], XmNwidth, 130); n++;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNrecomputeSize, False); n++;
  widget_array[WI_TOTAL_SWAP_SIZE] =
    XmCreateLabel(widget_array[WI_SWAP_SETUP], "total_swap_size", args, n);

  /***************** swap_mount_point : XmLabel *****************/
  /* Chnaged to a label for now, will be changed back to an editable text field for the next release. */
  n = 0;
  XtSetArg(args[n], XmNwidth, 130); n++;
  XtSetArg(args[n], XmNrecomputeSize, False); n++;
  widget_array[WI_SWAP_MOUNT_POINT] =
    XmCreateLabel(widget_array[WI_SWAP_SETUP], "swap_mount_point", args, n);

  /***************** s_on_r_setup : XmForm *****************/
  /* --- This is being unmanaged for now.  It is planned for use */
  /* in the 2.6 release however, and should not be deleted from this module. --- Form for swap on root definition. */
  n = 0;
  XtSetArg(args[n], XmNhorizontalSpacing, 6); n++;
  XtSetArg(args[n], XmNverticalSpacing, 8); n++;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  widget_array[WI_S_ON_R_SETUP] =
    XmCreateForm(widget_array[WI_CLIENT_SETUP_TABLE], "s_on_r_setup", args, n);

  /***************** sonr_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNwidth, 64); n++;
  XtSetArg(args[n], XmNrecomputeSize, False); n++;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  widget_array[WI_SONR_LABEL] =
    XmCreateLabel(widget_array[WI_S_ON_R_SETUP], "sonr_label", args, n);

  /***************** numClients : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNmaxLength, 5); n++;
  XtSetArg(args[n], XmNwidth, 80); n++;
  XtSetArg(args[n], XtNmappedWhenManaged, False); n++;
  widget_array[WI_NUMCLIENTS1] =
    XmCreateTextField(widget_array[WI_S_ON_R_SETUP], "numClients", args, n);

  /***************** sonr_multiply : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  widget_array[WI_SONR_MULTIPLY] =
    XmCreateLabel(widget_array[WI_S_ON_R_SETUP], "sonr_multiply", args, n);

  /***************** size_per : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNwidth, 90); n++;
  widget_array[WI_SIZE_PER] =
    XmCreateTextField(widget_array[WI_S_ON_R_SETUP], "size_per", args, n);

  /***************** sonr_equals : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XtNmappedWhenManaged, False); n++;
  widget_array[WI_SONR_EQUALS] =
    XmCreateLabel(widget_array[WI_S_ON_R_SETUP], "sonr_equals", args, n);

  /***************** total_size : XmTextField *****************/
  /* The total size here will be the same as that defined for /root. */
  n = 0;
  XtSetArg(args[n], XmNwidth, 90); n++;
  XtSetArg(args[n], XmNeditable, False); n++;
  XtSetArg(args[n], XtNmappedWhenManaged, False); n++;
  widget_array[WI_TOTAL_SIZE] =
    XmCreateTextField(widget_array[WI_S_ON_R_SETUP], "total_size", args, n);

  /***************** mount_point : XmTextField *****************/
  /* For Swap on Root, the default mount point is the same as */
  /* that defined for /root. */
  n = 0;
  XtSetArg(args[n], XmNvalue, "/export/root"); n++;
  XtSetArg(args[n], XtNmappedWhenManaged, False); n++;
  widget_array[WI_MOUNT_POINT] =
    XmCreateTextField(widget_array[WI_S_ON_R_SETUP], "mount_point", args, n);

  /* Terminate the widget array */
  widget_array[31] = NULL;


  /***************** client_types_frame : XmFrame *****************/
  n = 0;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_ROOT_LABEL]); n++;
  XtSetValues(widget_array[WI_CLIENT_TYPES_FRAME], args, n);


  /***************** client_types : XmOptionMenu *****************/
  n = 0;
  XtSetArg(args[n], XmNmenuHistory, widget_array[WI_ROOT_AND_SWAP]); n++;
  XtSetValues(widget_array[WI_CLIENT_TYPES], args, n);

  XtAddCallback(widget_array[WI_ROOT_ONLY],
                XmNactivateCallback,
                (XtCallbackProc)show_root_entry,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_ROOT_ONLY]);
  XtAddCallback(widget_array[WI_SWAP_ONLY],
                XmNactivateCallback,
                (XtCallbackProc)show_swap_entry,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_SWAP_ONLY]);
  XtAddCallback(widget_array[WI_ROOT_AND_SWAP],
                XmNactivateCallback,
                (XtCallbackProc)show_root_and_swap_entries,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_ROOT_AND_SWAP]);
  XtManageChild(widget_array[WI_CLIENT_TYPES]);
  XtManageChild(widget_array[WI_CLIENT_TYPES_FRAME]);

  /***************** root_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_NUMCLIENTS]); n++;
  XtSetValues(widget_array[WI_ROOT_LABEL], args, n);

  XtManageChild(widget_array[WI_ROOT_LABEL]);

  /***************** numClients : XmTextField *****************/
  n = 0;
  XtAddCallback(widget_array[WI_NUMCLIENTS],
                XmNactivateCallback,
                (XtCallbackProc)setNumberOfClients_traverse,
                (XtPointer)NULL);

  XtAddCallback(widget_array[WI_NUMCLIENTS],
                XmNlosingFocusCallback,
                (XtCallbackProc)setNumberOfClients,
                (XtPointer)NULL);

  XtAddCallback(widget_array[WI_NUMCLIENTS],
                XmNmodifyVerifyCallback,
                (XtCallbackProc)verify_text_is_digit,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_MULTIPLY]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_NUMCLIENTS], args, n);

  XtManageChild(widget_array[WI_NUMCLIENTS]);

  /***************** multiply : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_ROOT_SIZE_PER]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_MULTIPLY], args, n);

  XtManageChild(widget_array[WI_MULTIPLY]);

  /***************** root_size_per : XmTextField *****************/
  n = 0;
  XtAddCallback(widget_array[WI_ROOT_SIZE_PER],
                XmNactivateCallback,
                (XtCallbackProc)setRootSize_traverse,
                (XtPointer)NULL);

  XtAddCallback(widget_array[WI_ROOT_SIZE_PER],
                XmNlosingFocusCallback,
                (XtCallbackProc)setRootSize,
                (XtPointer)NULL);

  XtAddCallback(widget_array[WI_ROOT_SIZE_PER],
                XmNmodifyVerifyCallback,
                (XtCallbackProc)verify_text_is_digit,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_EQUALS]); n++;
  XtSetValues(widget_array[WI_ROOT_SIZE_PER], args, n);

  XtManageChild(widget_array[WI_ROOT_SIZE_PER]);

  /***************** equals : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_TOTAL_ROOT_SIZE]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_EQUALS], args, n);

  XtManageChild(widget_array[WI_EQUALS]);

  /***************** total_root_size : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_ROOT_MOUNT_POINT]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_TOTAL_ROOT_SIZE], args, n);

  XtManageChild(widget_array[WI_TOTAL_ROOT_SIZE]);

  /***************** root_mount_point : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_ROOT_MOUNT_POINT], args, n);

  XtManageChild(widget_array[WI_ROOT_MOUNT_POINT]);
  XtManageChild(widget_array[WI_CLIENT_SETUP]);

  /***************** swap_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_SWAP_NUMCLIENTS]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SWAP_LABEL], args, n);

  XtManageChild(widget_array[WI_SWAP_LABEL]);

  /***************** swap_numClients : XmTextField *****************/
  n = 0;
  XtAddCallback(widget_array[WI_SWAP_NUMCLIENTS],
                XmNlosingFocusCallback,
                (XtCallbackProc)setNumberOfClients,
                (XtPointer)NULL);

  XtAddCallback(widget_array[WI_SWAP_NUMCLIENTS],
                XmNactivateCallback,
                (XtCallbackProc)setNumberOfClients_traverse,
                (XtPointer)NULL);

  XtAddCallback(widget_array[WI_SWAP_NUMCLIENTS],
                XmNmodifyVerifyCallback,
                (XtCallbackProc)verify_text_is_digit,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_SWAP_MULTIPLY]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SWAP_NUMCLIENTS], args, n);

  XtManageChild(widget_array[WI_SWAP_NUMCLIENTS]);

  /***************** swap_multiply : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_SWAP_SIZE_PER]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SWAP_MULTIPLY], args, n);

  XtManageChild(widget_array[WI_SWAP_MULTIPLY]);

  /***************** swap_size_per : XmTextField *****************/
  n = 0;
  XtAddCallback(widget_array[WI_SWAP_SIZE_PER],
                XmNactivateCallback,
                (XtCallbackProc)setSwapSize_traverse,
                (XtPointer)NULL);

  XtAddCallback(widget_array[WI_SWAP_SIZE_PER],
                XmNlosingFocusCallback,
                (XtCallbackProc)setSwapSize,
                (XtPointer)NULL);

  XtAddCallback(widget_array[WI_SWAP_SIZE_PER],
                XmNmodifyVerifyCallback,
                (XtCallbackProc)verify_text_is_digit,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_SWAP_EQUALS]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SWAP_SIZE_PER], args, n);

  XtManageChild(widget_array[WI_SWAP_SIZE_PER]);

  /***************** swap_equals : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_TOTAL_SWAP_SIZE]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SWAP_EQUALS], args, n);

  XtManageChild(widget_array[WI_SWAP_EQUALS]);

  /***************** total_swap_size : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_SWAP_MOUNT_POINT]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_TOTAL_SWAP_SIZE], args, n);

  XtManageChild(widget_array[WI_TOTAL_SWAP_SIZE]);

  /***************** swap_mount_point : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SWAP_MOUNT_POINT], args, n);

  XtManageChild(widget_array[WI_SWAP_MOUNT_POINT]);
  XtManageChild(widget_array[WI_SWAP_SETUP]);

  /***************** sonr_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_NUMCLIENTS1]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SONR_LABEL], args, n);

  XtManageChild(widget_array[WI_SONR_LABEL]);

  /***************** numClients : XmTextField *****************/
  n = 0;
  XtAddCallback(widget_array[WI_NUMCLIENTS1],
                XmNactivateCallback,
                (XtCallbackProc)compute_size_total,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_SONR_MULTIPLY]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_NUMCLIENTS1], args, n);

  XtManageChild(widget_array[WI_NUMCLIENTS1]);

  /***************** sonr_multiply : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_SIZE_PER]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SONR_MULTIPLY], args, n);

  XtManageChild(widget_array[WI_SONR_MULTIPLY]);

  /***************** size_per : XmTextField *****************/
  n = 0;
  XtAddCallback(widget_array[WI_SIZE_PER],
                XmNactivateCallback,
                (XtCallbackProc)compute_size_total,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_SONR_EQUALS]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SIZE_PER], args, n);

  XtManageChild(widget_array[WI_SIZE_PER]);

  /***************** sonr_equals : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_TOTAL_SIZE]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SONR_EQUALS], args, n);

  XtManageChild(widget_array[WI_SONR_EQUALS]);

  /***************** total_size : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_MOUNT_POINT]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_TOTAL_SIZE], args, n);

  XtManageChild(widget_array[WI_TOTAL_SIZE]);

  /***************** mount_point : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_MOUNT_POINT], args, n);

  XtManageChild(widget_array[WI_MOUNT_POINT]);
  XtManageChild(widget_array[WI_CLIENT_SETUP_TABLE]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*32);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*32);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_CLIENT_SETUP_TABLE]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_CLIENT_SETUP_TABLE]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_CLIENT_SETUP_TABLE];
}


/**************************************************************
 * tu_client_setup_widget:
 *   Form for No Swap definiton.  The platform option menu will
 *   be created with the platform choices from a previous screen.
 *   All other fields will be initially filled in with default values that
 *   can later be changed by the user.  The total size will be
 *   calculated, but can later be changed by the user also.
 **************************************************************/
Widget tu_client_setup_widget(char    * name,
                              Widget    parent,
                              Widget ** warr_ret)
{
  Arg args[20];
  Widget widget_array[15];
  int n;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNverticalSpacing, 8); n++;
  XtSetArg(args[n], XmNhorizontalSpacing, 6); n++;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  widget_array[WI_CLIENT_SETUP1] =
    XmCreateForm(parent, name, args, n);

  /***************** client_types_frame : XmFrame *****************/
  n = 0;
  XtSetArg(args[n], XmNshadowThickness, 0); n++;
  widget_array[WI_CLIENT_TYPES_FRAME1] =
    XmCreateFrame(widget_array[WI_CLIENT_SETUP1], "client_types_frame", args, n);

  /***************** client_types : XmOptionMenu *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNspacing, 0); n++;
  XtSetArg(args[n], XmNmarginHeight, 2); n++;
  widget_array[WI_CLIENT_TYPES1] =
    XmCreateOptionMenu(widget_array[WI_CLIENT_TYPES_FRAME1], "client_types", args, n);

  /***************** ctypeMenu : XmPulldownMenu *****************/
  widget_array[WI_CTYPEMENU1] =
    XmCreatePulldownMenu(widget_array[WI_CLIENT_TYPES_FRAME1], "ctypeMenu", NULL, 0);
  {
    Arg args[1];
    XtSetArg(args[0], XmNsubMenuId, widget_array[WI_CTYPEMENU1]);
    XtSetValues(widget_array[WI_CLIENT_TYPES1], args, 1);
  }

  /***************** root_only : XmPushButton *****************/
  widget_array[WI_ROOT_ONLY1] =
    XmCreatePushButton(widget_array[WI_CTYPEMENU1], "root_only", NULL, 0);

  /***************** swap_only : XmPushButton *****************/
  widget_array[WI_SWAP_ONLY1] =
    XmCreatePushButton(widget_array[WI_CTYPEMENU1], "swap_only", NULL, 0);

  /***************** root_and_swap : XmPushButton *****************/
  widget_array[WI_ROOT_AND_SWAP1] =
    XmCreatePushButton(widget_array[WI_CTYPEMENU1], "root_and_swap", NULL, 0);

  /***************** root_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNwidth, 64); n++;
  XtSetArg(args[n], XmNrecomputeSize, False); n++;
  widget_array[WI_ROOT_LABEL1] =
    XmCreateLabel(widget_array[WI_CLIENT_SETUP1], "root_label", args, n);

  /***************** numClients : XmTextField *****************/
  /* The number of clients.  The default value is 5. */
  n = 0;
  XtSetArg(args[n], XmNmaxLength, 4); n++;
  XtSetArg(args[n], XmNwidth, 80); n++;
  widget_array[WI_NUMCLIENTS2] =
    XmCreateTextField(widget_array[WI_CLIENT_SETUP1], "numClients", args, n);

  /***************** multiply : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  widget_array[WI_MULTIPLY1] =
    XmCreateLabel(widget_array[WI_CLIENT_SETUP1], "multiply", args, n);

  /***************** root_size_per : XmTextField *****************/
  /* The default size of /root. */
  n = 0;
  XtSetArg(args[n], XmNwidth, 90); n++;
  XtSetArg(args[n], XmNmaxLength, 4); n++;
  widget_array[WI_ROOT_SIZE_PER1] =
    XmCreateTextField(widget_array[WI_CLIENT_SETUP1], "root_size_per", args, n);

  /***************** equals : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_EQUALS1] =
    XmCreateLabel(widget_array[WI_CLIENT_SETUP1], "equals", args, n);

  /***************** total_root_size : XmLabel *****************/
  /* The computed total from a multiplcation of number */
  /* of clients times size per client desired.  This field is */
  /* calculated, but can also be edited. -- Changed to a label for this release, will be changed back to an editable text field later. */
  n = 0;
  XtSetArg(args[n], XmNwidth, 130); n++;
  widget_array[WI_TOTAL_ROOT_SIZE1] =
    XmCreateLabel(widget_array[WI_CLIENT_SETUP1], "total_root_size", args, n);

  /***************** root_mount_point : XmLabel *****************/
  /* The desired mount point for /root.  The default is /export/root. --- This will be changed back to an editable text field for the next release. */
  widget_array[WI_ROOT_MOUNT_POINT1] =
    XmCreateLabel(widget_array[WI_CLIENT_SETUP1], "root_mount_point", NULL, 0);

  /* Terminate the widget array */
  widget_array[14] = NULL;


  /***************** client_types_frame : XmFrame *****************/
  n = 0;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_ROOT_LABEL1]); n++;
  XtSetValues(widget_array[WI_CLIENT_TYPES_FRAME1], args, n);


  /***************** client_types : XmOptionMenu *****************/
  n = 0;
  XtSetArg(args[n], XmNmenuHistory, widget_array[WI_ROOT_AND_SWAP1]); n++;
  XtSetValues(widget_array[WI_CLIENT_TYPES1], args, n);

  XtAddCallback(widget_array[WI_ROOT_ONLY1],
                XmNactivateCallback,
                (XtCallbackProc)show_root_entry,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_ROOT_ONLY1]);
  XtAddCallback(widget_array[WI_SWAP_ONLY1],
                XmNactivateCallback,
                (XtCallbackProc)show_swap_entry,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_SWAP_ONLY1]);
  XtAddCallback(widget_array[WI_ROOT_AND_SWAP1],
                XmNactivateCallback,
                (XtCallbackProc)show_root_and_swap_entries,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_ROOT_AND_SWAP1]);
  XtManageChild(widget_array[WI_CLIENT_TYPES1]);
  XtManageChild(widget_array[WI_CLIENT_TYPES_FRAME1]);

  /***************** root_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_NUMCLIENTS2]); n++;
  XtSetValues(widget_array[WI_ROOT_LABEL1], args, n);

  XtManageChild(widget_array[WI_ROOT_LABEL1]);

  /***************** numClients : XmTextField *****************/
  n = 0;
  XtAddCallback(widget_array[WI_NUMCLIENTS2],
                XmNactivateCallback,
                (XtCallbackProc)setNumberOfClients_traverse,
                (XtPointer)NULL);

  XtAddCallback(widget_array[WI_NUMCLIENTS2],
                XmNlosingFocusCallback,
                (XtCallbackProc)setNumberOfClients,
                (XtPointer)NULL);

  XtAddCallback(widget_array[WI_NUMCLIENTS2],
                XmNmodifyVerifyCallback,
                (XtCallbackProc)verify_text_is_digit,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_MULTIPLY1]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_NUMCLIENTS2], args, n);

  XtManageChild(widget_array[WI_NUMCLIENTS2]);

  /***************** multiply : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_ROOT_SIZE_PER1]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_MULTIPLY1], args, n);

  XtManageChild(widget_array[WI_MULTIPLY1]);

  /***************** root_size_per : XmTextField *****************/
  n = 0;
  XtAddCallback(widget_array[WI_ROOT_SIZE_PER1],
                XmNactivateCallback,
                (XtCallbackProc)setRootSize_traverse,
                (XtPointer)NULL);

  XtAddCallback(widget_array[WI_ROOT_SIZE_PER1],
                XmNlosingFocusCallback,
                (XtCallbackProc)setRootSize,
                (XtPointer)NULL);

  XtAddCallback(widget_array[WI_ROOT_SIZE_PER1],
                XmNmodifyVerifyCallback,
                (XtCallbackProc)verify_text_is_digit,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_EQUALS1]); n++;
  XtSetValues(widget_array[WI_ROOT_SIZE_PER1], args, n);

  XtManageChild(widget_array[WI_ROOT_SIZE_PER1]);

  /***************** equals : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_TOTAL_ROOT_SIZE1]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_EQUALS1], args, n);

  XtManageChild(widget_array[WI_EQUALS1]);

  /***************** total_root_size : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_ROOT_MOUNT_POINT1]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_TOTAL_ROOT_SIZE1], args, n);

  XtManageChild(widget_array[WI_TOTAL_ROOT_SIZE1]);

  /***************** root_mount_point : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_ROOT_MOUNT_POINT1], args, n);

  XtManageChild(widget_array[WI_ROOT_MOUNT_POINT1]);
  XtManageChild(widget_array[WI_CLIENT_SETUP1]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*15);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*15);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_CLIENT_SETUP1]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_CLIENT_SETUP1]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_CLIENT_SETUP1];
}


/**************************************************************
 * tu_new_client_setup_widget:
 *   Form for No Swap definiton.  The platform option menu will
 *   be created with the platform choices from a previous screen.
 *   All other fields will be initially filled in with default values that
 *   can later be changed by the user.  The total size will be
 *   calculated, but can later be changed by the user also.
 **************************************************************/
Widget tu_new_client_setup_widget(char    * name,
                                  Widget    parent,
                                  Widget ** warr_ret)
{
  Arg args[19];
  Widget widget_array[23];
  int n;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNverticalSpacing, 8); n++;
  XtSetArg(args[n], XmNhorizontalSpacing, 6); n++;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  widget_array[WI_NEW_CLIENT_SETUP] =
    XmCreateForm(parent, name, args, n);

  /***************** platforms : XmOptionMenu *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_PLATFORMS] =
    XmCreateOptionMenu(widget_array[WI_NEW_CLIENT_SETUP], "platforms", args, n);

  /***************** platformMenu : XmPulldownMenu *****************/
  widget_array[WI_PLATFORMMENU] =
    XmCreatePulldownMenu(widget_array[WI_NEW_CLIENT_SETUP], "platformMenu", NULL, 0);
  {
    Arg args[1];
    XtSetArg(args[0], XmNsubMenuId, widget_array[WI_PLATFORMMENU]);
    XtSetValues(widget_array[WI_PLATFORMS], args, 1);
  }

  /***************** root_svc_none : XmPushButton *****************/
  widget_array[WI_ROOT_SVC_NONE] =
    XmCreatePushButton(widget_array[WI_PLATFORMMENU], "root_svc_none", NULL, 0);

  /***************** no_platform : XmPushButton *****************/
  widget_array[WI_NO_PLATFORM] =
    XmCreatePushButton(widget_array[WI_PLATFORMMENU], "no_platform", NULL, 0);

  /***************** Delete : XmPushButton *****************/
  widget_array[WI_DELETE] =
    XmCreatePushButton(widget_array[WI_PLATFORMMENU], "Delete", NULL, 0);

  /***************** platform_1 : XmPushButton *****************/
  widget_array[WI_PLATFORM_1] =
    XmCreatePushButton(widget_array[WI_PLATFORMMENU], "platform_1", NULL, 0);

  /***************** platform_2 : XmPushButton *****************/
  widget_array[WI_PLATFORM_2] =
    XmCreatePushButton(widget_array[WI_PLATFORMMENU], "platform_2", NULL, 0);

  /***************** platform_3 : XmPushButton *****************/
  widget_array[WI_PLATFORM_3] =
    XmCreatePushButton(widget_array[WI_PLATFORMMENU], "platform_3", NULL, 0);

  /***************** client_types : XmOptionMenu *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_CLIENT_TYPES2] =
    XmCreateOptionMenu(widget_array[WI_NEW_CLIENT_SETUP], "client_types", args, n);

  /***************** ctypeMenu : XmPulldownMenu *****************/
  widget_array[WI_CTYPEMENU2] =
    XmCreatePulldownMenu(widget_array[WI_NEW_CLIENT_SETUP], "ctypeMenu", NULL, 0);
  {
    Arg args[1];
    XtSetArg(args[0], XmNsubMenuId, widget_array[WI_CTYPEMENU2]);
    XtSetValues(widget_array[WI_CLIENT_TYPES2], args, 1);
  }

  /***************** no_swap : XmPushButton *****************/
  widget_array[WI_NO_SWAP] =
    XmCreatePushButton(widget_array[WI_CTYPEMENU2], "no_swap", NULL, 0);

  /***************** sep_swap : XmPushButton *****************/
  widget_array[WI_SEP_SWAP] =
    XmCreatePushButton(widget_array[WI_CTYPEMENU2], "sep_swap", NULL, 0);

  /***************** swap_on_root : XmPushButton *****************/
  widget_array[WI_SWAP_ON_ROOT] =
    XmCreatePushButton(widget_array[WI_CTYPEMENU2], "swap_on_root", NULL, 0);

  /***************** root_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNwidth, 64); n++;
  XtSetArg(args[n], XmNrecomputeSize, False); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_ROOT_LABEL2] =
    XmCreateLabel(widget_array[WI_NEW_CLIENT_SETUP], "root_label", args, n);

  /***************** numClients : XmTextField *****************/
  /* The number of clients.  The default value is 5. */
  n = 0;
  XtSetArg(args[n], XmNmaxLength, 5); n++;
  XtSetArg(args[n], XmNwidth, 80); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_NUMCLIENTS3] =
    XmCreateTextField(widget_array[WI_NEW_CLIENT_SETUP], "numClients", args, n);

  /***************** multiply : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_MULTIPLY2] =
    XmCreateLabel(widget_array[WI_NEW_CLIENT_SETUP], "multiply", args, n);

  /***************** size_per : XmTextField *****************/
  /* The default size of /root. */
  n = 0;
  XtSetArg(args[n], XmNwidth, 90); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_SIZE_PER1] =
    XmCreateTextField(widget_array[WI_NEW_CLIENT_SETUP], "size_per", args, n);

  /***************** equals : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_EQUALS2] =
    XmCreateLabel(widget_array[WI_NEW_CLIENT_SETUP], "equals", args, n);

  /***************** total_size : XmLabel *****************/
  /* The computed total from a multiplcation of number */
  /* of clients times size per client desired.  This field is */
  /* calculated, but can also be edited. -- Changed to a label for this release, will be changed back to an editable text field later. */
  n = 0;
  XtSetArg(args[n], XmNwidth, 90); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_TOTAL_SIZE1] =
    XmCreateLabel(widget_array[WI_NEW_CLIENT_SETUP], "total_size", args, n);

  /***************** mount_point : XmLabel *****************/
  /* The desired mount point for /root.  The default is /export/root. --- This will be changed back to an editable text field for the next release. */
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_MOUNT_POINT1] =
    XmCreateLabel(widget_array[WI_NEW_CLIENT_SETUP], "mount_point", args, n);

  /***************** select_toggle : XmToggleButton *****************/
  n = 0;
  XtSetArg(args[n], XmNindicatorType, XmONE_OF_MANY); n++;
  XtSetArg(args[n], XmNrecomputeSize, False); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_SELECT_TOGGLE] =
    XmCreateToggleButton(widget_array[WI_NEW_CLIENT_SETUP], "select_toggle", args, n);

  /* Terminate the widget array */
  widget_array[22] = NULL;


  /***************** platforms : XmOptionMenu *****************/
  n = 0;
  XtSetArg(args[n], XmNmenuHistory, widget_array[WI_ROOT_SVC_NONE]); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_CLIENT_TYPES2]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_PLATFORMS], args, n);

  XtAddCallback(widget_array[WI_ROOT_SVC_NONE],
                XmNactivateCallback,
                (XtCallbackProc)reset_to_none,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_ROOT_SVC_NONE]);
  XtAddCallback(widget_array[WI_NO_PLATFORM],
                XmNactivateCallback,
                (XtCallbackProc)set_separate_swap,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_NO_PLATFORM]);
  XtManageChild(widget_array[WI_PLATFORM_1]);
  XtManageChild(widget_array[WI_PLATFORM_2]);
  XtManageChild(widget_array[WI_PLATFORM_3]);
  XtManageChild(widget_array[WI_PLATFORMS]);

  /***************** client_types : XmOptionMenu *****************/
  n = 0;
  XtSetArg(args[n], XmNmenuHistory, widget_array[WI_NO_SWAP]); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_ROOT_LABEL2]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_CLIENT_TYPES2], args, n);

  XtAddCallback(widget_array[WI_NO_SWAP],
                XmNactivateCallback,
                (XtCallbackProc)show_root_only,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_NO_SWAP]);
  XtAddCallback(widget_array[WI_SEP_SWAP],
                XmNactivateCallback,
                (XtCallbackProc)show_root_and_swap,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_SEP_SWAP]);
  XtAddCallback(widget_array[WI_SWAP_ON_ROOT],
                XmNactivateCallback,
                (XtCallbackProc)show_swap_on_root,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_SWAP_ON_ROOT]);
  XtManageChild(widget_array[WI_CLIENT_TYPES2]);

  /***************** root_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_NUMCLIENTS3]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_ROOT_LABEL2], args, n);

  XtManageChild(widget_array[WI_ROOT_LABEL2]);

  /***************** numClients : XmTextField *****************/
  n = 0;
  XtAddCallback(widget_array[WI_NUMCLIENTS3],
                XmNactivateCallback,
                (XtCallbackProc)compute_size_total,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_MULTIPLY2]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_NUMCLIENTS3], args, n);

  XtManageChild(widget_array[WI_NUMCLIENTS3]);

  /***************** multiply : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_SIZE_PER1]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_MULTIPLY2], args, n);

  XtManageChild(widget_array[WI_MULTIPLY2]);

  /***************** size_per : XmTextField *****************/
  n = 0;
  XtAddCallback(widget_array[WI_SIZE_PER1],
                XmNactivateCallback,
                (XtCallbackProc)compute_size_total,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_EQUALS2]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SIZE_PER1], args, n);

  XtManageChild(widget_array[WI_SIZE_PER1]);

  /***************** equals : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_TOTAL_SIZE1]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_EQUALS2], args, n);

  XtManageChild(widget_array[WI_EQUALS2]);

  /***************** total_size : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_MOUNT_POINT1]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_TOTAL_SIZE1], args, n);

  XtManageChild(widget_array[WI_TOTAL_SIZE1]);

  /***************** mount_point : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_MOUNT_POINT1], args, n);

  XtManageChild(widget_array[WI_MOUNT_POINT1]);

  /***************** select_toggle : XmToggleButton *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_PLATFORMS]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SELECT_TOGGLE], args, n);

  XtManageChild(widget_array[WI_NEW_CLIENT_SETUP]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*23);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*23);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_NEW_CLIENT_SETUP]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_NEW_CLIENT_SETUP]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_NEW_CLIENT_SETUP];
}


/**************************************************************
 * tu_clientDialog_widget:
 **************************************************************/
Widget tu_clientDialog_widget(char    * name,
                              Widget    parent,
                              Widget ** warr_ret)
{
  Arg args[26];
  Widget widget_array[23];
  XtTranslations ttbl;
  int n;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmFormDialog *****************/
  widget_array[WI_CLIENTDIALOG] =
    XmCreateFormDialog(parent, name, NULL, 0);

  /***************** panelhelpText : XmText *****************/
  n = 0;
  XtSetArg(args[n], XmNautoShowCursorPosition, False); n++;
  XtSetArg(args[n], XmNcursorPositionVisible, False); n++;
  XtSetArg(args[n], XmNeditMode, XmMULTI_LINE_EDIT); n++;
  XtSetArg(args[n], XmNtraversalOn, False); n++;
  XtSetArg(args[n], XmNresizeHeight, True); n++;
  XtSetArg(args[n], XmNwordWrap, True); n++;
  XtSetArg(args[n], XmNshadowThickness, 0); n++;
  XtSetArg(args[n], XmNmarginWidth, 18); n++;
  XtSetArg(args[n], XmNmarginHeight, 18); n++;
  XtSetArg(args[n], XmNvalue, "message_text"); n++;
  widget_array[WI_PANELHELPTEXT] =
    XmCreateText(widget_array[WI_CLIENTDIALOG], "panelhelpText", args, n);

  /***************** form : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  XtSetArg(args[n], XmNmarginWidth, 10); n++;
  widget_array[WI_FORM] =
    XmCreateForm(widget_array[WI_CLIENTDIALOG], "form", args, n);

  /***************** client_form : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  widget_array[WI_CLIENT_FORM] =
    XmCreateForm(widget_array[WI_FORM], "client_form", args, n);

  /***************** client_scroll : XmScrolledWindow *****************/
  n = 0;
  XtSetArg(args[n], XmNheight, 150); n++;
  XtSetArg(args[n], XmNscrollingPolicy, XmAUTOMATIC); n++;
  XtSetArg(args[n], XmNwidth, 700); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_CLIENT_SCROLL] =
    XmCreateScrolledWindow(widget_array[WI_CLIENT_FORM], "client_scroll", args, n);

  /***************** main_table_rc : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNadjustLast, False); n++;
  XtSetArg(args[n], XmNorientation, XmVERTICAL); n++;
  widget_array[WI_MAIN_TABLE_RC] =
    XmCreateRowColumn(widget_array[WI_CLIENT_SCROLL], "main_table_rc", args, n);

  /***************** column_headers : XmForm *****************/
  /* Column headings for client setup table. */
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  XtSetArg(args[n], XmNallowOverlap, False); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_COLUMN_HEADERS] =
    XmCreateForm(widget_array[WI_CLIENT_FORM], "column_headers", args, n);

  /***************** platforms_label : XmLabel *****************/
  /* This label is unmanaged for now, it will go back in 2.6 */
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_CENTER); n++;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_PLATFORMS_LABEL] =
    XmCreateLabel(widget_array[WI_COLUMN_HEADERS], "platforms_label", args, n);

  /***************** client_types_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_CENTER); n++;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_CLIENT_TYPES_LABEL] =
    XmCreateLabel(widget_array[WI_COLUMN_HEADERS], "client_types_label", args, n);

  /***************** root_or_swap_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_CENTER); n++;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_ROOT_OR_SWAP_LABEL] =
    XmCreateLabel(widget_array[WI_COLUMN_HEADERS], "root_or_swap_label", args, n);

  /***************** numClients_label : XmLabel *****************/
  /* The number of clients.  The default value is 5. */
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_CENTER); n++;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_NUMCLIENTS_LABEL] =
    XmCreateLabel(widget_array[WI_COLUMN_HEADERS], "numClients_label", args, n);

  /***************** blank_label1 : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_CENTER); n++;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_BLANK_LABEL1] =
    XmCreateLabel(widget_array[WI_COLUMN_HEADERS], "blank_label1", args, n);

  /***************** size_per_label : XmLabel *****************/
  /* The default size of /root. */
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_CENTER); n++;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_SIZE_PER_LABEL] =
    XmCreateLabel(widget_array[WI_COLUMN_HEADERS], "size_per_label", args, n);

  /***************** blank_label2 : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_CENTER); n++;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_BLANK_LABEL2] =
    XmCreateLabel(widget_array[WI_COLUMN_HEADERS], "blank_label2", args, n);

  /***************** total_size_label : XmLabel *****************/
  /* The computed total from a multiplcation of number */
  /* of clients times size per client desired.  This field is */
  /* calculated, but can also be edited. */
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_CENTER); n++;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_TOTAL_SIZE_LABEL] =
    XmCreateLabel(widget_array[WI_COLUMN_HEADERS], "total_size_label", args, n);

  /***************** mount_point_label : XmLabel *****************/
  /* The desired mount point for /root.  The default is /export/root. */
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_CENTER); n++;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_MOUNT_POINT_LABEL] =
    XmCreateLabel(widget_array[WI_COLUMN_HEADERS], "mount_point_label", args, n);

  /***************** clientSetupMessageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdialogType, XmDIALOG_TEMPLATE); n++;
  widget_array[WI_CLIENTSETUPMESSAGEBOX] =
    XmCreateMessageBox(widget_array[WI_CLIENTDIALOG], "clientSetupMessageBox", args, n);

  /***************** clientContinueButton : XmPushButton *****************/
  n = 0;
  XtSetArg(args[n], XmNshowAsDefault, 1); n++;
  widget_array[WI_CLIENTCONTINUEBUTTON] =
    XmCreatePushButton(widget_array[WI_CLIENTSETUPMESSAGEBOX], "clientContinueButton", args, n);

  /***************** clientGobackButton : XmPushButton *****************/
  widget_array[WI_CLIENTGOBACKBUTTON] =
    XmCreatePushButton(widget_array[WI_CLIENTSETUPMESSAGEBOX], "clientGobackButton", NULL, 0);

  /***************** clientCancelButton : XmPushButton *****************/
  widget_array[WI_CLIENTCANCELBUTTON] =
    XmCreatePushButton(widget_array[WI_CLIENTSETUPMESSAGEBOX], "clientCancelButton", NULL, 0);

  /***************** clientExitButton : XmPushButton *****************/
  widget_array[WI_CLIENTEXITBUTTON] =
    XmCreatePushButton(widget_array[WI_CLIENTSETUPMESSAGEBOX], "clientExitButton", NULL, 0);

  /***************** clientHelpButton : XmPushButton *****************/
  widget_array[WI_CLIENTHELPBUTTON] =
    XmCreatePushButton(widget_array[WI_CLIENTSETUPMESSAGEBOX], "clientHelpButton", NULL, 0);

  /* Terminate the widget array */
  widget_array[22] = NULL;


  /***************** panelhelpText : XmText *****************/
  n = 0;
  ttbl = XtParseTranslationTable("#override\n\
~Ctrl ~Meta<BtnDown>:\n\
~Ctrl ~Meta<BtnUp>:");
  XtOverrideTranslations(widget_array[WI_PANELHELPTEXT], ttbl);
  unregister_as_dropsite(widget_array[WI_PANELHELPTEXT],
                         NULL,
                         NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_PANELHELPTEXT], args, n);

  XtManageChild(widget_array[WI_PANELHELPTEXT]);

  /***************** form : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_PANELHELPTEXT]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_CLIENTSETUPMESSAGEBOX]); n++;
  XtSetValues(widget_array[WI_FORM], args, n);


  /***************** client_form : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_CLIENT_FORM], args, n);


  /***************** client_scroll : XmScrolledWindow *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_CLIENT_SCROLL], args, n);

  XtManageChild(widget_array[WI_MAIN_TABLE_RC]);
  XtManageChild(widget_array[WI_CLIENT_SCROLL]);

  /***************** column_headers : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_CLIENT_SCROLL]); n++;
  XtSetValues(widget_array[WI_COLUMN_HEADERS], args, n);


  /***************** platforms_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_PLATFORMS_LABEL], args, n);


  /***************** client_types_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_PLATFORMS_LABEL]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_CLIENT_TYPES_LABEL], args, n);

  XtManageChild(widget_array[WI_CLIENT_TYPES_LABEL]);

  /***************** root_or_swap_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_CLIENT_TYPES_LABEL]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_ROOT_OR_SWAP_LABEL], args, n);

  XtManageChild(widget_array[WI_ROOT_OR_SWAP_LABEL]);

  /***************** numClients_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_ROOT_OR_SWAP_LABEL]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_NUMCLIENTS_LABEL], args, n);

  XtManageChild(widget_array[WI_NUMCLIENTS_LABEL]);

  /***************** blank_label1 : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_NUMCLIENTS_LABEL]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_BLANK_LABEL1], args, n);

  XtManageChild(widget_array[WI_BLANK_LABEL1]);

  /***************** size_per_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_BLANK_LABEL1]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SIZE_PER_LABEL], args, n);

  XtManageChild(widget_array[WI_SIZE_PER_LABEL]);

  /***************** blank_label2 : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_SIZE_PER_LABEL]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_BLANK_LABEL2], args, n);

  XtManageChild(widget_array[WI_BLANK_LABEL2]);

  /***************** total_size_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_BLANK_LABEL2]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_TOTAL_SIZE_LABEL], args, n);

  XtManageChild(widget_array[WI_TOTAL_SIZE_LABEL]);

  /***************** mount_point_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_TOTAL_SIZE_LABEL]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_MOUNT_POINT_LABEL], args, n);

  XtManageChild(widget_array[WI_MOUNT_POINT_LABEL]);
  XtManageChild(widget_array[WI_COLUMN_HEADERS]);
  XtManageChild(widget_array[WI_CLIENT_FORM]);
  XtManageChild(widget_array[WI_FORM]);

  /***************** clientSetupMessageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdefaultButton, widget_array[WI_CLIENTCONTINUEBUTTON]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_CLIENTSETUPMESSAGEBOX], args, n);

  XtAddCallback(widget_array[WI_CLIENTCONTINUEBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)clientContinueCB,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_CLIENTCONTINUEBUTTON]);
  XtAddCallback(widget_array[WI_CLIENTGOBACKBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)clientGobackCB,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_CLIENTGOBACKBUTTON]);
  XtAddCallback(widget_array[WI_CLIENTCANCELBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)clientCancelCB,
                (XtPointer)NULL);

  XtAddCallback(widget_array[WI_CLIENTEXITBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)clientExitCB,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_CLIENTEXITBUTTON]);
  XtAddCallback(widget_array[WI_CLIENTHELPBUTTON],
                XmNactivateCallback,
                pfgHelp,
                (XtPointer)"allocate.r");

  XtManageChild(widget_array[WI_CLIENTHELPBUTTON]);
  XtManageChild(widget_array[WI_CLIENTSETUPMESSAGEBOX]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*23);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*23);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_CLIENTDIALOG]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_CLIENTDIALOG]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_CLIENTDIALOG];
}



/****************************************************************
 * create_method:
 *     This function creates a widget hierarchy using the
 *     functions generated above.
 ****************************************************************/
static Widget create_method(char               * temp,
                            char               * name,
                            Widget               parent,
                            Display            * disp,
                            Screen             * screen,
                            tu_template_descr  * retval)
{
  Widget w;

  sDisplay = disp;
  sScreen = screen;

  /* check each node against its name and call its
   * create function if appropriate */
  w = NULL;
  if (strcmp(temp, "client_setup_table") == 0){
    w = tu_client_setup_table_widget(name, parent, (Widget **)retval);
  }
  else if (strcmp(temp, "client_setup") == 0){
    w = tu_client_setup_widget(name, parent, (Widget **)retval);
  }
  else if (strcmp(temp, "new_client_setup") == 0){
    w = tu_new_client_setup_widget(name, parent, (Widget **)retval);
  }
  else if (strcmp(temp, "clientDialog") == 0){
    w = tu_clientDialog_widget(name, parent, (Widget **)retval);
  }

  sDisplay = NULL;
  sScreen = NULL;
  return w;
}

