
/****************************************************************
 *
 * Name      : pfgInstallClients_ui.h
 *
 * File is generated by TeleUSE
 * Version : TeleUSE v3.0.2 / Solaris 2.4
 *
 * Copyright (c) 1994-1995 by Sun MicroSystems, Inc.
 * All rights reserved.
 *
 ****************************************************************/

#ifndef _PFGINSTALLCLIENTS_UI_H_
#define _PFGINSTALLCLIENTS_UI_H_

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Shell.h>

#include "tu_runtime.h"


/* widget creation functions */

extern Widget tu_client_setup_table_widget(char * name,
                                           Widget parent,
                                           Widget ** warr_ret);

extern Widget tu_client_setup_widget(char * name,
                                     Widget parent,
                                     Widget ** warr_ret);

extern Widget tu_new_client_setup_widget(char * name,
                                         Widget parent,
                                         Widget ** warr_ret);

extern Widget tu_clientDialog_widget(char * name,
                                     Widget parent,
                                     Widget ** warr_ret);

#define WI_CLIENT_SETUP_TABLE 0
#define WI_CLIENT_SETUP 1
#define WI_CLIENT_TYPES_FRAME 2
#define WI_CLIENT_TYPES 3
#define WI_CTYPEMENU 4
#define WI_ROOT_ONLY 5
#define WI_SWAP_ONLY 6
#define WI_ROOT_AND_SWAP 7
#define WI_ROOT_LABEL 8
#define WI_NUMCLIENTS 9
#define WI_MULTIPLY 10
#define WI_ROOT_SIZE_PER 11
#define WI_EQUALS 12
#define WI_TOTAL_ROOT_SIZE 13
#define WI_ROOT_MOUNT_POINT 14
#define WI_SWAP_SETUP 15
#define WI_SWAP_LABEL 16
#define WI_SWAP_NUMCLIENTS 17
#define WI_SWAP_MULTIPLY 18
#define WI_SWAP_SIZE_PER 19
#define WI_SWAP_EQUALS 20
#define WI_TOTAL_SWAP_SIZE 21
#define WI_SWAP_MOUNT_POINT 22
#define WI_S_ON_R_SETUP 23
#define WI_SONR_LABEL 24
#define WI_NUMCLIENTS1 25
#define WI_SONR_MULTIPLY 26
#define WI_SIZE_PER 27
#define WI_SONR_EQUALS 28
#define WI_TOTAL_SIZE 29
#define WI_MOUNT_POINT 30

#define WI_CLIENT_SETUP1 0
#define WI_CLIENT_TYPES_FRAME1 1
#define WI_CLIENT_TYPES1 2
#define WI_CTYPEMENU1 3
#define WI_ROOT_ONLY1 4
#define WI_SWAP_ONLY1 5
#define WI_ROOT_AND_SWAP1 6
#define WI_ROOT_LABEL1 7
#define WI_NUMCLIENTS2 8
#define WI_MULTIPLY1 9
#define WI_ROOT_SIZE_PER1 10
#define WI_EQUALS1 11
#define WI_TOTAL_ROOT_SIZE1 12
#define WI_ROOT_MOUNT_POINT1 13

#define WI_NEW_CLIENT_SETUP 0
#define WI_PLATFORMS 1
#define WI_PLATFORMMENU 2
#define WI_ROOT_SVC_NONE 3
#define WI_NO_PLATFORM 4
#define WI_DELETE 5
#define WI_PLATFORM_1 6
#define WI_PLATFORM_2 7
#define WI_PLATFORM_3 8
#define WI_CLIENT_TYPES2 9
#define WI_CTYPEMENU2 10
#define WI_NO_SWAP 11
#define WI_SEP_SWAP 12
#define WI_SWAP_ON_ROOT 13
#define WI_ROOT_LABEL2 14
#define WI_NUMCLIENTS3 15
#define WI_MULTIPLY2 16
#define WI_SIZE_PER1 17
#define WI_EQUALS2 18
#define WI_TOTAL_SIZE1 19
#define WI_MOUNT_POINT1 20
#define WI_SELECT_TOGGLE 21

#define WI_CLIENTDIALOG 0
#define WI_PANELHELPTEXT 1
#define WI_FORM 2
#define WI_CLIENT_FORM 3
#define WI_CLIENT_SCROLL 4
#define WI_MAIN_TABLE_RC 5
#define WI_COLUMN_HEADERS 6
#define WI_PLATFORMS_LABEL 7
#define WI_CLIENT_TYPES_LABEL 8
#define WI_ROOT_OR_SWAP_LABEL 9
#define WI_NUMCLIENTS_LABEL 10
#define WI_BLANK_LABEL1 11
#define WI_SIZE_PER_LABEL 12
#define WI_BLANK_LABEL2 13
#define WI_TOTAL_SIZE_LABEL 14
#define WI_MOUNT_POINT_LABEL 15
#define WI_CLIENTSETUPMESSAGEBOX 16
#define WI_CLIENTCONTINUEBUTTON 17
#define WI_CLIENTGOBACKBUTTON 18
#define WI_CLIENTCANCELBUTTON 19
#define WI_CLIENTEXITBUTTON 20
#define WI_CLIENTHELPBUTTON 21


#endif
