
/****************************************************************
 *
 * Name      : pfgLocale_ui.h
 *
 * File is generated by TeleUSE
 * Version : TeleUSE v3.0.2 / Solaris 2.4
 *
 * Copyright (c) 1994-1995 by Sun MicroSystems, Inc.
 * All rights reserved.
 *
 ****************************************************************/

#ifndef _PFGLOCALE_UI_H_
#define _PFGLOCALE_UI_H_

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Shell.h>

#include "tu_runtime.h"


/* widget creation functions */

extern Widget tu_locale_dialog_widget(char * name,
                                      Widget parent,
                                      Widget ** warr_ret);

#define WI_LOCALE_DIALOG 0
#define WI_PANELHELPTEXT 1
#define WI_FORM 2
#define WI_AVAILABLELABEL 3
#define WI_AVAILABLESCROLLEDLIST 4
#define WI_BUTTONFORM 5
#define WI_ADDBUTTON 6
#define WI_REMOVEBUTTON 7
#define WI_SELECTEDLABEL 8
#define WI_SELECTEDSCROLLEDLIST 9
#define WI_MESSAGEBOX 10
#define WI_CONTINUEBUTTON 11
#define WI_GOBACKBUTTON 12
#define WI_EXITBUTTON 13
#define WI_HELPBUTTON 14
#define WI_BUTTON5 15


#endif
