
/****************************************************************
 *
 * Name      : pfgSolarPart_ui.h
 *
 * File is generated by TeleUSE
 * Version : TeleUSE v3.0.2 / Solaris 2.4
 *
 * Copyright (c) 1994-1995 by Sun MicroSystems, Inc.
 * All rights reserved.
 *
 ****************************************************************/

#ifndef _PFGSOLARPART_UI_H_
#define _PFGSOLARPART_UI_H_

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Shell.h>

#include "tu_runtime.h"


/* widget creation functions */

extern Widget tu_solarpart_dialog_widget(char * name,
                                         Widget parent,
                                         Widget ** warr_ret);

#define WI_SOLARPART_DIALOG 0
#define WI_PANELHELPTEXT 1
#define WI_SOLARPARTFORM 2
#define WI_SOLARPARTRADIOBOX 3
#define WI_ENTIRETOGGLE 4
#define WI_REMAINDERTOGGLE 5
#define WI_CUSTOMTOGGLE 6
#define WI_MESSAGEBOX 7
#define WI_OKBUTTON 8
#define WI_CANCELBUTTON 9
#define WI_HELPBUTTON 10
#define WI_BUTTON4 11
#define WI_BUTTON5 12


#endif
