
/****************************************************************
 *
 * Name      : pfgSolarCust_ui.h
 *
 * File is generated by TeleUSE
 * Version : TeleUSE v3.0.2 / Solaris 2.4
 *
 * Copyright (c) 1994-1995 by Sun MicroSystems, Inc.
 * All rights reserved.
 *
 ****************************************************************/

#ifndef _PFGSOLARCUST_UI_H_
#define _PFGSOLARCUST_UI_H_

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Shell.h>

#include "tu_runtime.h"


/* widget creation functions */

extern Widget tu_solarcust_dialog_widget(char * name,
                                         Widget parent,
                                         Widget ** warr_ret);

extern Widget tu_fdisk_entry_widget(char * name,
                                    Widget parent,
                                    Widget ** warr_ret);

#define WI_SOLARCUST_DIALOG 0
#define WI_PANELHELPTEXT 1
#define WI_SOLARCUSTFORM 2
#define WI_FDISKLABELFORM 3
#define WI_FDISKPARTITIONNAME 4
#define WI_FDISKPARTITIONSIZE 5
#define WI_FDISKCYLINDER 6
#define WI_FDISKROWCOLUMN 7
#define WI_LABELROWCOLUMN 8
#define WI_CAPACITYLABEL 9
#define WI_ALLOCATEDLABEL 10
#define WI_FREELABEL 11
#define WI_ROUNDINGLABEL 12
#define WI_SIZEROWCOLUMN 13
#define WI_CAPACITYVALUE 14
#define WI_ALLOCATEDVALUE 15
#define WI_FREEVALUE 16
#define WI_ROUNDINGVALUE 17
#define WI_MESSAGEBOX 18
#define WI_OKBUTTON 19
#define WI_CANCELBUTTON 20
#define WI_HELPBUTTON 21
#define WI_BUTTON4 22
#define WI_BUTTON5 23

#define WI_FDISK_ENTRY 0
#define WI_FDISKOPTIONMENU 1
#define WI_PULLDOWNMENU 2
#define WI_SOLARBUTTON 3
#define WI_DOSBUTTON 4
#define WI_UNUSEDBUTTON 5
#define WI_OTHERBUTTON 6
#define WI_FDISKSIZETEXT 7
#define WI_FDISKSTARTCYLINDER 8


#endif
