
/****************************************************************
 *
 * Name      : pfgUseDisks_ui.h
 *
 * File is generated by TeleUSE
 * Version : TeleUSE v3.0.2 / Solaris 2.4
 *
 * Copyright (c) 1994-1995 by Sun MicroSystems, Inc.
 * All rights reserved.
 *
 ****************************************************************/

#ifndef _PFGUSEDISKS_UI_H_
#define _PFGUSEDISKS_UI_H_

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Shell.h>

#include "tu_runtime.h"


/* widget creation functions */

extern Widget tu_usedisks_dialog_widget(char * name,
                                        Widget parent,
                                        Widget ** warr_ret);

#define WI_USEDISKS_DIALOG 0
#define WI_PANELHELPTEXT 1
#define WI_FORM 2
#define WI_AVAILABLELABEL 3
#define WI_AVAILABLESCROLLEDLIST 4
#define WI_TOTALAVAILABLELABEL 5
#define WI_TOTALAVAILABLEVALUE 6
#define WI_BUTTONFORM 7
#define WI_ADDBUTTON 8
#define WI_REMOVEBUTTON 9
#define WI_AUTOADDBUTTON 10
#define WI_REMOVEALLBUTTON 11
#define WI_SOLARBUTTON 12
#define WI_SELECTEDLABEL 13
#define WI_SELECTEDSCROLLEDLIST 14
#define WI_ROWCOLUMN 15
#define WI_RECOMMENDLABEL 16
#define WI_MINIMUMLABEL 17
#define WI_USETOTALLABEL 18
#define WI_ROWCOLUMN1 19
#define WI_RECOMMENDVALUE 20
#define WI_MINIMUMVALUE 21
#define WI_USETOTALVALUE 22
#define WI_BOOT_DEVICE_FORM 23
#define WI_BOOT_LABEL 24
#define WI_CHANGEBUTTON 25
#define WI_MESSAGEBOX 26
#define WI_CONTINUEBUTTON 27
#define WI_GOBACKBUTTON 28
#define WI_EXITBUTTON 29
#define WI_HELPBUTTON 30
#define WI_BUTTON5 31


#endif
