#
# uts/sun4c/Makefile.rules
# Copyright (c) 1991 by Sun Microsystems, Inc.
#
#ident   "@(#)Makefile.rules 1.32     96/06/10 SMI"
#
#	This Makefile defines the build rules for the directory uts/sun4c
#	and it's children. These are the source files which sun4c
#	"implementation architecture" dependent.
#

#
#	This was implemented by pattern matching rules of the form:
#
# $(OBJS_DIR)/%.o:	 $(UTSBASE)/common/os/%.c
#	$(COMPILE.c) -o $@ $<
#
# $(LINTS_DIR)/%.ln:	$(UTSBASE)/common/os/%.c
#	@($(LHEAD) $(LINT.c) $< $(LTAIL))
#
#	For each directory containing source. This proved to slow under
#	Nse because it caused a significant additional number of stats
#	and stats are real slow under TFS. If TFS performance should
#	improve, one might consider returning to the former implementation.
#	In the former implementation, this file (Makefile.rules) was not
#	needed and the pattern matching rules were in Makefile.files.
#

#
#	C object build rules
#
#	The following are alphabetized by source file path. Please maintain
# this ordering.
#
$(OBJS_DIR)/swtch.o:            $(UTSBASE)/sun4c/ml/swtch.s
	$(COMPILE.s) -o $@ $(UTSBASE)/sun4c/ml/swtch.s

$(OBJS_DIR)/confunix.o:		$(UTSBASE)/sun4c/conf/confunix.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4c/conf/confunix.c

$(OBJS_DIR)/autoconf.o:		$(UTSBASE)/sun4c/io/autoconf.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4c/io/autoconf.c

$(OBJS_DIR)/hardclk.o:		$(UTSBASE)/sun4c/io/hardclk.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4c/io/hardclk.c

$(OBJS_DIR)/copy.o:		$(UTSBASE)/sun4c/ml/copy.s
	$(COMPILE.s) -o $@ $(UTSBASE)/sun4c/ml/copy.s

$(OBJS_DIR)/ip_ocsum.o:		$(UTSBASE)/sun4c/ml/ip_ocsum.s
	$(COMPILE.s) -o $@ $(UTSBASE)/sun4c/ml/ip_ocsum.s

$(OBJS_DIR)/locore.o:		$(UTSBASE)/sun4c/ml/locore.s
	$(COMPILE.s) -o $@ $(UTSBASE)/sun4c/ml/locore.s

$(OBJS_DIR)/map.o:		$(UTSBASE)/sun4c/ml/map.s
	$(COMPILE.s) -o $@ $(UTSBASE)/sun4c/ml/map.s

$(OBJS_DIR)/memerr.o:		$(UTSBASE)/sun4c/ml/memerr.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4c/ml/memerr.c

$(OBJS_DIR)/notes.o:		$(UTSBASE)/sparc/ml/notes.s
	$(COMPILE.s) -o $@ $(UTSBASE)/sparc/ml/notes.s

$(OBJS_DIR)/subr_4c.o:		$(UTSBASE)/sun4c/ml/subr_4c.s
	$(COMPILE.s) -o $@ $(UTSBASE)/sun4c/ml/subr_4c.s

$(OBJS_DIR)/atomic.o:		$(UTSBASE)/sun4c/os/atomic.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4c/os/atomic.c

$(OBJS_DIR)/bp_map.o:		$(UTSBASE)/sun4c/os/bp_map.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4c/os/bp_map.c

$(OBJS_DIR)/ddi_impl.o:		$(UTSBASE)/sun4c/os/ddi_impl.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4c/os/ddi_impl.c

$(OBJS_DIR)/dvma.o:		$(UTSBASE)/sun4c/os/dvma.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4c/os/dvma.c

$(OBJS_DIR)/kalloc.o:		$(UTSBASE)/sun4c/os/kalloc.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4c/os/kalloc.c

$(OBJS_DIR)/mach_sysconfig.o:	$(UTSBASE)/sun4c/os/mach_sysconfig.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4c/os/mach_sysconfig.c

$(OBJS_DIR)/mach_page.o:	$(UTSBASE)/common/vm/mach_page.c
	$(COMPILE.c) -o $@ $(UTSBASE)/common/vm/mach_page.c

$(OBJS_DIR)/machdep.o:		$(UTSBASE)/sun4c/os/machdep.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4c/os/machdep.c

$(OBJS_DIR)/mlsetup.o:		$(UTSBASE)/sun4c/os/mlsetup.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4c/os/mlsetup.c

$(OBJS_DIR)/ppage.o:		$(UTSBASE)/sun4c/os/ppage.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4c/os/ppage.c

$(OBJS_DIR)/rootnex.o:		$(UTSBASE)/sun4c/io/rootnex.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4c/io/rootnex.c

$(OBJS_DIR)/startup.o:		$(UTSBASE)/sun4c/os/startup.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4c/os/startup.c

$(OBJS_DIR)/stubs.o:		$(UTSBASE)/sun4c/os/stubs.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4c/os/stubs.c

$(OBJS_DIR)/trap.o:		$(UTSBASE)/sun4c/os/trap.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4c/os/trap.c

$(OBJS_DIR)/mmu.o:		$(UTSBASE)/sun4c/vm/mmu.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4c/vm/mmu.c

$(OBJS_DIR)/vm_machdep.o:	$(UTSBASE)/sun4c/vm/vm_machdep.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4c/vm/vm_machdep.c

$(OBJS_DIR)/obpsym.o:		$(UTSBASE)/sparc/os/obpsym.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sparc/os/obpsym.c
 
$(OBJS_DIR)/obpsym_obp.o:	$(UTSBASE)/sparc/os/obpsym_obp.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sparc/os/obpsym_obp.c
 
$(OBJS_DIR)/bootdev.o:		$(UTSBASE)/sparc/os/bootdev.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sparc/os/bootdev.c
 
#
#	Lint `object' build rules
#
#	The following are alphabetized by source file path. Please maintain
# this ordering.
#
$(LINTS_DIR)/swtch.ln:          $(UTSBASE)/sun4c/ml/swtch.s
	@($(LHEAD) $(LINT.s) $(UTSBASE)/sun4c/ml/swtch.s $(LTAIL))

$(LINTS_DIR)/confunix.ln:	$(UTSBASE)/sun4c/conf/confunix.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4c/conf/confunix.c $(LTAIL))

$(LINTS_DIR)/autoconf.ln:	$(UTSBASE)/sun4c/io/autoconf.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4c/io/autoconf.c $(LTAIL))

$(LINTS_DIR)/hardclk.ln:	$(UTSBASE)/sun4c/io/hardclk.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4c/io/hardclk.c $(LTAIL))

$(LINTS_DIR)/copy.ln:		$(UTSBASE)/sun4c/ml/copy.s
	@($(LHEAD) $(LINT.s) $(UTSBASE)/sun4c/ml/copy.s $(LTAIL))

$(LINTS_DIR)/ip_ocsum.ln:	$(UTSBASE)/sun4c/ml/ip_ocsum.s
	@($(LHEAD) $(LINT.s) $(UTSBASE)/sun4c/ml/ip_ocsum.s $(LTAIL))

$(LINTS_DIR)/locore.ln:		$(UTSBASE)/sun4c/ml/locore.s
	@($(LHEAD) $(LINT.s) $(UTSBASE)/sun4c/ml/locore.s $(LTAIL))

$(LINTS_DIR)/map.ln:		$(UTSBASE)/sun4c/ml/map.s
	@($(LHEAD) $(LINT.s) $(UTSBASE)/sun4c/ml/map.s $(LTAIL))

$(LINTS_DIR)/memerr.ln:		$(UTSBASE)/sun4c/ml/memerr.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4c/ml/memerr.c $(LTAIL))

$(LINTS_DIR)/subr_4c.ln:	$(UTSBASE)/sun4c/ml/subr_4c.s
	@($(LHEAD) $(LINT.s) $(UTSBASE)/sun4c/ml/subr_4c.s $(LTAIL))

$(LINTS_DIR)/atomic.ln:		$(UTSBASE)/sun4c/os/atomic.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4c/os/atomic.c $(LTAIL))

$(LINTS_DIR)/bp_map.ln:		$(UTSBASE)/sun4c/os/bp_map.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4c/os/bp_map.c $(LTAIL))

$(LINTS_DIR)/ddi_impl.ln:	$(UTSBASE)/sun4c/os/ddi_impl.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4c/os/ddi_impl.c $(LTAIL))

$(LINTS_DIR)/dvma.ln:		$(UTSBASE)/sun4c/os/dvma.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4c/os/dvma.c $(LTAIL))

$(LINTS_DIR)/kalloc.ln:		$(UTSBASE)/sun4c/os/kalloc.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4c/os/kalloc.c $(LTAIL))

$(LINTS_DIR)/mach_sysconfig.ln:	$(UTSBASE)/sun4c/os/mach_sysconfig.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4c/os/mach_sysconfig.c $(LTAIL))

$(LINTS_DIR)/mach_page.ln:	$(UTSBASE)/common/vm/mach_page.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/common/vm/mach_page.c $(LTAIL))

$(LINTS_DIR)/machdep.ln:	$(UTSBASE)/sun4c/os/machdep.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4c/os/machdep.c $(LTAIL))

$(LINTS_DIR)/mlsetup.ln:	$(UTSBASE)/sun4c/os/mlsetup.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4c/os/mlsetup.c $(LTAIL))

$(LINTS_DIR)/notes.ln:		$(UTSBASE)/sparc/ml/notes.s
	@($(LHEAD) $(LINT.s) $(UTSBASE)/sparc/ml/notes.s $(LTAIL))

$(LINTS_DIR)/ppage.ln:		$(UTSBASE)/sun4c/os/ppage.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4c/os/ppage.c $(LTAIL))

$(LINTS_DIR)/rootnex.ln:	$(UTSBASE)/sun4c/io/rootnex.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4c/io/rootnex.c $(LTAIL))

$(LINTS_DIR)/startup.ln:	$(UTSBASE)/sun4c/os/startup.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4c/os/startup.c $(LTAIL))

$(LINTS_DIR)/stubs.ln:		$(UTSBASE)/sun4c/os/stubs.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4c/os/stubs.c $(LTAIL))

$(LINTS_DIR)/trap.ln:		$(UTSBASE)/sun4c/os/trap.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4c/os/trap.c $(LTAIL))

$(LINTS_DIR)/mmu.ln:		$(UTSBASE)/sun4c/vm/mmu.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4c/vm/mmu.c $(LTAIL))

$(LINTS_DIR)/vm_machdep.ln:	$(UTSBASE)/sun4c/vm/vm_machdep.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4c/vm/vm_machdep.c $(LTAIL))

$(LINTS_DIR)/obpsym.ln:		$(UTSBASE)/sparc/os/obpsym.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sparc/os/obpsym.c $(LTAIL))
 
$(LINTS_DIR)/obpsym_obp.ln:	$(UTSBASE)/sparc/os/obpsym_obp.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sparc/os/obpsym_obp.c $(LTAIL))
 
$(LINTS_DIR)/bootdev.ln:	$(UTSBASE)/sparc/os/bootdev.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sparc/os/bootdev.c $(LTAIL))
 
