#
# Copyright (c) 1996 by Sun Microsystems, Inc.
# All rights reserved.
#
# ident	"@(#)sections.msg	1.3	96/08/19 SMI"
#
# Message file for cmd/sgs/libconv/common/sections.c

@ MSG_SHT_NULL		"[ SHT_NULL ]"
@ MSG_SHT_PROGBITS	"[ SHT_PROGBITS ]"
@ MSG_SHT_SYMTAB	"[ SHT_SYMTAB ]"
@ MSG_SHT_STRTAB	"[ SHT_STRTAB ]"
@ MSG_SHT_RELA		"[ SHT_RELA ]"
@ MSG_SHT_HASH		"[ SHT_HASH ]"
@ MSG_SHT_DYNAMIC	"[ SHT_DYNAMIC ]"
@ MSG_SHT_NOTE		"[ SHT_NOTE ]"
@ MSG_SHT_NOBITS	"[ SHT_NOBITS ]"
@ MSG_SHT_REL		"[ SHT_REL ]"
@ MSG_SHT_SHLIB		"[ SHT_SHLIB ]"
@ MSG_SHT_DYNSYM	"[ SHT_DYNSYM ]"

@ MSG_SHT_SUNW_verdef	"[ SHT_SUNW_verdef ]"
@ MSG_SHT_SUNW_verneed	"[ SHT_SUNW_verneed ]"
@ MSG_SHT_SUNW_versym	"[ SHT_SUNW_versym ]"

@ MSG_SHF_WRITE		" SHF_WRITE "
@ MSG_SHF_ALLOC		" SHF_ALLOC "
@ MSG_SHF_EXECINSTR	" SHF_EXECINSTR "
@ MSG_SHF_EXCLUDE	" SHF_EXCLUDE "
@ MSG_SHF_ORDERED	" SHF_ORDERED "

@ MSG_GBL_ZERO		"0"
@ MSG_GBL_OSQBRKT	"["
@ MSG_GBL_CSQBRKT	"]"
