#
# Copyright (c) 1996 by Sun Microsystems, Inc.
# All rights reserved.
#
# ident	"@(#)symbols.msg	1.2	96/02/26 SMI"
#
# Message file for cmd/sgs/libconv/common/symbols.c

@ MSG_STT_NOTYPE	"NOTY"
@ MSG_STT_OBJECT	"OBJT"
@ MSG_STT_FUNC		"FUNC"
@ MSG_STT_SECTION	"SECT"
@ MSG_STT_FILE		"FILE"

@ MSG_STB_LOCAL		"LOCL"
@ MSG_STB_GLOBAL	"GLOB"
@ MSG_STB_WEAK		"WEAK"

@ MSG_SHN_UNDEF		"UNDEF"
@ MSG_SHN_ABS		"ABS"
@ MSG_SHN_COMMON	"COMMON"
