#
#ident	"@(#)Makefile	1.4	96/08/16 SMI"
#
# Copyright (c) 1993 by Sun Microsystems, Inc.
#

include ../Makefile.com

DATAFILES += i.preserve i.rOWconfig

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
