#
#ident	"@(#)Makefile	1.9	94/02/03 SMI"
#
# Copyright (c) 1993, 1994 by Sun Microsystems, Inc.
#
# cmd/sgs/dis/sparc/Makefile
#

MACHOBJS=	bits.o disasm.o sas_tables.o tables.o

DEFLIST=	-DM32 -DFBO -DSPARC -DELF

include		../common/Makefile.com
