#
# Copyright (c) 1994 by Sun Microsystems, Inc.
#
#pragma ident	"@(#)Makefile	1.1	94/02/01 SMI"
#
# cmd/adb/prep/Makefile
#

ARCHITECTURE=	ppc
MACHINE=	prep
ARCH=		prep

include ../$(ARCHITECTURE)/Makefile

