#
#ident	"@(#)Makefile.targ	1.1	96/04/10 SMI"
#
# Copyright (c) 1996 by Sun Microsystems, Inc.
# All rights reserved.

pics/%.o:	../common/%.c
		$(COMPILE.c) -o $@ $<
		$(POST_PROCESS_O)

all:		$(DYNLIB)

include		$(SRC)/lib/Makefile.targ

delete:
		$(RM) $(DYNLIB)

install:	all $(ROOTDYNLIB)

lint:
		$(LINT.c) $(SRCS) > $(LINTOUT) 2>&1
