#
#ident	"@(#)Makefile.targ	1.1	94/05/18 SMI"
#
# Copyright (c) 1994 by Sun Microsystems, Inc.
#

.KEEP_STATE:

all:		$(PROG)

$(PROG):	$(OBJS)
		$(LD) -o $@ $(LDFLAGS) $(OBJS)

clean:
		$(RM) $(OBJS) $(CLEANFILES)

delete:
		$(RM) $(PROG)

install:	all $(ROOTLIBPROG)

lint:

include		../../../Makefile.targ
