#
#ident	"@(#)Makefile	1.1	92/06/05 SMI"
#
# Copyright (c) 1992 by Sun Microsystems, Inc.
#
# lib/libbsdmalloc/Makefile
#
LIBRARY= libbsdmalloc.a

OBJECTS= malloc.bsd43.o

# include library definitions
include ../Makefile.lib

.KEEP_STATE:

all: $(LIBS)

install: $(ROOTLIBS)

# include library targets
include ../Makefile.targ
