#
#ident	"@(#)Makefile	1.2	95/08/16 SMI"
#
# Copyright (c) 1995 by Sun Microsystems, Inc.
# All rights reserved.
#

include ../Makefile.com

.KEEP_STATE:

all:		$(DYNLIB) $(LIBLINKS)
install:	all $(ROOTDYNLIB) $(ROOTLINKS)

include ../Makefile.targ
