#
#ident	"@(#)Makefile.targ	1.3	93/10/01 SMI"
#
# Copyright (c) 1993 by Sun Microsystems, Inc.
#

pkginfo: pkginfo.tmpl ../awk_pkginfo
	$(RM) $@; nawk -f ../awk_pkginfo $@.tmpl > $@

pkg: $(PKGARCHIVE) FRC
	pkgmk -f prototype_$(MACH) -d $(PKGARCHIVE) -r $(ROOT) -o $(PACKAGE)

$(PKGARCHIVE):
	[ -d $(PKGARCHIVE) ] || mkdir $(PKGARCHIVE)

$(DATAFILES): ../common_files/$$@
	$(RM) $@; cp ../common_files/$@ $@

clobber clean:
	-$(RM) $(CLOBBERFILES) $(CLEANFILES)

FRC:
