#
#ident	"@(#)Makefile	1.1	94/05/27 SMI"
#
# Copyright (c) 1994 by Sun Microsystems, Inc.
#

include ../Makefile.com

.KEEP_STATE:

DATAFILES += depend

all: $(FILES)
install: all pkg

include ../Makefile.targ
