#
#ident	@(#)Makefile 1.4 94/12/11
#
# Copyright (c) 1993 by Sun Microsystems, Inc.
# All rights reserved.
#

include ../Makefile.com

DATAFILES +=

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
